# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Omavoi einrichten',
 "first.blurb": "Drei Fragen, dann ein Knopf. Nichts läuft, bis du drückst, und jeder Befehl wird vorher gezeigt.",
 "first.pick.language": 'Sprache der Oberfläche',
 "first.pick.model": 'Sprachmodell',
 "first.reuse": "ein Erkennungsmodell, das auf diesem Rechner schon liegt — dort genutzt, wo es liegt, kein Download",
 "first.reuse.label": 'Vorhandene nutzen',
 "first.m.large": "die Turbo-Modelle können Stille nicht von Sprache unterscheiden, dieses kann es",
 "first.m.turbo": "die Vorgabe; halber Download und schneller",
 "first.m.light": "das Leichteste, das sich noch lohnt",
 "first.willrun": 'WAS AUSGEFÜHRT WIRD',
 "first.needspassword": 'fragt nach deinem Passwort',
 "first.install": 'Installieren',
 "first.retry": 'Erneut versuchen',
 "first.working": '%1 …',
 "first.failed": '%1 fehlgeschlagen — siehe unten',
 "first.cancelled": 'die Passwortabfrage wurde abgebrochen, es wurde nichts installiert',
 "first.done": 'Bereit — Taste halten und sprechen',
 "first.dbstale": "Eine Installation kann jetzt mit 404 scheitern: Die dort genannten Versionen liegen vielleicht nicht mehr auf den Spiegeln. Erst das System zu aktualisieren ist die sichere Reihenfolge.",
 "first.updatebtn": 'Systempakete aktualisieren',
 "first.pacman404": 'Die Paketdatenbank ist veraltet, die Spiegel haben die dort genannten Versionen nicht mehr. Aktualisiere oben das System und versuche es erneut.',
 "first.pick.hotkey": 'Taste zum Sprechen',
 "first.hotkey.other": 'andere Taste, z. B. F9',
 "first.hotkey.note": "Wird unterhalb deines Tastaturlayouts gelesen und nie übernommen, die Taste macht also weiter, was sie sonst macht. Auf vielen Layouts außerhalb der USA ist die rechte Alt-Taste AltGr und tippt dort Zeichen — nimm die rechte Strg-Taste oder Rollen, wenn das bei dir so ist.",
 "first.group.needed": "Du bist noch nicht in der Gruppe input, also kann keine Taste gelesen werden. Der Schritt unten fügt dich hinzu und startet den Hintergrunddienst so, dass er die Gruppe sofort hat — kein Abmelden nötig.",
 "first.step.hotkey": 'Tastenkürzel',
 "first.step.packages": 'Systempakete',
 "first.step.daemon": "der Hintergrunddienst",
 "first.step.language": 'Sprache',
 "first.step.weights": "Erkennungsmodell",
 "first.step.use": 'Modell auswählen',
 "first.step.mode": 'Vorgabemodus',
 "first.step.service": 'Unit, Tastenkürzel und Menüeintrag',
 "up.title": 'AKTUALISIEREN',
 "up.behind": '%1 neue Commits auf dem Zweig des Plugins',
 "up.current": 'Aktuell',
 "up.daemon.blind": "Der Hintergrunddienst ist separat installiert, daher lässt sich hier nicht sagen, ob er aktuell ist; Aktualisieren installiert ihn so oder so neu.",
 "up.unknown": 'Nicht feststellbar — das Plugin wurde nicht aus git installiert',
 "up.nofetch": "Das Remote war nicht erreichbar, dies ist also vielleicht nicht der neueste Stand: %1",
 "up.noupstream": "Der Branch des Plugins hat kein Upstream, es gibt also nichts zu vergleichen",
 "up.dirty": 'Das installierte Plugin hat lokale Änderungen und kann nicht vorspulen. Installiere es neu: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Aktualisieren',
 "up.again": 'Erneut prüfen',
 "up.done": 'Aktualisiert',
 "up.step.plugin": 'das Plugin',
 "up.step.daemon": "der Hintergrunddienst",
 "up.step.shortcuts": 'Unit, Tastenkürzel und Menüeintrag',
 "up.step.restart": 'neu starten',
 "nav.setup": 'Einrichtung',
 "setup.rootblurb": "Die Schritte oben, die ein Administratorpasswort brauchen, lassen sich hier in einem Zug erledigen, mit einer Passwortabfrage. Danach startet der Hintergrunddienst neu, damit er das Installierte erkennt.",
 "setup.rootrun": 'Diese installieren',
 "nav.history": "Verlauf",
 "nav.modes": "Modi",
 "nav.models": "Modelle",
 "nav.dictionary": 'Mein Wörterbuch',
 "nav.settings": "Einstellungen",
 "state.idle": "bereit",
 "state.recording": "Aufnahme",
 "state.transcribing": "Transkription",
 "state.stopped": "Dienst gestoppt",
 "hud.stage.decoding": 'Transkription',
 "hud.stage.llm": 'Umschreiben',
 "hud.stage.injecting": 'Eingabe',
 "hud.nospeech": "keine Sprache gehört",

 "setup.prefix": "Einrichtung ",
 "setup.title": "Noch offen: %1",
 "setup.titledone": 'Alles ist vorhanden',
 "setup.blurb": "Hier läuft nichts, bevor du drückst, und jeder Schritt zeigt vorher seinen Befehl.",
 "setup.copy": "Kopieren",
 "setup.run": "Ausführen",
 "setup.recheck": "Neu prüfen",
 "setup.hint": "oder  omavoi setup  im Terminal ausführen — gleiche Schritte, "
               "gleiche Reihenfolge",

 "hist.problems": "WAS SCHIEFGING",
 "hist.fellthrough": "hat nicht geklappt — der Text von davor wurde verwendet",
 "hist.none": "noch keine Aufnahmen — %1 halten und sprechen",
 "hist.yourkey": "deine Taste",
 "hist.audio": "Länge",
 "hist.level": "Lautstärke",
 "hist.decode": "Erkennung dauerte",
 "hist.model": "Modell",
 "hist.language": "Sprache",
 "hist.injected": "getippt mit",
 "hist.said": "WAS ES GEHÖRT HAT",
 "hist.post": "WAS DIE BEREINIGUNG GEÄNDERT HAT",
 "hist.segments": "SEGMENT-KONFIDENZ",
 "hist.copy": "Kopieren",
 "hist.play": "Abspielen",
 "hist.delete": "Löschen",

 "modes.wontfit": 'braucht %1 frei',
 "modes.blocked": "nicht gewechselt — das Modell dieses Modus passt gerade nicht in den Grafikspeicher",
 "modes.speechmodel": "Erkennungsmodell",
 "modes.speechglobal": "Standard verwenden",
 "modes.speechglobalnamed": "Standard verwenden (%1)",
 "modes.speechonly1": "Nur ein Erkennungsmodell ist heruntergeladen. Im Tab Modelle gibt es kleinere, für einen Modus, in dem Geschwindigkeit mehr zählt als Genauigkeit.",
 "modes.newname": "Name des neuen Modus",
 "modes.here": "in Gebrauch",
 "modes.fallback": "Rückfall",
 "modes.followwin": "Der Modus folgt dem fokussierten Fenster",
 "modes.everytake": "Jede Aufnahme nutzt ",
 "modes.longestwins": "Die längste Übereinstimmung unten gewinnt; passt nichts, "
                      "greift default.",
 "modes.matchoff": "Fensterabgleich ist aus, die Listen unten sind also "
                   "konfiguriert, aber wirkungslos. Er will pro Anwendung "
                   "eingestellt werden, bevor er sich lohnt.",
 "modes.hiddenauto": "Das fokussierte Fenster wählt den Modus, ein Klick unten öffnet ihn also nur.",
 "modes.following": "dem Fenster folgen",
 "modes.fixed": "hier wählen",
 "modes.delete": "Modus löschen",
 "modes.opens": "ÖFFNET BEI",
 "modes.notinuse": "nicht in Gebrauch, solange der Modus fest ist",
 "modes.nothing": "nichts — dieser Modus wird nur über seinen Namen erreicht",
 "modes.classph": "Fensterklasse, z. B. thunderbird",
 "modes.add": "Hinzufügen",
 "modes.matchhint": "Abgeglichen mit Klasse und Titel aus Hyprland. Die längste "
                    "Übereinstimmung gewinnt.",
 "modes.s1": "SPRACHE",
 "modes.language": "gesprochene Sprache",
 "modes.decoderhint": "Erkennungshinweis",
 "modes.promptph": "z. B. Ein Meeting über Hyprland, Quickshell und PipeWire.",
 "modes.s2": "BEREINIGUNG",
 "modes.rulessub": "Ohne KI: sofort, und jedes Mal gleich.",
 "modes.r.hallucinations": "wiederholte Sätze zusammenfassen",
 "modes.r.fillers": "Füllwörter entfernen",
 "modes.r.dictionary": "Wörterbuch",
 "modes.r.names": "Namen",
 "modes.r.cjk": "Abstand zwischen CJK und Latein",
 "modes.s3": "KI-ÜBERARBEITUNG",
 "modes.llmsub": "Optional. Jeder Schritt kostet ein paar Sekunden; scheitert einer, gibt er den Text weiter, den er bekommen hat.",
 "modes.step": "Schritt ",
 "modes.stepsuffix": "",
 "modes.remove": "Entfernen",
 "modes.stepph": "Sag ihm, es soll bearbeiten, nicht antworten.",
 "modes.addstep": "+ Überarbeitungsschritt hinzufügen",
 "modes.weights": "Modell",
 "modes.inherit": "Standard verwenden (%1)",
 "modes.nollm": "noch kein KI-Modell eingerichtet — siehe Tab Modelle",
 "modes.inject.auto": "auto",
 "modes.inject.type": "tippen",
 "modes.inject.clipboard": "einfügen",
 "modes.langauto": "auto",
 "modes.s4": "Eingabe",

 "models.speech": "SPRACHERKENNUNG",
 "models.speechsub": "Macht aus dem Gesagten Text. Immer nur auf eine Art.",
 "models.e.vulkan": "Auf diesem Rechner",
 "models.e.vulkan.sub": "Läuft auf der Grafikkarte, oder auf dem Prozessor, wenn es keine gibt. Nichts verlässt den Rechner.",
 "models.e.vulkan.note": "Ton bleibt hier",
 "models.e.api": "Remote-API",
 "models.e.api.sub": "Ein Sprachdienst deiner Wahl — OpenAI, Groq, SiliconFlow oder ein eigener Server.",
 "models.e.api.note": "Audio verlässt diesen Rechner",
 "models.now": "läuft gerade",
 "models.running": "läuft",
 "models.notloaded": "nicht geladen",
 "models.llmnone": 'keiner geladen — jeder startet bei der ersten Nutzung',
 "models.coldshort": "nicht gestartet",
 "models.ready": "bereit",
 "models.nodaemon": "der Hintergrunddienst antwortet nicht, daher ist unklar, was geladen ist",
 "models.f.edit": 'Bearbeiten',
 "models.f.close": 'Schließen',
 "models.f.url": "Adresse",
 "models.f.model": 'Modell',
 "models.f.key": 'Key',
 "models.f.key.place": "Schlüssel einfügen — er liegt nur in secrets.toml",
 "models.f.key.save": 'Speichern',
 "models.f.key.saved": "in secrets.toml gespeichert, nur für dich lesbar",
 "models.f.key.failed": 'konnte nicht gespeichert werden',
 "models.f.test": 'Testen',
 "models.f.testing": "verbinde…",
 "models.f.testok": 'geantwortet, %1 Modelle — wähle unten eines',
 "models.f.key.have": 'ein Schlüssel ist gespeichert',
 "models.f.key.fromenv": "nutzt den Schlüssel aus %1 in der Umgebung, der Vorrang vor einem hier gespeicherten hat",
 "models.f.key.fromfile": 'in secrets.toml gespeichert',
 "models.f.testfail": 'keine Antwort',
 "models.speechapi": "Remote-Dienst",
 "models.speechapi.sub": "Wohin der Ton geht: Adresse, Modell und Schlüssel.",
 "models.speechapi.cat": "Das sind die Modelle der lokalen Engine; mit der Remote-API werden sie nicht benutzt.",
 "models.k.agent": 'System-Agent',
 "models.k.agent.sub": "Der Coding-Agent, den Omarchy nutzt. Schon angemeldet, kein Schlüssel nötig; ein paar Sekunden pro Aufnahme. Deine Worte gehen an dessen Dienst.",
 "models.k.agent.argv": "(Seine Befehlszeile enthält deine Worte, die andere Programme auf diesem Rechner sehen können.)",
 "models.k.local": 'Lokales Modell',
 "models.k.local.sub": "Führt ein Modell aus der Liste unten auf diesem Rechner aus. Nichts verlässt ihn.",
 "models.k.api": 'Remote-API',
 "models.k.api.sub": "Ein Online-Modell deiner Wahl, mit Adresse und Schlüssel. Deine Worte gehen dorthin.",
 "models.k.unset": 'nicht konfiguriert',
 "models.stale": "Der Hintergrunddienst nutzt noch das Modell, mit dem er gestartet ist",
 "models.loaded": "geladen ",
 "models.configured": "konfiguriert ",
 "models.restart": "Hintergrunddienst neu starten",
 "models.ondisk": "schon auf der Platte",
 "models.downloading": "wird geladen…",
 "models.download": "Herunterladen",
 "models.use": "Verwenden",
 "models.remove": "Entfernen",
 "models.ourstore": "unserem Speicher",
 "models.outside": "Modelle außerhalb von %1 werden dort genutzt, wo sie liegen, und nie gelöscht.",
 "models.llm": "KI-ÜBERARBEITUNG",
 "models.llmsub": "Was der KI-Schritt eines Modus nutzen kann. Alle drei können gleichzeitig bereitstehen.",
 "models.nokey": "kein Key",
 "models.endpointnote": "Ein Schlüssel kommt nie in die Konfiguration: Er liegt in secrets.toml oder kommt aus einer Umgebungsvariable.",
 "models.seg.speech": 'Sprachmodell',
 "models.seg.other": 'andere Programme',
 "models.vramnote": "Beide Modelle bleiben geladen, damit das Diktieren sofort geht. Wird der Speicher knapp, fliegt zuerst das Sprachmodell raus und das Diktieren wird viel langsamer.",

 "models.vram": "VRAM · ",
 "models.sharednote": "Dieser Grafikchip teilt sich den Arbeitsspeicher, der Balken ist also der ganze Rechner. Läuft er voll, beginnt das System auszulagern und alles wird langsamer.",
 "models.shared": 'Gemeinsamer Speicher · ',
 "models.needs": "braucht",
 "dict.rules": "Regeln",
 "dict.names": "Namen",
 "dict.blurb": "gehört → gemeint. Ein Decoder-Prompt ist ein Hinweis, den das Modell "
               "ignorieren darf; hier steht die Garantie. Der längste Schlüssel wird "
               "zuerst probiert, ein darin enthaltener kürzerer greift also nie.",
 "dict.shadowed": "greift nie — verdeckt von ",
 "dict.remove": "Entfernen",
 "dict.heard": 'gehört als',
 "dict.meant": 'soll sein',
 "dict.add": 'Hinzufügen',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": 'Hyprland  Postgres  Wayland — mehrere auf einmal sind in Ordnung',
 "dict.namesblurb": "Schreibe nur die richtige Form. Namen gehen in den Decoder-Prompt, "
                    "damit das Modell sie erzeugt, und werden danach klanglich "
                    "abgeglichen, damit Homophone zurückfallen. Der Abgleich bleibt aus, "
                    "bis ein Probelauf angesehen wurde — er ist das Einzige hier, das "
                    "schon richtigen Text beschädigen kann.",
 "dict.matching": "Abgleich",
 "dict.seedonly": "nur Prompt",
 "dict.dryrun": "Probelauf",
 "dict.enable": "Abgleich aktivieren",
 "dict.prompt": "Prompt: ",
 "dict.none": "(keiner)",
 "dict.overbudget": "%1 weitere passten nicht ins Prompt-Budget",
 "set.ptt": "Halten zum Sprechen",
 "set.toggle": "drücken zum Starten, erneut zum Stoppen",
 "set.dwell.always": "immer",
 "set.dwell.changed": "bei Änderung",
 "set.dwell.never": "nie",
 "set.hotkey": "TASTENKÜRZEL",
 "set.key.type": "oder eingeben, z. B. F9",
 "set.key.rebind": 'Taste drücken',
 "set.key.press": "warte — drück sie jetzt, oder halte eine Kombination",
 "set.key": "Taste",
 "set.behaviour": "Bedienung",
 "set.key.check": 'Erneut prüfen',
 "set.key.ok": 'hört auf %1',
 "set.key.testing": 'prüfe …',
 "set.key.badname": '%1 ist keine Taste, die dieser Rechner hat — drücke stattdessen eine Taste',
 "set.key.nogroup": "Zum Lesen der Taste brauchst du die Gruppe `input`, und du bist noch nicht darin",
 "set.key.relogin": "Du bist der Gruppe `input` erst nach Beginn dieser Sitzung beigetreten — der Hintergrunddienst kann jetzt mit ihr starten, ohne Abmelden",
 "set.key.nodevice": "Keine deiner Tastaturen hat %1 — versuch eine andere Taste",
 "set.key.stopped": 'Der Hintergrunddienst läuft nicht, also hört nichts zu',
 "set.key.stale": "Der Hintergrunddienst hört noch auf %1 — starte ihn neu, damit er die neue Taste nimmt",
 "set.key.off": 'Das Tastenkürzel ist abgeschaltet',
 "set.key.fix.restart": 'Neu starten',
 "set.key.fix.regroup": 'Mit der Gruppe starten',
 "set.key.fix.group": 'Mich zu `input` hinzufügen',
 "set.hotkeynote": "Die Taste wird an ihrer Position erkannt: Ein anderes Tastaturlayout verschiebt sie nicht, und sie tut weiter, was sie vorher tat.",
 "set.preroll": "früher beginnen um",
 "set.prerollwhy": "Behält einen Moment Ton von vor dem Tastendruck, damit dein erstes Wort nicht abgeschnitten wird.",
 "set.tail": "später aufhören um",
 "set.warnbelow": "Leise-Warnung bei",
 "set.maxtake": "längste Aufnahme",
 "set.hud": "ANZEIGE",
 "set.hud.show": "anzeigen",
 "set.hud.size": "Größe",
 "set.size.xs": "klein",
 "set.size.s": "mittel",
 "set.size.m": "groß",
 "set.keepup": "Ergebnis zeigen",
 "set.hudnote": "Normalerweise blitzt das Ergebnis nur kurz auf. „Bei Änderung“ lässt es länger stehen, wenn eine Regel oder ein KI-Schritt etwas geändert hat oder etwas schiefging. Mit „nie“ erscheint das Gesagte gar nicht auf dem Bildschirm.",
 "set.notifications": "Benachrichtigungen",
 "set.on": "ein",
 "set.off": "aus",
 "set.history": "VERLAUF UND DATENSCHUTZ",
 "set.keepaudio": "Aufnahmen behalten",
 "set.takes": " Aufnahmen",
 "set.historynote": "Nur so viele der neuesten Aufnahmen bleiben, zum Abspielen; der Text jeder Aufnahme bleibt so oder so. 0 behält keine.",
 "set.clearhistory": "Gesamten Verlauf löschen",
 "set.clearnote": "Jede Aufnahme und jede noch vorhandene Audiodatei, auf einmal. Es gibt kein Zurück — einzeln löschst du per Rechtsklick im Verlauf.",
 "set.clear.confirm": "Alle Aufnahmen und alle Audiodateien löschen? Das lässt sich nicht rückgängig machen.",
 "set.clear.cancel": "Abbrechen",
 "set.clear.go": "Alles löschen",
 "set.neverleaves": "Audio verlässt diesen Rechner nie",
 "set.audioleaves": "Audio wird zu %1 hochgeladen",
 "set.privacynote.api": "Die Spracherkennung ist eine Remote-API, also verlässt der Ton jeder Aufnahme diesen Rechner. Stell im Tab Modelle wieder auf die lokale Engine, damit er hier bleibt.",
 "set.privacynote": "Die Spracherkennung läuft auf diesem Rechner. Text verlässt ihn nur, wenn die KI-Überarbeitung eines Modus die Remote-API oder den System-Agent nutzt — der Tab Modi zeigt, welche.",
 "set.editconfig": "Bearbeiten",
 "set.restart": "Hintergrunddienst neu starten",
 "set.configpath": "Jede Einstellung steht in ~/.config/omavoi/config.toml.",
 "bar.stopped": "gestoppt",
 "bar.tip.notinstalled": "Omavoi — noch nicht installiert. Zum Einrichten klicken.",
 "bar.tip.ready": "Omavoi — bereit",
 "bar.tip.recording": "Aufnahme läuft",
 "bar.tip.rightclick": "Rechtsklick startet und stoppt eine Aufnahme",
 "bar.tip.stopped": "Omavoi — der Hintergrunddienst läuft nicht. Zum Öffnen der Konsole klicken.",
 "bar.tip.transcribing": "Transkribiert…",
 "bar.tip.unfinished": "Omavoi — Einrichtung unvollständig (%1)",
 "dict.dryrun.none": "Es würde sich nichts ändern.",
 "dict.dryrun.running": "Probelauf · läuft…",
 "edit.revert": "Verwerfen",
 "edit.save": "Speichern",
 "edit.unsaved": "ungespeichert",
 "first.dbstale.age": "Deine Paketdatenbank ist %1 Tage alt.",
 "first.dbstale.age1": "Deine Paketdatenbank ist einen Tag alt.",
 "models.notready": "nicht bereit",
 "modes.speechnone": "Noch kein Erkennungsmodell heruntergeladen — der Tab Modelle hat sie.",
 "modes.pick.title": "Umschalten",
 "modes.langfixed": "Hört nur auf diese Sprache: zuverlässiger, wenn du sie sprichst, aber andere Sprachen können falsch herauskommen.",
 "modes.script": "chinesische Schriftzeichen",
 "modes.script.none": "wie erkannt",
 "modes.script.hans": "vereinfacht",
 "modes.script.hant": "traditionell",
 "modes.droppunct": "Satzzeichen am Ende entfernen",
 "modes.addwhich": "überarbeiten mit:",
 "modes.adv": "ERWEITERT",
 "modes.adv.changed": "geändert: %1",
 "modes.adv.sep": ", ",
 "modes.adv.kv": "%1: %2",
 "modes.adv.cleanup": "Bereinigung",
 "modes.speechreload": "Beim Wechsel in diesen Modus wird zuerst dieses Modell geladen, das dauert ein paar Sekunden.",
 "modes.prompthint": "Wird vor dem Zuhören gelesen — ein Hinweis, keine Garantie. Wörter aus Mein Wörterbuch kommen von selbst dazu.",
 "modes.promptinherited": "Dieser Modus hat keinen eigenen Hinweis und nutzt den von default. Speichern hier gibt ihm einen eigenen.",
 "modes.inject.hint.auto": "Tippt den Text, außer in Electron-Apps wie VS Code und Slack und in Chromium-Browsern, wo er eingefügt wird. X11-Programme werden mit xdotool getippt.",
 "modes.inject.hint.type": "Tippt immer, über wtype — außer in X11-Programmen, die mit xdotool getippt werden.",
 "modes.inject.hint.paste": "Fügt immer ein und stellt danach deine Zwischenablage wieder her — außer in X11-Programmen, die mit xdotool getippt werden.",
 "modes.sum.ai": "KI: %1",
 "modes.sum.plain": "ohne KI",
 "modes.sum.hans": "vereinfachtes Chinesisch",
 "modes.sum.hant": "traditionelles Chinesisch",
 "modes.sum.nopunct": "ohne Satzzeichen am Ende",
 "modes.sum.paste": "fügt ein",
 "modes.sum.type": "tippt",
 "setup.optional": "optional",
 "set.hotkey.sub": "Die Taste zum Sprechen. Was du sagst, landet an der Cursorposition.",
 "set.hud.sub": "Der kleine Streifen unten am Bildschirm, während du sprichst.",
 "set.notifynote": "Eine Benachrichtigung, wenn eine Aufnahme eine Warnung hat oder nichts gehört wurde.",
 "set.history.sub": "Der Verlauf bleibt auf diesem Rechner und nirgends sonst.",
 "set.tailwhy": "Nimmt nach dem Loslassen noch einen Moment weiter auf, damit dein letztes Wort nicht abgeschnitten wird.",
 "set.warnwhy": "Eine leisere Aufnahme wird im Verlauf markiert — zu leiser Ton ist der häufigste Grund für fehlende Wörter.",
 "set.maxwhy": "Die Aufnahme stoppt nach dieser Zeit von selbst.",
 "set.configfile": "Konfigurationsdatei",
 "hist.yesterday": "gestern %1",
 "hist.droppedas": "verworfen · %1",
 "hist.drop.short": "zu kurz (%1 s)",
 "hist.drop.nospeech": "keine Sprache gehört",
 "hist.drop.failed": "Erkennung fehlgeschlagen",
 "hist.w.quiet": "Die Aufnahme war leise (%1 dBFS) — der häufigste Grund für fehlende Wörter.",
 "hist.w.step": "KI-Schritt %1 (%2) hat nicht geklappt: %3 — der Text von davor wurde verwendet.",
 "hist.w.wrapped": "Der Anfang dieser Aufnahme ging verloren.",
 "hist.w.lowconf": "Die Erkennung war unsicher — manche Wörter können falsch sein oder fehlen.",
 "hist.w.silence": "Ein Teil war vielleicht Stille — prüf diesen Teil des Texts.",
 "hist.w.noxdotool": "Das ist ein X11-Fenster und xdotool ist nicht installiert, daher kam der Text dort nicht an.",
 "hist.w.script": "Die Umwandlung der chinesischen Schriftzeichen schlug fehl, der Text blieb wie erkannt.",
 "hist.w.fellback": "Für dieses Fenster wurde auf %1 gewechselt.",
 "hist.w.injectfailed": "Der Text konnte nicht ins Fenster getippt werden.",
 "hist.c.fillers": "Füllwörter entfernt",
 "hist.c.deduped": "wiederholte Sätze zusammengefasst",
 "hist.c.spacing": "Abstand zwischen CJK und Latein eingefügt",
 "hist.c.lines": "Zeilen zusammengeführt",
 "hist.c.punct": "Satzzeichen am Ende entfernt",
 "hist.c.dictionary": "aus Mein Wörterbuch korrigiert: %1",
 "hist.c.silence": "eine stille Stelle ausgelassen",
 "hist.c.hans": "in vereinfachtes Chinesisch umgewandelt",
 "hist.c.hant": "in traditionelles Chinesisch umgewandelt",
 "hist.took": "%1 s",
 "hist.details": "DETAILS",
 "hist.rtfnote": "RTF ist die Erkennungszeit im Verhältnis zur Sprechdauer; unter 1 ist schneller als Echtzeit.",
 "hist.raw": "so, wie der Hintergrunddienst es schrieb",
 "models.list.speech": "Sprachmodelle",
 "models.list.speech.sub": "Größere sind genauer, kleinere schneller. Das mit ● ist in Gebrauch.",
 "models.list.llm": "lokale KI-Modelle",
 "models.list.llm.sub": "Für die Überarbeitung mit „Lokales Modell“. Verwenden macht eines zum Standard; ein Schritt im Modus kann ein eigenes wählen.",
 "models.usedby": "genutzt von %1",
 "models.seg.llm": "KI-Modell",
 "setup.s.tools": "Aufnahme- und Tippwerkzeuge",
 "setup.s.engine": "Spracherkennung",
 "setup.s.engineapi": "Spracherkennung (Remote-API)",
 "setup.s.model": "Sprachmodell (%1)",
 "setup.s.llm": "Lokale KI-Engine (llama.cpp)",
 "setup.s.hotkey": "Taste (%1)",
 "setup.s.service": "Beim Anmelden starten",
 "setup.d.tools": "Die Systemwerkzeuge, die deine Stimme aufnehmen und den Text in Fenster tippen.",
 "setup.d.engine": "Das Programm, das auf diesem Rechner aus deiner Stimme Text macht.",
 "setup.d.model": "Die Modelldatei für die Erkennung. Sie wird einmal heruntergeladen.",
 "setup.d.llm": "Nur nötig, wenn die KI-Überarbeitung eines Modus das lokale Modell nutzt.",
 "setup.d.hotkey": "Zum Lesen der Taste musst du in der Gruppe input sein.",
 "setup.d.service": "Startet den Hintergrunddienst bei jeder Anmeldung.",
 "setup.x.missing": "Fehlt: %1",
 "setup.x.notinstalled": "%1 ist nicht installiert",
 "setup.x.nocpu": "whisper.cpp ist installiert, aber das CPU-Backend, das es ebenfalls braucht, fehlt — es würde beim Laden des Modells abbrechen",
 "setup.x.notdownloaded": "Noch nicht heruntergeladen · %1",
 "setup.x.reading": "Der Hintergrunddienst hört auf diese Taste",
 "setup.x.relogin": "In der Gruppe input, aber diese Sitzung begann vor dem Beitritt",
 "setup.x.ingroup": "In der Gruppe input",
 "setup.x.notingroup": "Noch nicht in der Gruppe input",
 "setup.x.enabled": "Eingeschaltet",
 "setup.x.notenabled": "Noch nicht eingeschaltet",
 "setup.x.nounit": "Noch nicht eingerichtet",
 "setup.x.provider": "Anbieter: %1",
 "setup.titleoptional": "Bereit zum Diktieren · %1 optional offen",
 "bar.tip.hold": "Halte %1 gedrückt und sprich",
 "bar.tip.toggle": "Drück %1 zum Starten und noch einmal zum Beenden",
 "bar.tip.release": "Lass %1 los, um zu beenden",
 "bar.tip.again": "Drück %1 noch einmal, um zu beenden",
 "word.corrects": "Korrigiert: %1",
 "word.sep": ", ",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': 'Wort hinzufügen',
 'word.edit': 'Wort bearbeiten',
 'word.intro': 'Füge Namen und Fachbegriffe hinzu, damit Omavoi sie richtig schreibt.',
 'word.spelling': 'Gewünschte Schreibweise',
 'word.examples': 'z. B. Anna Müller, Acme, JavaScript',
 'word.spaces': 'Vollständigen Namen oder Ausdruck eingeben. Leerzeichen sind erlaubt.',
 'word.wrong': 'Wird es oft falsch geschrieben?',
 'word.heard': 'Was schreibt Omavoi stattdessen?',
 'word.another': 'Weitere Schreibweise hinzufügen',
 'word.removealias': 'Entfernen',
 'word.replacehelp': 'Diese Schreibweisen werden durch „%1“ ersetzt. Nur Text hinzufügen, der immer '
                     'korrigiert werden soll.',
 'word.more': 'Weitere Optionen',
 'word.hint': 'Dieses Wort bei der Erkennung berücksichtigen',
 'word.hinthelp': 'Das Wort wird dem Sprachdienst mitgeteilt. Cloud-Dienste können es zusammen mit dem '
                  'Audio erhalten.',
 'word.case': 'Diese Groß-/Kleinschreibung verwenden',
 'word.sound': 'Ähnlich klingende Schreibweisen korrigieren',
 'word.soundhelp': 'Dabei können richtige Wörter geändert werden. Prüfe zuerst die Vorschau.',
 'word.scope': 'Anwenden in',
 'word.allmodes': 'Allen Modi',
 'word.previewhelp': 'Teste einen Satz, ohne Aufnahme oder KI-Aufruf.',
 'word.sample': 'Testsatz einfügen…',
 'word.preview': 'Korrekturen ansehen',
 'word.casewarning': 'Dies ändert auch %1. Unter Weitere Optionen abschaltbar.',
 'word.save': 'Speichern',
 'word.cancel': 'Abbrechen',
 'word.discardhelp': 'Ungespeicherte Änderungen verwerfen?',
 'word.keepediting': 'Weiter bearbeiten',
 'word.discard': 'Änderungen verwerfen',
 'word.search': 'Wörter oder Fehlschreibungen suchen…',
 'word.paused': 'Pausiert',
 'word.pause': 'Wort pausieren',
 'word.resume': 'Wieder verwenden',
 'word.delete': 'Wort und Korrekturen löschen',
 'word.undo': 'Rückgängig',
 'word.empty': 'Füge einen Namen oder ein Wort hinzu, das Omavoi oft falsch schreibt.',
 'word.noresults': 'Keine passenden Wörter.',
 'word.loading': 'Wörterbuch wird geladen…',
 'word.saved': 'Gespeichert.',
 'word.pending': 'Gespeichert, aber noch nicht aktiv. Erneut versuchen oder Sprachdienst starten.',
 'word.retry': 'Erneut versuchen',
 'word.refresh': 'Neu laden, Entwurf behalten',
 'word.failed': 'Speichern fehlgeschlagen. Dein Entwurf bleibt erhalten.',
 'word.readfailed': 'Wörterbuch konnte nicht geladen werden. Bitte erneut versuchen.',
 'word.stale': 'Das Wörterbuch wurde anderswo geändert. Lade es neu; dein Entwurf bleibt erhalten.',
 'word.duplicate': 'Dieses Wort ist schon vorhanden. Bearbeite den vorhandenen Eintrag.',
 'word.conflict': 'Diese Schreibweise überschneidet sich mit einem anderen Wort oder einer Korrektur.',
 'word.invalid': 'Gib 1–200 Zeichen ohne Zeilenumbruch ein.',
 'word.correct': 'Diese Schreibweise ist bereits richtig.',
 'word.invalidmode': 'Ein gewählter Modus existiert nicht mehr.',
 'word.missing': 'Dieses Wort wurde anderswo gelöscht. Bitte neu laden.',
 "word.capacity": "Einige Wörter passen nicht in die Erkennungshilfe. Ihre Korrekturen bleiben aktiv: %1",
 'word.legacy': 'Dein bisheriges Wörterbuch bleibt unten verfügbar. Für den neuen Editor muss der '
                'Sprachdienst aktualisiert oder die aufgeführte Konfiguration geprüft werden.',
 'word.use': 'Mein Wörterbuch verwenden',
 'word.partial': 'Teilweise aktiv'})

PACK.update({'word.deleted': 'Wort und seine Korrekturen gelöscht.',
 'word.restart': 'Starte den Sprachdienst neu, um das neue Wörterbuch zu verwenden. Die bisherigen '
                 'Wörter bleiben erhalten.'})

PACK.update({'modes.langsearch': 'Sprachen suchen…', 'modes.langempty': 'Keine passenden Sprachen', 'modes.langupgrade': 'Aktualisiere den Sprachdienst, um eine Eingabesprache auszuwählen.'})
