# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Configurar Omavoi',
 "first.blurb": "Tres preguntas y un botón. Nada se ejecuta hasta que pulsas, y cada comando se muestra primero.",
 "first.pick.language": 'Idioma de la interfaz',
 "first.pick.model": 'Modelo de voz',
 "first.reuse": "un modelo de voz que ya está en esta máquina — se usa donde está, sin descargar nada",
 "first.reuse.label": 'Usar los que hay',
 "first.m.large": "los modelos turbo no distinguen el silencio del habla; este sí",
 "first.m.turbo": "el valor por defecto; la mitad de descarga y más rápido",
 "first.m.light": "lo más ligero que aún vale la pena",
 "first.willrun": 'LO QUE SE EJECUTARÁ',
 "first.needspassword": 'pedirá tu contraseña',
 "first.install": 'Instalar',
 "first.retry": 'Reintentar',
 "first.working": '%1 …',
 "first.failed": '%1 falló — mira abajo',
 "first.cancelled": 'se canceló la petición de contraseña, así que no se instaló nada',
 "first.done": 'Listo — mantén tu tecla y habla',
 "first.dbstale": "Instalar ahora puede fallar con un 404: puede que las versiones que lista ya no estén en los espejos. Actualizar primero el sistema es el orden seguro.",
 "first.updatebtn": 'Actualizar paquetes del sistema',
 "first.pacman404": 'La base de datos de paquetes está desactualizada, así que los mirrors ya no tienen las versiones que lista. Actualiza el sistema arriba y vuelve a intentarlo.',
 "first.pick.hotkey": 'Tecla para hablar',
 "first.hotkey.other": 'otra tecla, p. ej. F9',
 "first.hotkey.note": "Se lee por debajo de tu distribución de teclado y nunca se apropia de la tecla, así que sigue haciendo lo de siempre. En muchas distribuciones no estadounidenses Alt derecha es AltGr y sirve para escribir caracteres: elige Ctrl derecha o Bloq Despl si es tu caso.",
 "first.group.needed": "Aún no estás en el grupo input, así que no se puede leer ninguna tecla. El paso de abajo te añade y arranca el servicio con el grupo desde ya, sin cerrar sesión.",
 "first.step.hotkey": 'atajo',
 "first.step.packages": 'paquetes del sistema',
 "first.step.daemon": "el servicio",
 "first.step.language": 'idioma',
 "first.step.weights": "modelo de voz",
 "first.step.use": 'seleccionar el modelo',
 "first.step.mode": 'modo por defecto',
 "first.step.service": 'unidad, atajo y entrada de menú',
 "up.title": 'ACTUALIZAR',
 "up.behind": '%1 commits nuevos en la rama del plugin',
 "up.current": 'Al día',
 "up.daemon.blind": "El servicio en segundo plano se instala aparte, así que aquí no se sabe si está al día; actualizar lo reinstala de todos modos.",
 "up.unknown": 'No se puede saber — el plugin no se instaló desde git',
 "up.nofetch": "No se pudo contactar con el remoto, así que puede que esta no sea la última versión: %1",
 "up.noupstream": "La rama del plugin no tiene upstream, así que no hay nada con que comparar",
 "up.dirty": 'El plugin instalado tiene cambios locales, así que no puede avanzar. Reinstálalo: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Actualizar',
 "up.again": 'Volver a comprobar',
 "up.done": 'Actualizado',
 "up.step.plugin": 'el plugin',
 "up.step.daemon": "el servicio",
 "up.step.shortcuts": 'unidad, atajo y entrada de menú',
 "up.step.restart": 'reiniciar',
 "nav.setup": 'Instalación',
 "setup.rootblurb": "Los pasos de arriba que necesitan la contraseña de administrador se pueden hacer aquí de una vez, con una sola petición de contraseña. Después el servicio se reinicia para reconocer lo instalado.",
 "setup.rootrun": 'Instalar esto',
 "nav.history": "Historial",
 "nav.modes": "Modos",
 "nav.models": "Modelos",
 "nav.dictionary": 'Mi diccionario',
 "nav.settings": "Ajustes",
 "state.idle": "inactivo",
 "state.recording": "grabando",
 "state.transcribing": "transcribiendo",
 "state.stopped": "servicio detenido",
 "hud.stage.decoding": 'transcribiendo',
 "hud.stage.llm": 'reescribiendo',
 "hud.stage.injecting": 'escribiendo',
 "hud.nospeech": "no se oyó voz",

 "setup.prefix": "instalación ",
 "setup.title": "Pendiente: %1",
 "setup.titledone": 'Todo está en su sitio',
 "setup.blurb": "Aquí no se ejecuta nada hasta que pulsas, y cada paso muestra antes su comando.",
 "setup.copy": "Copiar",
 "setup.run": "Ejecutar",
 "setup.recheck": "Volver a comprobar",
 "setup.hint": "o ejecuta  omavoi setup  en una terminal — los mismos pasos, el mismo orden",

 "hist.problems": "QUÉ SALIÓ MAL",
 "hist.fellthrough": "no funcionó — se usó el texto de antes",
 "hist.none": "todavía no hay tomas — mantén %1 y habla",
 "hist.yourkey": "tu tecla",
 "hist.audio": "duración",
 "hist.level": "volumen",
 "hist.decode": "reconocimiento",
 "hist.model": "modelo",
 "hist.language": "idioma",
 "hist.injected": "escrito con",
 "hist.said": "LO QUE OYÓ",
 "hist.post": "LO QUE CAMBIÓ LA LIMPIEZA",
 "hist.segments": "CONFIANZA POR SEGMENTO",
 "hist.copy": "Copiar",
 "hist.play": "Reproducir",
 "hist.delete": "Eliminar",

 "modes.wontfit": 'necesita %1 libres',
 "modes.blocked": 'no se cambió — el modelo de este modo no cabe ahora en la VRAM',
 "modes.speechmodel": "modelo de voz",
 "modes.speechglobal": "usar el predeterminado",
 "modes.speechglobalnamed": "usar el predeterminado (%1)",
 "modes.speechonly1": "Solo hay un modelo de voz descargado. La pestaña Modelos tiene otros más pequeños, para un modo en el que la velocidad importe más que la precisión.",
 "modes.newname": "nombre del nuevo modo",
 "modes.here": "en uso",
 "modes.fallback": "por defecto",
 "modes.followwin": "El modo sigue a la ventana enfocada",
 "modes.everytake": "Cada toma usa ",
 "modes.longestwins": "Gana la coincidencia más larga de abajo; si nada coincide, se "
                      "vuelve a default.",
 "modes.matchoff": "La coincidencia por ventana está desactivada, así que las listas de "
                   "abajo están configuradas pero inertes. Hay que ajustarla aplicación "
                   "por aplicación antes de que valga la pena.",
 "modes.hiddenauto": "La ventana enfocada elige el modo, así que hacer clic en uno de abajo solo lo abre.",
 "modes.following": "seguir la ventana",
 "modes.fixed": "elegir aquí",
 "modes.delete": "Eliminar modo",
 "modes.opens": "SE ABRE EN",
 "modes.notinuse": "sin uso mientras el modo esté fijo",
 "modes.nothing": "nada — a este modo solo se llega por su nombre",
 "modes.classph": "clase de ventana, p. ej. thunderbird",
 "modes.add": "Añadir",
 "modes.matchhint": "Se compara con la clase y el título de Hyprland. Gana la coincidencia "
                    "más larga.",
 "modes.s1": "VOZ",
 "modes.language": "idioma hablado",
 "modes.decoderhint": "pista de reconocimiento",
 "modes.promptph": "p. ej. Una reunión sobre Hyprland, Quickshell y PipeWire.",
 "modes.s2": "LIMPIEZA",
 "modes.rulessub": "Sin IA: al instante, y siempre igual.",
 "modes.r.hallucinations": "unir frases repetidas",
 "modes.r.fillers": "quitar muletillas",
 "modes.r.dictionary": "diccionario",
 "modes.r.names": "nombres",
 "modes.r.cjk": "espacio entre CJK y latín",
 "modes.s3": "REESCRITURA CON IA",
 "modes.llmsub": "Opcional. Cada paso añade unos segundos; si uno falla, pasa el texto que recibió.",
 "modes.step": "paso ",
 "modes.stepsuffix": "",
 "modes.remove": "Quitar",
 "modes.stepph": "Dile que edite, no que responda.",
 "modes.addstep": "+ añadir un paso de reescritura",
 "modes.weights": "Modelo",
 "modes.inherit": "usar el predeterminado (%1)",
 "modes.nollm": "no hay ningún LLM configurado — mira la pestaña Modelos",
 "modes.inject.auto": "auto",
 "modes.inject.type": "teclear",
 "modes.inject.clipboard": "pegar",
 "modes.langauto": "auto",
 "modes.s4": "escritura",

 "models.speech": "RECONOCIMIENTO DE VOZ",
 "models.speechsub": "Convierte lo que dices en texto. De una sola forma a la vez.",
 "models.e.vulkan": "En este equipo",
 "models.e.vulkan.sub": "Funciona en tu tarjeta gráfica, o en el procesador si no hay. Nada sale del equipo.",
 "models.e.vulkan.note": "el audio se queda aquí",
 "models.e.api": "API remota",
 "models.e.api.sub": "Un servicio de voz que tú eliges: OpenAI, Groq, SiliconFlow o tu propio servidor.",
 "models.e.api.note": "el audio sale de esta máquina",
 "models.now": "en marcha ahora",
 "models.running": "en ejecución",
 "models.notloaded": "sin cargar",
 "models.llmnone": 'ninguno cargado — cada uno arranca en su primer uso',
 "models.coldshort": 'en frío',
 "models.ready": "listo",
 "models.nodaemon": "el servicio en segundo plano no responde, así que no se sabe qué está cargado",
 "models.f.edit": 'Editar',
 "models.f.close": 'Cerrar',
 "models.f.url": "dirección",
 "models.f.model": 'Modelo',
 "models.f.key": 'Clave',
 "models.f.key.place": "pega la clave; solo se guarda en secrets.toml",
 "models.f.key.save": 'Guardar',
 "models.f.key.saved": "guardada en secrets.toml, solo tú puedes leerla",
 "models.f.key.failed": 'no se pudo guardar',
 "models.f.test": 'Probar',
 "models.f.testing": "conectando…",
 "models.f.testok": 'respondió, %1 modelos — elige uno abajo',
 "models.f.key.have": 'hay una clave guardada',
 "models.f.key.fromenv": "usando la clave de %1 en el entorno, que tiene prioridad sobre la guardada aquí",
 "models.f.key.fromfile": 'guardada en secrets.toml',
 "models.f.testfail": 'no respondió',
 "models.speechapi": "servicio remoto",
 "models.speechapi.sub": "Adónde va el audio: dirección, modelo y clave.",
 "models.speechapi.cat": "Estos son los modelos del motor local; con la API remota elegida no se usan.",
 "models.k.agent": 'Agente del sistema',
 "models.k.agent.sub": "El agente de programación que usa Omarchy. Ya tiene sesión, no necesita clave; tarda unos segundos cada vez. Tus palabras van a su servicio.",
 "models.k.agent.argv": "(Su línea de comandos lleva tus palabras, que otros programas de este equipo pueden ver.)",
 "models.k.local": 'Modelo local',
 "models.k.local.sub": "Ejecuta en este equipo un modelo de la lista de abajo. Nada sale del equipo.",
 "models.k.api": 'API remota',
 "models.k.api.sub": "Un modelo en línea que tú eliges, con su dirección y una clave. Tus palabras van allí.",
 "models.k.unset": 'sin configurar',
 "models.stale": "El servicio sigue usando el modelo con el que arrancó",
 "models.loaded": "cargado ",
 "models.configured": "configurado ",
 "models.restart": "Reiniciar el servicio",
 "models.ondisk": "ya está en disco",
 "models.downloading": "descargando…",
 "models.download": "Descargar",
 "models.use": "Usar",
 "models.remove": "Eliminar",
 "models.ourstore": "nuestro almacén",
 "models.outside": "Los modelos encontrados fuera de %1 se usan donde están y nunca se borran.",
 "models.llm": "REESCRITURA CON IA",
 "models.llmsub": "Lo que puede usar el paso de IA de un modo. Los tres pueden estar listos a la vez.",
 "models.nokey": "sin clave",
 "models.endpointnote": "La clave nunca se escribe en la configuración: se guarda en secrets.toml o llega por una variable de entorno.",
 "models.seg.speech": 'modelo de voz',
 "models.seg.other": 'otros programas',
 "models.vramnote": "Los dos modelos se quedan cargados para que el dictado sea inmediato. Si falta memoria, primero sale el modelo de voz y el dictado se vuelve mucho más lento.",

 "models.vram": "VRAM · ",
 "models.sharednote": "Este chip gráfico comparte la memoria del equipo, así que la barra es todo el equipo. Si se llena, el sistema empieza a usar swap y todo va más lento.",
 "models.shared": 'Memoria compartida · ',
 "models.needs": "necesita",
 "dict.rules": "reglas",
 "dict.names": "nombres",
 "dict.blurb": "oído → querido. Un prompt de decodificador es una pista que el modelo "
               "puede ignorar; esto es la garantía. Se prueba primero la clave más larga, "
               "así que una más corta contenida en ella nunca se dispara.",
 "dict.shadowed": "nunca se dispara — la tapa ",
 "dict.remove": "Quitar",
 "dict.heard": 'se oyó como',
 "dict.meant": 'debería ser',
 "dict.add": 'Añadir',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": 'Hyprland  Postgres  Wayland — varios a la vez vale',
 "dict.namesblurb": "Escribe solo la forma correcta. Los nombres se meten en el prompt del "
                    "decodificador para que el modelo los produzca, y luego se emparejan "
                    "por sonido para que los homófonos vuelvan al sitio. El emparejamiento "
                    "sigue desactivado hasta que se haya mirado una prueba en seco — es lo "
                    "único aquí que puede estropear texto que ya estaba bien.",
 "dict.matching": "emparejando",
 "dict.seedonly": "solo prompt",
 "dict.dryrun": "Prueba en seco",
 "dict.enable": "Activar emparejamiento",
 "dict.prompt": "prompt: ",
 "dict.none": "(ninguno)",
 "dict.overbudget": "%1 más no cupieron en el presupuesto del prompt",
 "set.ptt": "mantener para hablar",
 "set.toggle": "pulsar para empezar y para parar",
 "set.dwell.always": "siempre",
 "set.dwell.changed": "si cambió",
 "set.dwell.never": "nunca",
 "set.hotkey": "ATAJO",
 "set.key.type": "o escríbela, p. ej. F9",
 "set.key.rebind": 'Pulsa una tecla',
 "set.key.press": "esperando — púlsala ahora, o mantén una combinación",
 "set.key": "tecla",
 "set.behaviour": "cómo se usa",
 "set.key.check": 'Comprobar de nuevo',
 "set.key.ok": 'escuchando en %1',
 "set.key.testing": 'comprobando…',
 "set.key.badname": '%1 no es una tecla que tenga esta máquina — pulsa una tecla en su lugar',
 "set.key.nogroup": "Para leer la tecla hace falta el grupo `input`, y aún no estás en él",
 "set.key.relogin": "Te uniste al grupo `input` después de empezar esta sesión — el servicio en segundo plano puede arrancar ya con él, sin cerrar sesión",
 "set.key.nodevice": "Ninguno de tus teclados tiene %1 — prueba otra tecla",
 "set.key.stopped": 'El servicio en segundo plano no está corriendo, así que nada escucha',
 "set.key.stale": "El servicio en segundo plano sigue escuchando en %1 — reinícialo para usar la nueva tecla",
 "set.key.off": 'El atajo está desactivado',
 "set.key.fix.restart": 'Reiniciarlo',
 "set.key.fix.regroup": 'Arrancarlo con el grupo',
 "set.key.fix.group": 'Añadirme a `input`',
 "set.hotkeynote": "La tecla se reconoce por su posición, así que cambiar la distribución del teclado no la mueve, y sigue haciendo lo que hacía.",
 "set.preroll": "empezar antes",
 "set.prerollwhy": "Guarda un instante de sonido de antes de pulsar la tecla, para que tu primera palabra no se corte.",
 "set.tail": "parar después",
 "set.warnbelow": "aviso de volumen bajo",
 "set.maxtake": "toma más larga",
 "set.hud": "EN PANTALLA",
 "set.hud.show": "mostrar",
 "set.hud.size": "tamaño",
 "set.size.xs": "pequeño",
 "set.size.s": "mediano",
 "set.size.m": "grande",
 "set.keepup": "mostrar el resultado",
 "set.hudnote": "Normalmente el resultado solo aparece un instante. «Si cambió» lo deja un poco más cuando una regla o un paso de IA cambió lo que dijiste, o algo falló. Con «nunca», lo que dices no se muestra en pantalla.",
 "set.notifications": "notificaciones",
 "set.on": "activado",
 "set.off": "desactivado",
 "set.history": "HISTORIAL Y PRIVACIDAD",
 "set.keepaudio": "conservar grabaciones",
 "set.takes": " tomas",
 "set.historynote": "Solo se conservan estas grabaciones más recientes, para reproducirlas; el texto de cada toma se queda igualmente. 0 no guarda ninguna.",
 "set.clearhistory": "Borrar todo el historial",
 "set.clearnote": "Todas las tomas, y todas las grabaciones que sigan en el disco, de una vez. No se puede deshacer — de una en una es un clic derecho en la pestaña de historial.",
 "set.clear.confirm": "¿Eliminar todas las tomas y todas las grabaciones? Esto no se puede deshacer.",
 "set.clear.cancel": "Cancelar",
 "set.clear.go": "Eliminar todo",
 "set.neverleaves": "El audio nunca sale de esta máquina",
 "set.audioleaves": "El audio se sube a %1",
 "set.privacynote.api": "El motor de voz es una API remota, así que el audio de cada toma sale de este equipo. Vuelve al motor local en la pestaña Modelos para que se quede aquí.",
 "set.privacynote": "El reconocimiento de voz se hace en este equipo. El texto solo sale cuando la reescritura con IA de un modo usa la API remota o el agente del sistema; la pestaña Modos muestra cuáles.",
 "set.editconfig": "Editar",
 "set.restart": "Reiniciar el servicio",
 "set.configpath": "Todos los ajustes están en ~/.config/omavoi/config.toml.",
 "bar.stopped": "detenido",
 "bar.tip.notinstalled": "Omavoi — aún sin instalar. Pulsa para configurarlo.",
 "bar.tip.ready": "Omavoi — listo",
 "bar.tip.recording": "Grabando",
 "bar.tip.rightclick": "Clic derecho para empezar o parar una toma",
 "bar.tip.stopped": "Omavoi — el servicio en segundo plano no está en marcha. Pulsa para abrir la consola.",
 "bar.tip.transcribing": "Transcribiendo…",
 "bar.tip.unfinished": "Omavoi — instalación sin terminar (%1)",
 "dict.dryrun.none": "No cambiaría nada.",
 "dict.dryrun.running": "Prueba en seco · en marcha…",
 "edit.revert": "Revertir",
 "edit.save": "Guardar",
 "edit.unsaved": "sin guardar",
 "first.dbstale.age": "Tu base de datos de paquetes tiene %1 días.",
 "first.dbstale.age1": "Tu base de datos de paquetes tiene un día.",
 "models.notready": "no listo",
 "modes.speechnone": "Aún no hay ningún modelo de voz descargado; la pestaña Modelos los tiene.",
 "modes.pick.title": "cambio de modo",
 "modes.langfixed": "Solo escucha este idioma: más fiable si es el que hablas, pero otros idiomas pueden salir mal.",
 "modes.script": "caracteres chinos",
 "modes.script.none": "tal como se reconocen",
 "modes.script.hans": "simplificados",
 "modes.script.hant": "tradicionales",
 "modes.droppunct": "quitar la puntuación final",
 "modes.addwhich": "reescribir con:",
 "modes.adv": "AVANZADO",
 "modes.adv.changed": "cambiado: %1",
 "modes.adv.sep": ", ",
 "modes.adv.kv": "%1: %2",
 "modes.adv.cleanup": "limpieza",
 "modes.speechreload": "Al cambiar a este modo primero se carga ese modelo, lo que tarda unos segundos.",
 "modes.prompthint": "El reconocedor lo lee antes de escuchar: una ayuda, no una garantía. Las palabras de Mi diccionario se añaden solas.",
 "modes.promptinherited": "Este modo no tiene pista propia y usa la de default. Guardar aquí le da una.",
 "modes.inject.hint.auto": "Escribe el texto, salvo en apps Electron como VS Code y Slack y en navegadores Chromium, donde lo pega. Las apps X11 se escriben con xdotool.",
 "modes.inject.hint.type": "Siempre escribe, mediante wtype, salvo en apps X11, que se escriben con xdotool.",
 "modes.inject.hint.paste": "Siempre pega y luego restaura tu portapapeles, salvo en apps X11, que se escriben con xdotool.",
 "modes.sum.ai": "IA: %1",
 "modes.sum.plain": "sin IA",
 "modes.sum.hans": "chino simplificado",
 "modes.sum.hant": "chino tradicional",
 "modes.sum.nopunct": "sin puntuación final",
 "modes.sum.paste": "pega",
 "modes.sum.type": "escribe",
 "setup.optional": "opcional",
 "set.hotkey.sub": "La tecla con la que hablas. Lo que digas aparece donde está el cursor.",
 "set.hud.sub": "La pequeña barra en la parte inferior de la pantalla mientras hablas.",
 "set.notifynote": "Una notificación cuando una toma tiene un aviso o no se oyó nada.",
 "set.history.sub": "El historial se guarda en este equipo y en ningún otro sitio.",
 "set.tailwhy": "Sigue grabando un instante después de soltar, para que tu última palabra no se corte.",
 "set.warnwhy": "Una toma más baja que esto se marca en el historial: el volumen bajo es la causa habitual de palabras perdidas.",
 "set.maxwhy": "La grabación se detiene sola pasado este tiempo.",
 "set.configfile": "archivo de configuración",
 "hist.yesterday": "ayer %1",
 "hist.droppedas": "descartada · %1",
 "hist.drop.short": "demasiado corta (%1 s)",
 "hist.drop.nospeech": "no se oyó voz",
 "hist.drop.failed": "falló el reconocimiento",
 "hist.w.quiet": "La grabación sonaba baja (%1 dBFS), la causa habitual de palabras perdidas.",
 "hist.w.step": "El paso de IA %1 (%2) no funcionó: %3 — se usó el texto de antes.",
 "hist.w.wrapped": "Se perdió el principio de esta toma.",
 "hist.w.lowconf": "El reconocimiento no estaba seguro: puede haber palabras erróneas o perdidas.",
 "hist.w.silence": "Una parte pudo ser silencio: revisa esa parte del texto.",
 "hist.w.noxdotool": "Es una ventana X11 y xdotool no está instalado, así que el texto no pudo llegar.",
 "hist.w.script": "Falló la conversión de caracteres chinos; el texto quedó tal como se reconoció.",
 "hist.w.fellback": "Para esta ventana se cambió a %1.",
 "hist.w.injectfailed": "No se pudo escribir el texto en la ventana.",
 "hist.c.fillers": "se quitaron muletillas",
 "hist.c.deduped": "se unieron frases repetidas",
 "hist.c.spacing": "se separaron CJK y latín",
 "hist.c.lines": "se unieron las líneas",
 "hist.c.punct": "se quitó la puntuación final",
 "hist.c.dictionary": "corregido con Mi diccionario: %1",
 "hist.c.silence": "se omitió un tramo de silencio",
 "hist.c.hans": "convertido a chino simplificado",
 "hist.c.hant": "convertido a chino tradicional",
 "hist.took": "tardó %1 s",
 "hist.details": "DETALLES",
 "hist.rtfnote": "RTF es el tiempo de reconocimiento frente a lo que hablaste; menos de 1 es más rápido que en tiempo real.",
 "hist.raw": "tal como lo escribió el servicio",
 "models.list.speech": "modelos de voz",
 "models.list.speech.sub": "Los grandes son más precisos y los pequeños más rápidos. El marcado con ● es el que está en uso.",
 "models.list.llm": "modelos de IA locales",
 "models.list.llm.sub": "Para reescribir con «Modelo local». Usar lo deja por defecto; el paso de un modo puede elegir otro.",
 "models.usedby": "lo usa %1",
 "models.seg.llm": "modelo de IA",
 "setup.s.tools": "Herramientas de grabación y escritura",
 "setup.s.engine": "Motor de voz",
 "setup.s.engineapi": "Motor de voz (API remota)",
 "setup.s.model": "Modelo de voz (%1)",
 "setup.s.llm": "Motor de IA local (llama.cpp)",
 "setup.s.hotkey": "Tecla (%1)",
 "setup.s.service": "Iniciar al entrar",
 "setup.d.tools": "Las herramientas del sistema que graban tu voz y escriben el texto en las ventanas.",
 "setup.d.engine": "El programa que convierte tu voz en texto en este equipo.",
 "setup.d.model": "El archivo de modelo que usa el reconocimiento. Se descarga una sola vez.",
 "setup.d.llm": "Solo hace falta si la reescritura con IA de un modo usa el modelo local.",
 "setup.d.hotkey": "Para leer la tecla tienes que estar en el grupo input.",
 "setup.d.service": "Inicia el servicio en segundo plano cada vez que entras.",
 "setup.x.missing": "Falta: %1",
 "setup.x.notinstalled": "%1 no está instalado",
 "setup.x.nocpu": "whisper.cpp está instalado, pero falta el backend de CPU que también necesita: se detendría al cargar el modelo",
 "setup.x.notdownloaded": "Aún no descargado · %1",
 "setup.x.reading": "El servicio en segundo plano está escuchando esta tecla",
 "setup.x.relogin": "En el grupo input, pero esta sesión empezó antes de unirte",
 "setup.x.ingroup": "En el grupo input",
 "setup.x.notingroup": "Aún no en el grupo input",
 "setup.x.enabled": "Activado",
 "setup.x.notenabled": "Aún no activado",
 "setup.x.nounit": "Aún no configurado",
 "setup.x.provider": "Proveedor: %1",
 "setup.titleoptional": "Listo para dictar · opcionales pendientes: %1",
 "bar.tip.hold": "Mantén pulsada %1 y habla",
 "bar.tip.toggle": "Pulsa %1 para empezar y otra vez para terminar",
 "bar.tip.release": "Suelta %1 para terminar",
 "bar.tip.again": "Pulsa %1 otra vez para terminar",
 "word.corrects": "Corrige: %1",
 "word.sep": ", ",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': 'Añadir palabra',
 'word.edit': 'Editar palabra',
 'word.intro': 'Añade nombres y términos especializados para ayudar a Omavoi a escribirlos bien.',
 'word.spelling': 'Cómo debe escribirse',
 'word.examples': 'Ej.: Ana García, Acme, JavaScript',
 'word.spaces': 'Escribe el nombre o la frase completa. Se permiten espacios.',
 'word.wrong': '¿Sigue escribiéndolo mal?',
 'word.heard': '¿Qué escribe Omavoi en su lugar?',
 'word.another': 'Añadir otra variante',
 'word.removealias': 'Quitar',
 'word.replacehelp': 'Estas variantes se cambiarán por «%1». Añade solo texto que quieras corregir '
                     'siempre.',
 'word.more': 'Más opciones',
 'word.hint': 'Ayudar a reconocer esta palabra',
 'word.hinthelp': 'Se proporciona esta palabra al servicio de voz. Los servicios en la nube pueden '
                  'recibirla junto al audio.',
 'word.case': 'Usar estas mayúsculas y minúsculas',
 'word.sound': 'Corregir palabras que suenan parecido',
 'word.soundhelp': 'Puede cambiar palabras correctas. Revisa primero el resultado.',
 'word.scope': 'Aplicar en',
 'word.allmodes': 'Todos los modos',
 'word.previewhelp': 'Prueba una frase sin grabar ni llamar a un servicio de IA.',
 'word.sample': 'Pega una frase para probar…',
 'word.preview': 'Ver correcciones',
 'word.casewarning': 'Esto también cambia %1. Puedes desactivarlo en Más opciones.',
 'word.save': 'Guardar',
 'word.cancel': 'Cancelar',
 'word.discardhelp': '¿Descartar los cambios sin guardar?',
 'word.keepediting': 'Seguir editando',
 'word.discard': 'Descartar cambios',
 'word.search': 'Buscar palabras o errores…',
 'word.paused': 'En pausa',
 'word.pause': 'Pausar palabra',
 'word.resume': 'Volver a usar',
 'word.delete': 'Eliminar palabra y correcciones',
 'word.undo': 'Deshacer',
 'word.empty': 'Añade un nombre o palabra que Omavoi suela escribir mal.',
 'word.noresults': 'No se encontraron palabras.',
 'word.loading': 'Cargando el diccionario…',
 'word.saved': 'Guardado.',
 'word.pending': 'Guardado, pero aún no activo. Reintenta o inicia el servicio de voz.',
 'word.retry': 'Reintentar',
 'word.refresh': 'Recargar y conservar borrador',
 'word.failed': 'No se pudo guardar. Tus cambios se conservan.',
 'word.readfailed': 'No se pudo leer el diccionario. Reintenta.',
 'word.stale': 'El diccionario cambió en otro lugar. Recárgalo; se conserva tu borrador.',
 'word.duplicate': 'Esta palabra ya existe. Edita la entrada existente.',
 'word.conflict': 'Esta forma entra en conflicto con otra palabra o corrección.',
 'word.invalid': 'Escribe entre 1 y 200 caracteres sin saltos de línea.',
 'word.correct': 'Esta forma ya es correcta.',
 'word.invalidmode': 'El modo elegido ya no existe.',
 'word.missing': 'Esta palabra se eliminó en otro lugar. Recarga el diccionario.',
 "word.capacity": "Algunas palabras no se usaron como pistas. Sus correcciones siguen activas: %1",
 'word.legacy': 'Tu diccionario sigue disponible abajo. Actualiza el servicio de voz o revisa los '
                'ajustes indicados para usar el nuevo editor.',
 'word.use': 'Usar mi diccionario',
 'word.partial': 'Parcialmente activo'})

PACK.update({'word.deleted': 'Palabra y correcciones eliminadas.',
 'word.restart': 'Reinicia el servicio de voz para usar el nuevo diccionario. Las palabras '
                 'existentes no han cambiado.'})

PACK.update({'modes.langsearch': 'Buscar idiomas…', 'modes.langempty': 'No hay idiomas coincidentes', 'modes.langupgrade': 'Actualiza el servicio de voz para elegir un idioma de entrada.'})
