# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Configurer Omavoi',
 "first.blurb": "Trois questions, puis un bouton. Rien ne s'exécute avant que tu ne presses, et chaque commande est montrée d'abord.",
 "first.pick.language": "Langue de l'interface",
 "first.pick.model": 'Modèle de parole',
 "first.reuse": "un modèle vocal déjà présent sur cette machine — utilisé là où il est, rien à télécharger",
 "first.reuse.label": "Utiliser l'existant",
 "first.m.large": "les modèles turbo ne distinguent pas le silence de la parole ; celui-ci le fait",
 "first.m.turbo": "le choix par défaut ; moitié du téléchargement, et plus rapide",
 "first.m.light": "le plus léger qui vaille encore la peine",
 "first.willrun": "CE QUI VA S'EXÉCUTER",
 "first.needspassword": 'demande ton mot de passe',
 "first.install": 'Installer',
 "first.retry": 'Réessayer',
 "first.working": '%1 …',
 "first.failed": '%1 a échoué — voir ci-dessous',
 "first.cancelled": "la demande de mot de passe a été annulée, rien n'a été installé",
 "first.done": 'Prêt — maintiens ta touche et parle',
 "first.dbstale": "Installer quoi que ce soit échoue maintenant en 404 : les versions qu'elle indique ne sont plus sur les miroirs. Arch demande de toute façon une mise à jour du système avant d'ajouter des paquets.",
 "first.updatebtn": 'Mettre à jour les paquets système',
 "first.pacman404": "La base de paquets est périmée, les miroirs n'ont plus les versions qu'elle indique. Mets le système à jour ci-dessus, puis réessaie.",
 "first.pick.hotkey": 'Touche pour parler',
 "first.hotkey.other": 'une autre touche, p. ex. F9',
 "first.hotkey.note": "Lue sous votre disposition de clavier et jamais accaparée : la touche continue de faire ce qu'elle fait d'habitude. Sur beaucoup de dispositions hors États-Unis, Alt droite est AltGr et sert à taper des caractères — choisissez Ctrl droite ou Arrêt défil si c'est votre cas.",
 "first.group.needed": "Tu n'es pas encore dans le groupe input, donc aucune touche ne peut être lue. L'étape ci-dessous s'en charge, et le démon est lancé de façon à obtenir le groupe immédiatement — pas besoin de te déconnecter.",
 "first.step.hotkey": 'raccourci',
 "first.step.packages": 'paquets système',
 "first.step.daemon": 'le démon',
 "first.step.language": 'langue',
 "first.step.weights": "modèle vocal",
 "first.step.use": 'sélectionner le modèle',
 "first.step.mode": 'mode par défaut',
 "first.step.service": 'unité, raccourci et entrée de menu',
 "up.title": 'MISE À JOUR',
 "up.behind": '%1 nouveaux commits sur la branche du plugin',
 "up.current": 'À jour',
 "up.daemon.blind": "Le service d'arrière-plan est installé à part, on ne peut donc pas savoir ici s'il est à jour ; la mise à jour le réinstalle de toute façon.",
 "up.unknown": "Impossible de savoir — le plugin n'a pas été installé depuis git",
 "up.nofetch": "Le dépôt distant est injoignable, ceci n'est donc peut-être pas la dernière version : %1",
 "up.noupstream": "La branche du plugin n'a pas d'upstream, il n'y a donc rien à comparer",
 "up.dirty": 'Le plugin installé a des modifications locales, il ne peut pas avancer. Réinstalle-le : omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Mettre à jour',
 "up.again": 'Revérifier',
 "up.done": 'Mis à jour',
 "up.step.plugin": 'le plugin',
 "up.step.daemon": "le service",
 "up.step.shortcuts": 'unité, raccourci et entrée de menu',
 "up.step.restart": 'redémarrer',
 "nav.setup": 'Installation',
 "setup.rootblurb": "Les étapes ci-dessus qui demandent root peuvent être faites ici, en une seule demande de mot de passe — polkit traite pacman comme auth_admin, donc deux appels signifient deux demandes. Le démon est ensuite redémarré : il retient l'absence d'un moteur pour toute la durée du processus, installer le binaire seul le laisserait continuer à dire qu'il manque.",
 "setup.rootrun": 'Tout installer',
 "nav.history": "Historique",
 "nav.modes": "Modes",
 "nav.models": "Modèles",
 "nav.dictionary": 'Mon dictionnaire',
 "nav.settings": "Réglages",
 "state.idle": "au repos",
 "state.recording": "enregistrement",
 "state.transcribing": "transcription",
 "state.stopped": "démon arrêté",
 "hud.stage.decoding": 'transcription',
 "hud.stage.llm": 'réécriture',
 "hud.stage.injecting": 'saisie',
 "hud.nospeech": 'aucune parole',

 "setup.prefix": "installation ",
 "setup.title": 'Reste à installer : %1',
 "setup.titledone": 'Tout est en place',
 "setup.blurb": "Rien ne s'exécute ici avant que tu ne l'actionnes, et chaque étape "
                "montre d'abord la commande exacte. Omarchy n'exécute délibérément "
                "rien depuis un dossier de plugin, donc cet écran demande.",
 "setup.copy": "Copier",
 "setup.run": "Exécuter",
 "setup.recheck": "Revérifier",
 "setup.hint": "ou lance  omavoi setup  dans un terminal — mêmes étapes, même ordre",

 "hist.problems": "CE QUI N'A PAS MARCHÉ",
 "hist.fellthrough": "n'a pas marché — le texte d'avant a été utilisé",
 "hist.none": "aucune prise pour l'instant — maintiens %1 et parle",
 "hist.yourkey": "ta touche",
 "hist.audio": "durée",
 "hist.level": "volume",
 "hist.decode": "reconnaissance",
 "hist.model": "modèle",
 "hist.language": "langue",
 "hist.injected": "saisi avec",
 "hist.said": "CE QU'IL A ENTENDU",
 "hist.post": "CE QUE LE NETTOYAGE A CHANGÉ",
 "hist.segments": "CONFIANCE PAR SEGMENT",
 "hist.copy": "Copier",
 "hist.play": "Écouter",
 "hist.delete": "Supprimer",

 "modes.wontfit": 'demande %1 de libre',
 "modes.blocked": 'non basculé — le modèle de ce mode ne tient pas dans la VRAM actuellement',
 "modes.speechmodel": "modèle vocal",
 "modes.speechglobal": "utiliser celui par défaut",
 "modes.speechglobalnamed": "utiliser celui par défaut (%1)",
 "modes.speechonly1": "Un seul modèle vocal est téléchargé. L'onglet Modèles en propose de plus petits, pour un mode où la vitesse compte plus que la précision.",
 "modes.newname": "nom du nouveau mode",
 "modes.here": "utilisé",
 "modes.fallback": "par défaut",
 "modes.followwin": "Le mode suit la fenêtre active",
 "modes.everytake": "Chaque prise utilise ",
 "modes.longestwins": "La correspondance la plus longue ci-dessous gagne ; sans "
                      "correspondance, retour à default.",
 "modes.matchoff": "La correspondance de fenêtre est désactivée : les listes ci-dessous "
                   "sont configurées mais inertes. Il faut l'ajuster application par "
                   "application avant qu'elle ne soit rentable.",
 "modes.hiddenauto": "La fenêtre active choisit le mode : cliquer sur un mode ci-dessous ne fait que l'ouvrir.",
 "modes.following": "suivre la fenêtre",
 "modes.fixed": "choisir ici",
 "modes.delete": "Supprimer le mode",
 "modes.opens": "S'OUVRE SUR",
 "modes.notinuse": "inutilisé tant que le mode est fixe",
 "modes.nothing": "rien — ce mode ne s'atteint que par son nom",
 "modes.classph": "classe de fenêtre, p. ex. thunderbird",
 "modes.add": "Ajouter",
 "modes.matchhint": "Comparé à la classe et au titre Hyprland. La correspondance la plus "
                    "longue gagne.",
 "modes.s1": "VOIX",
 "modes.language": "langue parlée",
 "modes.decoderhint": "indice de reconnaissance",
 "modes.promptph": "p. ex. Une réunion sur Hyprland, Quickshell et PipeWire.",
 "modes.s2": "NETTOYAGE",
 "modes.rulessub": "Sans IA : instantané, et identique à chaque fois.",
 "modes.r.hallucinations": "fusionner les phrases répétées",
 "modes.r.fillers": "retirer les mots de remplissage",
 "modes.r.dictionary": "dictionnaire",
 "modes.r.names": "noms",
 "modes.r.cjk": "espace entre CJK et latin",
 "modes.s3": "RÉÉCRITURE IA",
 "modes.llmsub": "Facultatif. Chaque étape ajoute quelques secondes ; une étape qui échoue transmet le texte qu'elle a reçu.",
 "modes.step": "étape ",
 "modes.stepsuffix": "",
 "modes.remove": "Retirer",
 "modes.stepph": "Dis-lui de corriger, pas de répondre.",
 "modes.addstep": "+ ajouter une étape de réécriture",
 "modes.weights": "Modèle",
 "modes.inherit": "utiliser celui par défaut (%1)",
 "modes.nollm": "aucun LLM configuré — voir l'onglet Modèles",
 "modes.inject.auto": "auto",
 "modes.inject.type": "taper",
 "modes.inject.clipboard": "coller",
 "modes.langauto": "auto",
 "modes.s4": "saisie",

 "models.speech": "PAROLE",
 "models.speechsub": "audio → texte · un seul tourne",
 "models.e.vulkan": "Local · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · poids ggml · NVIDIA, AMD et Intel indifféremment",
 "models.e.vulkan.note": "~10 Mo de paquets",
 "models.e.api": "API distante",
 "models.e.api.sub": "compatible OpenAI · OpenAI, Groq, SiliconFlow, un serveur local",
 "models.e.api.note": "l'audio quitte cette machine",
 "models.llmcathint": 'nommé par une étape de mode, pas un basculement global',
 "models.now": "EN COURS",
 "models.running": "en cours",
 "models.notloaded": "non chargé",
 "models.llmnone": "aucun chargé — chacun démarre à sa première utilisation",
 "models.coldshort": 'à froid',
 "models.ready": "prêt",
 "models.nodaemon": "démon injoignable — impossible de savoir ce qui est chargé",
 "models.f.edit": 'Modifier',
 "models.f.close": 'Fermer',
 "models.f.url": 'URL',
 "models.f.model": 'Modèle',
 "models.f.key": 'Clé',
 "models.f.key.place": 'colle-la ici — elle va dans secrets.toml, jamais dans la configuration',
 "models.f.key.save": 'Enregistrer',
 "models.f.key.saved": 'enregistrée dans secrets.toml, 0600',
 "models.f.key.failed": "n'a pas pu être enregistrée",
 "models.f.test": 'Tester',
 "models.f.testing": "on demande ses modèles au point d'accès…",
 "models.f.testok": 'a répondu, %1 modèles — choisis-en un ci-dessous',
 "models.f.key.have": 'une clé est enregistrée',
 "models.f.key.fromenv": "utilisée depuis %1 dans l'environnement — elle l'emporte "
                          "sur le fichier, donc une valeur périmée bat la clé que "
                          "tu viens d'enregistrer",
 "models.f.key.fromfile": 'enregistrée dans secrets.toml',
 "models.f.testfail": "pas de réponse",
 "models.speechapi": 'POINT DE TERMINAISON VOCAL DISTANT',
 "models.speechapi.sub": "L'audio quitte cette machine. À sélectionner ci-dessus sous « API distante ».",
 "models.speechapi.cat": "La liste ci-dessous est celle des modèles vocaux du moteur local ; elle ne sert pas quand le moteur distant est sélectionné.",
 "models.k.agent": 'Agent système',
 "models.k.agent.sub": "l'agent de code configuré dans Omarchy — déjà connecté, sans clé, quelques secondes de démarrage par prise. Vos mots partent là où cet agent est connecté.",
 "models.k.agent.argv": "· l'appel de cet agent place la transcription dans la ligne de commande, que /proc montre à tout processus de cet utilisateur",
 "models.k.local": 'Modèle local',
 "models.k.local.sub": "llama.cpp, lancé et géré ici ; une étape peut nommer son propre modèle dans le catalogue ci-dessous",
 "models.k.api": 'API distante',
 "models.k.api.sub": "compatible OpenAI — renseigner base_url et une clé. Vos mots partent vers ce point d'accès.",
 "models.k.unset": 'non configuré',
 "models.stale": "Le démon tourne toujours avec ce qu'il a chargé au démarrage",
 "models.loaded": "chargé ",
 "models.configured": "configuré ",
 "models.restart": "Redémarrer le démon",
 "models.list": "MODÈLES · ",
 "models.formathint": "le format que ce moteur exécute",
 "models.ondisk": "déjà sur le disque",
 "models.downloading": "téléchargement…",
 "models.download": "Télécharger",
 "models.use": "Utiliser",
 "models.remove": "Supprimer",
 "models.ourstore": "notre dépôt",
 "models.outside": "Les modèles trouvés hors de %1 sont utilisés là où ils sont et jamais supprimés.",
 "models.llm": "LLM",
 "models.llmsub": "texte → texte · autant qu'on veut, appelés par leur nom depuis les modes",
 "models.nokey": "pas de clé",
 "models.endpointnote": "Les points d'accès vivent sous [llm.<name>] — omavoi config edit. "
                        "Une clé ne va jamais dans la configuration : définis sa variable "
                        "d'environnement, ou mets-la dans secrets.toml.",
 "models.seg.speech": 'modèle de parole',
 "models.seg.other": 'autres programmes',
 "models.vramsub": "utilisée sur toute la machine",
 "models.vramnote": "Garder les deux en mémoire est tout l'intérêt : une chaîne qui charge "
                    "les poids à chaque prise coûte des secondes, pas des millisecondes. "
                    "En surengagement, c'est le modèle de parole qui est évincé — la dictée "
                    "devient dix fois plus lente sans que rien n'en dise la raison.",

 "models.vram": "VRAM · ",
 "models.sharednote": "Ce GPU n'a pas de mémoire propre — les poids sont des pages système ordinaires, et la barre ci-dessus représente toute la machine. Garder les deux en mémoire reste tout l'intérêt, mais ici le surengagement coûte du swap plutôt qu'une éviction : la dictée se bloque au lieu de seulement ralentir, et tout le reste de la machine se bloque avec elle.",
 "models.shared": 'Mémoire partagée · ',
 "models.needs": "requiert",
 "dict.rules": "règles",
 "dict.names": "noms",
 "dict.blurb": "entendu → voulu. Un prompt de décodeur est un indice que le modèle peut "
               "ignorer ; ici, c'est la garantie. La clé la plus longue est essayée "
               "d'abord, donc une plus courte qu'elle contient ne se déclenche jamais.",
 "dict.shadowed": "ne se déclenche jamais — masquée par ",
 "dict.remove": "Retirer",
 "dict.heard": 'entendu comme',
 "dict.meant": 'devrait être',
 "dict.add": 'Ajouter',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": "Hyprland  Postgres  Wayland — plusieurs à la fois, c'est bon",
 "dict.namesblurb": "N'écris que la forme correcte. Les noms sont injectés dans le prompt "
                    "du décodeur pour que le modèle les produise, puis appariés par le son "
                    "pour que les homophones se rabattent dessus. L'appariement reste "
                    "désactivé jusqu'à ce qu'un essai à blanc ait été examiné — c'est la "
                    "seule chose ici qui puisse abîmer un texte déjà correct.",
 "dict.matching": "appariement",
 "dict.seedonly": "prompt seulement",
 "dict.dryrun": "Essai à blanc",
 "dict.enable": "Activer l'appariement",
 "dict.prompt": "prompt : ",
 "dict.none": "(aucun)",
 "dict.overbudget": "%1 de plus n'ont pas tenu dans le budget du prompt",
 "set.ptt": "maintenir pour parler",
 "set.toggle": "appuyer pour démarrer, puis pour arrêter",
 "set.dwell.always": "toujours",
 "set.dwell.changed": "si modifié",
 "set.dwell.never": "jamais",
 "set.hotkey": "RACCOURCI",
 "set.key.type": "ou saisissez-la, p. ex. F9",
 "set.key.rebind": 'Appuie sur une touche',
 "set.key.press": "en attente — appuyez maintenant, ou maintenez une combinaison",
 "set.key": "touche",
 "set.behaviour": "utilisation",
 "set.key.check": 'Vérifier à nouveau',
 "set.key.ok": 'écoute sur %1',
 "set.key.testing": 'vérification…',
 "set.key.badname": "%1 n'est pas une touche que cette machine possède — appuie plutôt sur une touche",
 "set.key.nogroup": "Tu n'es pas dans le groupe `input`, donc aucun clavier ne peut être ouvert — "
                    "la touche est lue directement sur le périphérique, sous le bureau",
 "set.key.relogin": 'Tu es dans le groupe `input`, mais cette session a commencé avant — le démon peut être lancé avec le groupe maintenant, sans te déconnecter',
 "set.key.nodevice": 'Aucun clavier ici ne signale %1 — appuie sur une autre touche',
 "set.key.stopped": "Le service en arrière-plan ne tourne pas, donc rien n'écoute",
 "set.key.stale": "Le service écoute encore sur %1 — il n'a jamais pris en compte le changement",
 "set.key.off": 'Le raccourci est désactivé',
 "set.key.fix.restart": 'Le redémarrer',
 "set.key.fix.regroup": 'Le lancer avec le groupe',
 "set.key.fix.group": "M'ajouter à `input`",
 "set.hotkeynote": "La touche est reconnue par sa position : changer de disposition de clavier ne la déplace pas, et elle garde sa fonction habituelle.",
 "set.preroll": "commencer en avance de",
 "set.prerollwhy": "Garde un instant de son d'avant l'appui sur la touche, pour que votre premier mot ne soit pas coupé.",
 "set.tail": "arrêter en retard de",
 "set.warnbelow": "alerte volume bas à",
 "set.maxtake": "prise la plus longue",
 "set.hud": "À L'ÉCRAN",
 "set.hud.show": "afficher",
 "set.hud.size": "taille",
 "set.size.xs": "petit",
 "set.size.s": "moyen",
 "set.size.m": "grand",
 "set.keepup": "afficher le résultat",
 "set.hudnote": "D'habitude, le résultat ne fait que passer. « Si modifié » le laisse un peu plus longtemps quand une règle ou une étape d'IA a changé ce que vous avez dit, ou en cas de problème. Avec « jamais », ce que vous dites ne s'affiche pas à l'écran.",
 "set.notifications": "notifications",
 "set.on": "activé",
 "set.off": "désactivé",
 "set.history": "HISTORIQUE ET CONFIDENTIALITÉ",
 "set.keepaudio": "garder les enregistrements",
 "set.takes": " prises",
 "set.historynote": "Seuls ces enregistrements les plus récents sont gardés, pour réécouter une prise ; le texte reste de toute façon. 0 n'en garde aucun.",
 "set.clearhistory": "Effacer tout l'historique",
 "set.clearnote": "Toutes les prises, et tous les enregistrements encore sur le disque, d'un coup. C'est sans retour — une par une, c'est un clic droit dans l'onglet historique.",
 "set.clear.confirm": "Supprimer toutes les prises et tous les enregistrements ? C'est sans retour.",
 "set.clear.cancel": "Annuler",
 "set.clear.go": "Tout supprimer",
 "set.neverleaves": "L'audio ne quitte jamais cette machine",
 "set.audioleaves": "L'audio est envoyé à %1",
 "set.privacynote.api": "Le moteur vocal est une API distante : l'audio de chaque prise quitte cette machine. Revenez au moteur local dans l'onglet Modèles pour le garder ici.",
 "set.privacynote": "La reconnaissance vocale se fait sur cette machine. Le texte n'en sort que si la réécriture IA d'un mode utilise l'API distante ou l'agent système — l'onglet Modes montre lesquels.",
 "set.editconfig": "Modifier",
 "set.restart": "Redémarrer le service",
 "set.configpath": "Tous les réglages sont dans ~/.config/omavoi/config.toml.",
 "bar.stopped": "arrêté",
 "bar.tip.notinstalled": "Omavoi — pas encore installé. Clique pour l'installer.",
 "bar.tip.ready": "Omavoi — prêt",
 "bar.tip.recording": "Enregistrement · relâche la touche pour transcrire",
 "bar.tip.rightclick": "Clic droit pour démarrer ou arrêter une prise",
 "bar.tip.stopped": "Omavoi — le service en arrière-plan ne tourne pas. Clique pour ouvrir la console.",
 "bar.tip.transcribing": "Transcription…",
 "bar.tip.unfinished": "Omavoi — installation inachevée (%1)",
 "dict.dryrun.none": "Rien ne changerait.",
 "dict.dryrun.running": "Essai à blanc · en cours…",
 "edit.revert": "Annuler",
 "edit.save": "Enregistrer",
 "edit.unsaved": "non enregistré",
 "first.dbstale.age": "Ta base de paquets a %1 jours.",
 "first.dbstale.age1": "Ta base de paquets a un jour.",
 "models.notready": "pas prêt",
 "modes.speechnone": "Aucun modèle vocal n'est encore téléchargé — l'onglet Modèles les propose.",
 "modes.pick.title": "changement de mode",
 "modes.langfixed": "N'écoute que cette langue : plus fiable si c'est celle que vous parlez, mais les autres langues peuvent sortir fausses.",
 "modes.script": "caractères chinois",
 "modes.script.none": "tels que reconnus",
 "modes.script.hans": "simplifiés",
 "modes.script.hant": "traditionnels",
 "modes.droppunct": "retirer la ponctuation finale",
 "modes.addwhich": "réécrire avec :",
 "modes.adv": "AVANCÉ",
 "modes.adv.changed": "modifié : %1",
 "modes.adv.sep": ", ",
 "modes.adv.kv": "%1 : %2",
 "modes.adv.cleanup": "nettoyage",
 "modes.speechreload": "Passer à ce mode charge d'abord ce modèle, ce qui prend quelques secondes.",
 "modes.prompthint": "Lu par la reconnaissance avant d'écouter — un coup de pouce, pas une garantie. Les mots de Mon dictionnaire y sont ajoutés d'eux-mêmes.",
 "modes.promptinherited": "Ce mode n'a pas d'indice à lui et utilise celui de default. Enregistrer ici lui en donne un.",
 "modes.inject.hint.auto": "Tape le texte, sauf dans les applications Electron comme VS Code et Slack et dans les navigateurs Chromium, où il le colle. Les applications X11 sont tapées avec xdotool.",
 "modes.inject.hint.type": "Tape toujours, via wtype — sauf les applications X11, tapées avec xdotool.",
 "modes.inject.hint.paste": "Colle toujours, puis remet votre presse-papiers — sauf les applications X11, tapées avec xdotool.",
 "modes.sum.ai": "IA : %1",
 "modes.sum.plain": "sans IA",
 "modes.sum.hans": "chinois simplifié",
 "modes.sum.hant": "chinois traditionnel",
 "modes.sum.nopunct": "sans ponctuation finale",
 "modes.sum.paste": "colle",
 "modes.sum.type": "tape",
 "setup.optional": "optionnel",
 "set.hotkey.sub": "La touche pour parler. Ce que vous dites arrive là où se trouve le curseur.",
 "set.hud.sub": "La petite bande en bas de l'écran pendant que vous parlez.",
 "set.notifynote": "Une notification quand une prise comporte un avertissement ou n'a rien entendu.",
 "set.history.sub": "L'historique est conservé sur cette machine, et nulle part ailleurs.",
 "set.tailwhy": "Continue d'enregistrer un instant après le relâchement, pour que votre dernier mot ne soit pas coupé.",
 "set.warnwhy": "Une prise plus faible est signalée dans l'historique — un son trop faible est la cause habituelle des mots manquants.",
 "set.maxwhy": "L'enregistrement s'arrête tout seul après cette durée.",
 "set.configfile": "fichier de configuration",
 "hist.yesterday": "hier %1",
 "hist.droppedas": "écartée · %1",
 "hist.drop.short": "trop courte (%1 s)",
 "hist.drop.nospeech": "aucune parole entendue",
 "hist.drop.failed": "reconnaissance échouée",
 "hist.w.quiet": "L'enregistrement était faible (%1 dBFS), la cause habituelle des mots manquants.",
 "hist.w.step": "L'étape IA %1 (%2) n'a pas marché : %3 — le texte d'avant a été utilisé.",
 "hist.w.wrapped": "Le début de cette prise a été perdu.",
 "hist.w.lowconf": "La reconnaissance était incertaine — des mots peuvent être faux ou manquer.",
 "hist.w.silence": "Une partie était peut-être du silence — vérifiez ce passage du texte.",
 "hist.w.noxdotool": "C'est une fenêtre X11 et xdotool n'est pas installé : le texte n'a pas pu y arriver.",
 "hist.w.script": "La conversion des caractères chinois a échoué ; le texte est resté tel que reconnu.",
 "hist.w.fellback": "Pour cette fenêtre, la saisie est passée à %1.",
 "hist.w.injectfailed": "Le texte n'a pas pu être saisi dans la fenêtre.",
 "hist.c.fillers": "mots de remplissage retirés",
 "hist.c.deduped": "phrases répétées fusionnées",
 "hist.c.spacing": "espace ajoutée entre CJK et latin",
 "hist.c.lines": "lignes réunies",
 "hist.c.punct": "ponctuation finale retirée",
 "hist.c.dictionary": "corrigé d'après Mon dictionnaire : %1",
 "hist.c.silence": "un passage de silence omis",
 "hist.c.hans": "converti en chinois simplifié",
 "hist.c.hant": "converti en chinois traditionnel",
 "hist.took": "%1 s",
 "hist.details": "DÉTAILS",
 "hist.rtfnote": "Le RTF compare le temps de reconnaissance à votre temps de parole ; sous 1, c'est plus rapide que le temps réel.",
 "hist.raw": "tel que le service l'a écrit",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': 'Ajouter un mot',
 'word.edit': 'Modifier le mot',
 'word.intro': 'Ajoutez des noms et des termes spécialisés pour aider Omavoi à les écrire correctement.',
 'word.spelling': 'Orthographe souhaitée',
 'word.examples': 'Ex. : Marie Dupont, Acme, JavaScript',
 'word.spaces': 'Saisissez le nom ou la phrase entière. Les espaces sont autorisés.',
 'word.wrong': 'Toujours mal écrit ?',
 'word.heard': 'Que donne Omavoi à la place ?',
 'word.another': 'Ajouter une autre forme',
 'word.removealias': 'Retirer',
 'word.replacehelp': 'Ces formes seront remplacées par « %1 ». Ajoutez uniquement ce qui doit toujours '
                     'être corrigé.',
 'word.more': 'Plus d’options',
 'word.hint': 'Aider à reconnaître ce mot',
 'word.hinthelp': 'Ce mot est transmis au service de reconnaissance, éventuellement avec l’audio dans '
                  'le cloud.',
 'word.case': 'Utiliser ces majuscules et minuscules',
 'word.sound': 'Corriger les formes aux sons proches',
 'word.soundhelp': 'Cela peut modifier des mots déjà corrects. Vérifiez d’abord l’aperçu.',
 'word.scope': 'Appliquer dans',
 'word.allmodes': 'Tous les modes',
 'word.previewhelp': 'Testez une phrase sans enregistrer ni appeler un service d’IA.',
 'word.sample': 'Collez une phrase à tester…',
 'word.preview': 'Voir les corrections',
 'word.casewarning': 'Cela change aussi %1. Désactivable dans Plus d’options.',
 'word.save': 'Enregistrer',
 'word.cancel': 'Annuler',
 'word.discardhelp': 'Abandonner les modifications non enregistrées ?',
 'word.keepediting': 'Continuer à modifier',
 'word.discard': 'Abandonner',
 'word.search': 'Rechercher un mot ou une erreur…',
 'word.from': 'Corrige :',
 'word.paused': 'En pause',
 'word.pause': 'Mettre en pause',
 'word.resume': 'Réactiver',
 'word.delete': 'Supprimer le mot et ses corrections',
 'word.undo': 'Annuler',
 'word.empty': 'Ajoutez un nom ou un mot souvent mal écrit par Omavoi.',
 'word.noresults': 'Aucun mot trouvé.',
 'word.loading': 'Chargement du dictionnaire…',
 'word.saved': 'Enregistré.',
 'word.pending': 'Enregistré, mais pas encore actif. Réessayez ou démarrez le service vocal.',
 'word.retry': 'Réessayer',
 'word.refresh': 'Recharger en gardant le brouillon',
 'word.failed': 'Échec de l’enregistrement. Vos modifications sont conservées.',
 'word.readfailed': 'Impossible de lire le dictionnaire. Réessayez.',
 'word.stale': 'Le dictionnaire a changé ailleurs. Rechargez-le ; votre brouillon sera conservé.',
 'word.duplicate': 'Ce mot existe déjà. Modifiez l’entrée existante.',
 'word.conflict': 'Cette forme entre en conflit avec un autre mot ou une correction.',
 'word.invalid': 'Saisissez 1 à 200 caractères sans retour à la ligne.',
 'word.correct': 'Cette orthographe est déjà correcte.',
 'word.invalidmode': 'Un mode sélectionné n’existe plus.',
 'word.missing': 'Ce mot a été supprimé ailleurs. Rechargez le dictionnaire.',
 'word.capacity': 'Certains mots ne servent pas d’indice. Leurs corrections restent actives :',
 'word.legacy': 'Votre dictionnaire reste disponible ci-dessous. Mettez à jour le service vocal ou '
                'vérifiez les réglages indiqués pour le nouvel éditeur.',
 'word.use': 'Utiliser mon dictionnaire',
 'word.partial': 'Partiellement actif'})

PACK.update({'word.deleted': 'Mot et corrections supprimés.',
 'word.restart': 'Redémarrez le service vocal pour utiliser le nouveau dictionnaire. Les mots '
                 'existants sont inchangés.'})

PACK.update({'modes.langsearch': 'Rechercher une langue…', 'modes.langempty': 'Aucune langue correspondante', 'modes.langupgrade': 'Mettez à jour le service vocal pour choisir une langue de saisie.'})
