# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Omavoi のセットアップ',
 "first.blurb": "質問は三つ、そのあとボタン一つ。押すまで何も実行されず、コマンドは必ず先に表示します。",
 "first.pick.language": '画面の言語',
 "first.pick.model": '音声モデル',
 "first.reuse": "この端末に既にある音声モデル —— その場所のまま使い、ダウンロードは不要です",
 "first.reuse.label": '既にあるものを使う',
 "first.m.large": "turbo 系は無音と発話を区別できませんが、これはできます",
 "first.m.turbo": "既定値。ダウンロードは半分で、より高速",
 "first.m.light": "まだ使う価値のある最軽量のもの",
 "first.willrun": '実行される内容',
 "first.needspassword": 'パスワードを尋ねます',
 "first.install": 'インストール',
 "first.retry": '再試行',
 "first.working": '%1 …',
 "first.failed": '%1 に失敗しました —— 下を参照してください',
 "first.cancelled": 'パスワード入力が取り消されたので、何もインストールされていません',
 "first.done": '準備完了 —— キーを押しながら話してください',
 "first.dbstale": "今インストールすると 404 で失敗するかもしれません。記録されているバージョンがミラーにもう無い可能性があります。先にシステムを更新するのが安全です。",
 "first.updatebtn": 'システムパッケージを更新',
 "first.pacman404": 'パッケージデータベースが古く、記録されたバージョンがミラーに残っていません。上でシステムを更新してから、もう一度お試しください。',
 "first.pick.hotkey": '押しながら話すキー',
 "first.hotkey.other": '他のキー（例：F9）',
 "first.hotkey.note": "キーボードレイアウトより下で読み取り、決して奪わないので、そのキーは本来の動作を続けます。米国以外の多くのレイアウトでは右 Alt が AltGr で文字入力に使われます。そうしたレイアウトなら右 Ctrl か Scroll Lock を選んでください。",
 "first.group.needed": "まだ input グループに入っていないため、キーを読み取れません。下のステップであなたを追加し、バックグラウンドサービスがすぐにグループ権限を持てるように起動します。ログアウトは不要です。",
 "first.step.hotkey": 'ホットキー',
 "first.step.packages": 'システムパッケージ',
 "first.step.daemon": "バックグラウンドサービス",
 "first.step.language": '言語',
 "first.step.weights": "音声モデル",
 "first.step.use": 'モデルを選択',
 "first.step.mode": '既定のモード',
 "first.step.service": 'ユニット・ショートカット・メニュー項目',
 "up.title": '更新',
 "up.behind": 'プラグインのブランチに %1 件の新しいコミットがあります',
 "up.current": '最新です',
 "up.daemon.blind": "バックグラウンドサービスは別にインストールされているため、ここでは最新かどうか分かりません。更新すると一緒に再インストールされます。",
 "up.unknown": '判定できません —— このプラグインは git から入れたものではありません',
 "up.nofetch": "リモートに接続できなかったため、これが最新とは限りません：%1",
 "up.noupstream": "プラグインのブランチに upstream が設定されていないため、比較する対象がありません",
 "up.dirty": "インストール済みのプラグインにローカルの変更があるため早送りできません。入れ直してください：omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes",
 "up.run": '更新する',
 "up.again": 'もう一度確認',
 "up.done": '更新しました',
 "up.step.plugin": 'プラグイン',
 "up.step.daemon": "バックグラウンドサービス",
 "up.step.shortcuts": 'ユニット・ショートカット・メニュー項目',
 "up.step.restart": '再起動',
 "nav.setup": 'セットアップ',
 "setup.rootblurb": "上の管理者パスワードが必要な手順は、ここでまとめて行えます。パスワードの確認は一度だけです。その後、インストールしたものを認識させるためにバックグラウンドサービスを再起動します。",
 "setup.rootrun": 'まとめて入れる',
 "nav.history": "履歴",
 "nav.modes": "モード",
 "nav.models": "モデル",
 "nav.dictionary": '自分の辞書',
 "nav.settings": "設定",
 "state.idle": "待機中",
 "state.recording": "録音中",
 "state.transcribing": "文字起こし中",
 "state.stopped": "サービス停止中",
 "hud.stage.decoding": '文字起こし中',
 "hud.stage.llm": '書き換え中',
 "hud.stage.injecting": '入力中',
 "hud.nospeech": '音声なし',

 "setup.prefix": "セットアップ ",
 "setup.title": 'あと %1 個インストールが必要',
 "setup.titledone": 'すべて揃っています',
 "setup.blurb": "押すまで何も実行されず、各ステップは先にコマンドを表示します。",
 "setup.copy": "コピー",
 "setup.run": "実行",
 "setup.recheck": "再確認",
 "setup.hint": "またはターミナルで  omavoi setup  を実行 —— 手順も順序も同じです",

 "hist.problems": "起きた問題",
 "hist.fellthrough": "うまくいかず、直前の文章を使いました",
 "hist.none": "まだ録音がありません —— %1 を押しながら話してください",
 "hist.yourkey": "設定したキー",
 "hist.audio": "長さ",
 "hist.level": "音量",
 "hist.decode": "認識時間",
 "hist.model": "モデル",
 "hist.language": "言語",
 "hist.injected": "入力方法",
 "hist.said": "聞き取った内容",
 "hist.post": "整形で変わったこと",
 "hist.segments": "セグメント信頼度",
 "hist.copy": "コピー",
 "hist.play": "再生",
 "hist.delete": "削除",

 "modes.wontfit": '空き %1 が必要',
 "modes.blocked": '切り替えていません —— このモードのモデルは今の VRAM に収まりません',
 "modes.speechmodel": "音声モデル",
 "modes.speechglobal": "既定のものを使う",
 "modes.speechglobalnamed": "既定のものを使う (%1)",
 "modes.speechonly1": "音声モデルは1つしかダウンロードされていません。「モデル」タブに小さいものがあり、正確さより速さを重視するモードに向いています。",
 "modes.newname": "新しいモード名",
 "modes.here": "使用中",
 "modes.fallback": "フォールバック",
 "modes.followwin": "モードはフォーカス中のウィンドウに追従します",
 "modes.everytake": "毎回このモードを使用： ",
 "modes.longestwins": "下で最も長く一致したものが勝ちます。何も一致しなければ default に戻ります。",
 "modes.matchoff": "ウィンドウ照合は無効なので、下のリストは設定済みでも動作しません。"
                   "役に立つまでにはアプリごとの調整が必要です。",
 "modes.hiddenauto": "フォーカス中のウィンドウがモードを選ぶため、下のモードをクリックしても開くだけです。",
 "modes.following": "ウィンドウに従う",
 "modes.fixed": "ここで選ぶ",
 "modes.delete": "モードを削除",
 "modes.opens": "起動条件",
 "modes.notinuse": "モードが固定の間は使われません",
 "modes.nothing": "なし —— このモードは名前でしか呼び出せません",
 "modes.classph": "ウィンドウクラス（例：thunderbird）",
 "modes.add": "追加",
 "modes.matchhint": "Hyprland のクラスとタイトルに照合します。最も長い一致が勝ちます。",
 "modes.s1": "音声認識",
 "modes.language": "話す言語",
 "modes.decoderhint": "認識ヒント",
 "modes.promptph": "例：Hyprland、Quickshell、PipeWire についての会議。",
 "modes.s2": "整形",
 "modes.rulessub": "AI を使わず、即座に、毎回同じ結果で。",
 "modes.r.hallucinations": "繰り返した文をまとめる",
 "modes.r.fillers": "フィラーを取り除く",
 "modes.r.dictionary": "辞書",
 "modes.r.names": "固有名詞",
 "modes.r.cjk": "和文と欧文の間にスペース",
 "modes.s3": "AI 書き直し",
 "modes.llmsub": "任意。ステップごとに数秒かかります。失敗したステップは受け取った文章をそのまま次へ渡します。",
 "modes.step": "ステップ ",
 "modes.stepsuffix": "",
 "modes.remove": "削除",
 "modes.stepph": "回答ではなく編集をさせる指示を書いてください。",
 "modes.addstep": "+ 書き直しステップを追加",
 "modes.weights": "モデル",
 "modes.inherit": "既定のものを使う (%1)",
 "modes.nollm": "LLM が未設定です —— 「モデル」タブを確認してください",
 "modes.inject.auto": "自動",
 "modes.inject.type": "打鍵で入力",
 "modes.inject.clipboard": "貼り付け",
 "modes.langauto": "自動",
 "modes.s4": "入力方法",

 "models.speech": "音声認識",
 "models.speechsub": "話した内容を文字にします。使う方法は一度に一つです。",
 "models.e.vulkan": "このパソコン",
 "models.e.vulkan.sub": "グラフィックカードで動きます（なければ CPU）。何もパソコンの外に出ません。",
 "models.e.vulkan.note": "音声は手元に残る",
 "models.e.api": "リモート API",
 "models.e.api.sub": "指定したオンラインの音声認識サービス。OpenAI、Groq、SiliconFlow、自前のサーバーなど。",
 "models.e.api.note": "音声がこの端末から出ます",
 "models.now": "実行中",
 "models.running": "稼働中",
 "models.notloaded": "未ロード",
 "models.llmnone": '未ロード — それぞれ初回の使用時に起動します',
 "models.coldshort": '停止中',
 "models.ready": "準備完了",
 "models.nodaemon": "バックグラウンドサービスに接続できないため、何が読み込まれているか分かりません",
 "models.f.edit": '編集',
 "models.f.close": '閉じる',
 "models.f.url": "アドレス",
 "models.f.model": 'モデル',
 "models.f.key": 'キー',
 "models.f.key.place": "キーを貼り付け（secrets.toml にだけ保存されます）",
 "models.f.key.save": '保存',
 "models.f.key.saved": "secrets.toml に保存しました（本人だけが読めます）",
 "models.f.key.failed": '保存できませんでした',
 "models.f.test": '接続テスト',
 "models.f.testing": "接続中…",
 "models.f.testok": '応答あり、%1 個のモデル —— 下から選んでください',
 "models.f.key.have": 'キーは保存済み',
 "models.f.key.fromenv": "環境変数 %1 のキーを使用中。ここで保存したキーより優先されます",
 "models.f.key.fromfile": 'secrets.toml に保存済み',
 "models.f.testfail": '応答がありません',
 "models.speechapi": "リモートサービス",
 "models.speechapi.sub": "音声の送り先：アドレス、モデル、キーを入力します。",
 "models.speechapi.cat": "これはローカルエンジン用のモデルです。リモート API を使っている間は使われません。",
 "models.k.agent": 'システムのエージェント',
 "models.k.agent.sub": "Omarchy が使うように設定したコーディングエージェント。ログイン済みでキーは不要、毎回数秒かかります。話した内容はそのサービスに送られます。",
 "models.k.agent.argv": "（コマンドラインに話した内容が含まれ、このパソコンのほかのプログラムからも見えます。）",
 "models.k.local": 'ローカルモデル',
 "models.k.local.sub": "下の一覧のモデルをこのパソコンで動かします。何も外に出ません。",
 "models.k.api": 'リモート API',
 "models.k.api.sub": "指定したオンラインのモデル。アドレスとキーが必要で、話した内容はそこに送られます。",
 "models.k.unset": '未設定',
 "models.stale": "バックグラウンドサービスは起動時に読み込んだモデルをまだ使っています",
 "models.loaded": "読み込み済み ",
 "models.configured": "設定済み ",
 "models.restart": "バックグラウンドサービスを再起動",
 "models.ondisk": "ディスクに既にあります",
 "models.downloading": "ダウンロード中…",
 "models.download": "ダウンロード",
 "models.use": "使用",
 "models.remove": "削除",
 "models.ourstore": "こちらの保存先",
 "models.outside": "%1 以外で見つかったモデルはその場所のまま使い、削除しません。",
 "models.llm": "AI 書き直し",
 "models.llmsub": "モードの AI 書き直しで使える方法です。3 つとも同時に用意しておけます。",
 "models.nokey": "キーなし",
 "models.endpointnote": "キーは設定ファイルに書かれません。secrets.toml に保存するか、環境変数で渡します。",
 "models.seg.speech": '音声モデル',
 "models.seg.other": '他のプログラム',
 "models.vramnote": "2 つのモデルを読み込んだままにするので、すぐに書き起こせます。メモリが足りなくなると音声モデルが先に追い出され、大幅に遅くなります。",

 "models.vram": "VRAM · ",
 "models.sharednote": "このグラフィックチップはパソコンのメモリを共有しているため、バーはパソコン全体を表します。いっぱいになるとスワップが始まり、全体が遅くなります。",
 "models.shared": '共有メモリ · ',
 "models.needs": "必要",
 "dict.rules": "ルール",
 "dict.names": "固有名詞",
 "dict.blurb": "聞こえた語 → 本来の語。デコーダーのプロンプトはモデルが無視できる助言にすぎませんが、"
               "こちらは保証です。照合は最も長いキーから試すので、それに含まれる短いキーは"
               "決して発火しません。",
 "dict.shadowed": "決して発火しません —— 次のキーに隠れています： ",
 "dict.remove": "削除",
 "dict.heard": '聞こえ方',
 "dict.meant": '正しくは',
 "dict.add": '追加',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": 'Hyprland  Postgres  Wayland — まとめて追加できます',
 "dict.namesblurb": "正しい表記だけを書いてください。固有名詞はデコーダーのプロンプトに入れて"
                    "モデルがその形を出すようにし、その後で音の近さで照合して同音の表記を"
                    "引き戻します。照合はドライランを確認するまで無効のままです —— "
                    "ここで唯一、すでに正しいテキストを壊しうる機能だからです。",
 "dict.matching": "照合中",
 "dict.seedonly": "プロンプトのみ",
 "dict.dryrun": "ドライラン",
 "dict.enable": "照合を有効化",
 "dict.prompt": "プロンプト： ",
 "dict.none": "（なし）",
 "dict.overbudget": "さらに %1 件はプロンプトの上限に収まりませんでした",
 "set.ptt": "押している間だけ話す",
 "set.toggle": "押して開始、もう一度押して終了",
 "set.dwell.always": "常に",
 "set.dwell.changed": "変化したとき",
 "set.dwell.never": "しない",
 "set.hotkey": "ホットキー",
 "set.key.type": "または入力（例：F9）",
 "set.key.rebind": 'キーを押す',
 "set.key.press": "待機中 — 今押してください。組み合わせを押したままでも構いません",
 "set.key": "キー",
 "set.behaviour": "押し方",
 "set.key.check": 'もう一度確認',
 "set.key.ok": '%1 で待機中',
 "set.key.testing": '確認中…',
 "set.key.badname": '%1 はこのマシンに無いキーです — 使いたいキーを押してください',
 "set.key.nogroup": '`input` グループに入っていないため、キーボードを一つも開けません — '
                    'キーはデスクトップより下、デバイスから直接読んでいます',
 "set.key.relogin": '`input` グループには入っていますが、このセッションはそれより前に始まりました — デーモンを今すぐグループ権限付きで起動できます。ログアウトは不要です',
 "set.key.nodevice": 'ここのキーボードはどれも %1 を報告しません — 別のキーを押してください',
 "set.key.stopped": 'バックグラウンドのサービスが動いていないため、何も待機していません',
 "set.key.stale": 'サービスはまだ %1 を待機しています — 変更を受け取っていません',
 "set.key.off": 'ショートカットは無効になっています',
 "set.key.fix.restart": '再起動する',
 "set.key.fix.regroup": 'グループ権限付きで起動',
 "set.key.fix.group": '`input` に自分を追加',
 "set.hotkeynote": "キーは物理的な位置で認識されるため、キーボード配列を変えても影響せず、本来の機能もそのまま使えます。",
 "set.preroll": "先行録音",
 "set.prerollwhy": "キーを押す直前の音も少し録音して、最初の言葉が切れないようにします。",
 "set.tail": "離した後の録音",
 "set.warnbelow": "音量警告のしきい値",
 "set.maxtake": "最長録音時間",
 "set.hud": "画面表示",
 "set.hud.show": "表示する",
 "set.hud.size": "サイズ",
 "set.size.xs": "小",
 "set.size.s": "中",
 "set.size.m": "大",
 "set.keepup": "結果を表示",
 "set.hudnote": "通常、結果は一瞬だけ表示されます。「変化したとき」は、ルールや AI が内容を変えたときや問題があったときに少し長く表示します。「しない」を選ぶと、話した内容は画面に表示されません。",
 "set.notifications": "通知",
 "set.on": "オン",
 "set.off": "オフ",
 "set.history": "履歴とプライバシー",
 "set.keepaudio": "録音を残す",
 "set.takes": " 件",
 "set.historynote": "再生用に、新しい録音だけをこの数まで残します。文字の記録はそのまま残ります。0 にすると録音は残しません。",
 "set.clearhistory": "履歴をすべて削除",
 "set.clearnote": "すべての記録と、ディスクに残っている音声を一度に削除します。取り消しはできません —— 1 件ずつなら履歴タブで右クリックしてください。",
 "set.clear.confirm": "すべての記録と音声を削除しますか？取り消しはできません。",
 "set.clear.cancel": "キャンセル",
 "set.clear.go": "すべて削除",
 "set.neverleaves": "音声はこの端末から出ません",
 "set.audioleaves": "音声は %1 にアップロードされます",
 "set.privacynote.api": "音声認識エンジンがリモート API なので、毎回の音声がこのパソコンの外に送られます。「モデル」タブでローカルエンジンに戻すと、音声は手元に残ります。",
 "set.privacynote": "音声認識はこのパソコン上で行われます。モードの AI 書き直しでリモート API かシステムのエージェントを使う場合だけ、文字が外部に送られます。どのモードかは「モード」タブで確認できます。",
 "set.editconfig": "編集する",
 "set.restart": "バックグラウンドサービスを再起動",
 "set.configpath": "設定はすべて ~/.config/omavoi/config.toml に保存されます。",
 "bar.stopped": "停止中",
 "bar.tip.notinstalled": "Omavoi —— まだインストールされていません。クリックして設定します。",
 "bar.tip.ready": "Omavoi —— 準備完了",
 "bar.tip.recording": "録音中 · キーを離すと文字起こしします",
 "bar.tip.rightclick": "右クリックで録音の開始と停止",
 "bar.tip.stopped": "Omavoi —— バックグラウンドのサービスが動いていません。クリックでコンソールを開きます。",
 "bar.tip.transcribing": "文字起こし中……",
 "bar.tip.unfinished": "Omavoi —— セットアップ未完了（%1）",
 "dict.dryrun.none": "変わるものはありません。",
 "dict.dryrun.running": "ドライラン · 実行中……",
 "edit.revert": "元に戻す",
 "edit.save": "保存",
 "edit.unsaved": "未保存",
 "first.dbstale.age": "パッケージデータベースが %1 日前のものです。",
 "first.dbstale.age1": "パッケージデータベースが一日前のものです。",
 "models.notready": "未準備",
 "modes.speechnone": "音声モデルはまだダウンロードされていません。「モデル」タブから入手できます。",
 "modes.pick.title": "モードの切り替え",
 "modes.langfixed": "この言語だけを聞き取ります。主にこの言語を話すなら安定しますが、ほかの言語は誤認識されることがあります。",
 "modes.script": "中国語の字体",
 "modes.script.none": "変換しない",
 "modes.script.hans": "簡体字",
 "modes.script.hant": "繁体字",
 "modes.droppunct": "文末の句読点を取る",
 "modes.addwhich": "書き直しに使う：",
 "modes.adv": "詳細設定",
 "modes.adv.changed": "変更あり：%1",
 "modes.adv.sep": "、",
 "modes.adv.kv": "%1：%2",
 "modes.adv.cleanup": "整形",
 "modes.speechreload": "このモードに切り替えると、先にこのモデルを読み込むため数秒かかります。",
 "modes.prompthint": "認識モデルが聞き取りの前に読む文章です。ヒントであって保証ではありません。「自分の辞書」の語は自動で加わります。",
 "modes.promptinherited": "このモードには独自のヒントがないため、default のものを使っています。ここで保存するとこのモード専用になります。",
 "modes.inject.hint.auto": "文字を打ち込みます。ただし VS Code や Slack などの Electron アプリと Chromium 系ブラウザでは貼り付けます。X11 アプリには xdotool で入力します。",
 "modes.inject.hint.type": "常に wtype で打ち込みます。X11 アプリだけは xdotool で入力します。",
 "modes.inject.hint.paste": "常に貼り付け、その後クリップボードを元に戻します。X11 アプリだけは xdotool で入力します。",
 "modes.sum.ai": "AI：%1",
 "modes.sum.plain": "AI なし",
 "modes.sum.hans": "簡体字",
 "modes.sum.hant": "繁体字",
 "modes.sum.nopunct": "文末句読点なし",
 "modes.sum.paste": "貼り付け",
 "modes.sum.type": "打ち込み",
 "setup.optional": "任意",
 "set.hotkey.sub": "話すときに使うキー。話した内容はカーソルの位置に入力されます。",
 "set.hud.sub": "話している間、画面下部に出る小さな表示です。",
 "set.notifynote": "録音に警告があったときや、何も聞き取れなかったときに通知します。",
 "set.history.sub": "履歴はこのパソコンにだけ保存されます。",
 "set.tailwhy": "キーを離した後も少し録音を続け、最後の言葉が切れないようにします。",
 "set.warnwhy": "これより小さい録音は履歴で警告されます。音量不足は言葉が抜ける一番の原因です。",
 "set.maxwhy": "この時間を超えると自動で録音を止めます。",
 "set.configfile": "設定ファイル",
 "hist.yesterday": "昨日 %1",
 "hist.droppedas": "破棄 · %1",
 "hist.drop.short": "短すぎます（%1 秒）",
 "hist.drop.nospeech": "声が聞き取れませんでした",
 "hist.drop.failed": "認識に失敗しました",
 "hist.w.quiet": "録音の音量が小さめでした（%1 dBFS）。言葉が抜ける一番の原因です。",
 "hist.w.step": "AI 書き直しの %1 番目（%2）がうまくいきませんでした：%3 — 直前の文章を使いました。",
 "hist.w.wrapped": "この録音の冒頭が失われました。",
 "hist.w.lowconf": "認識に自信がなく、誤りや抜けがあるかもしれません。",
 "hist.w.silence": "一部が無音だった可能性があります。その部分の文章を確認してください。",
 "hist.w.noxdotool": "X11 のウィンドウですが xdotool が入っていないため、文字が届きませんでした。",
 "hist.w.script": "中国語の字体変換に失敗したため、認識結果のままにしました。",
 "hist.w.fellback": "このウィンドウでは %1 に切り替えて入力しました。",
 "hist.w.injectfailed": "ウィンドウに文字を入力できませんでした。",
 "hist.c.fillers": "フィラーを取り除きました",
 "hist.c.deduped": "繰り返した文をまとめました",
 "hist.c.spacing": "和文と欧文の間にスペースを入れました",
 "hist.c.lines": "改行をまとめました",
 "hist.c.punct": "文末の句読点を取りました",
 "hist.c.dictionary": "「自分の辞書」で修正：%1",
 "hist.c.silence": "無音の部分を省きました",
 "hist.c.hans": "簡体字に変換しました",
 "hist.c.hant": "繁体字に変換しました",
 "hist.took": "%1 秒",
 "hist.details": "詳細",
 "hist.rtfnote": "RTF は認識にかかった時間 ÷ 話した時間です。1 未満なら実時間より速いということです。",
 "hist.raw": "バックグラウンドサービスの原文",
 "models.list.speech": "音声モデル",
 "models.list.speech.sub": "大きいほど正確で、小さいほど速くなります。● が付いているのが使用中です。",
 "models.list.llm": "ローカル AI モデル",
 "models.list.llm.sub": "「ローカルモデル」で書き直すときに使います。「使う」で既定にでき、モードのステップごとにも選べます。",
 "models.usedby": "%1 が使用中",
 "models.seg.llm": "AI モデル",
 "setup.s.tools": "録音と入力のツール",
 "setup.s.engine": "音声認識エンジン",
 "setup.s.engineapi": "音声認識エンジン（リモート API）",
 "setup.s.model": "音声モデル（%1）",
 "setup.s.llm": "ローカル AI エンジン（llama.cpp）",
 "setup.s.hotkey": "キー（%1）",
 "setup.s.service": "ログイン時に起動",
 "setup.d.tools": "声を録音し、文字をウィンドウに入力するためのシステムツールです。",
 "setup.d.engine": "このパソコンで声を文字にするプログラムです。",
 "setup.d.model": "認識に使うモデルファイルです。ダウンロードは一度だけです。",
 "setup.d.llm": "モードの AI 書き直しでローカルモデルを使う場合だけ必要です。",
 "setup.d.hotkey": "キーを読み取るには input グループに入っている必要があります。",
 "setup.d.service": "ログインのたびにバックグラウンドサービスを起動します。",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': '単語を追加',
 'word.edit': '単語を編集',
 'word.intro': '人名や会社名、専門用語を追加して、Omavoi が正しく表記できるようにします。',
 'word.spelling': '正しい表記',
 'word.examples': '例：山田太郎、会社名、JavaScript',
 'word.spaces': '名前や語句をそのまま入力してください。スペースも使えます。',
 'word.wrong': 'よく間違えますか？',
 'word.heard': 'どのように間違えますか？',
 'word.another': '別の表記を追加',
 'word.removealias': '削除',
 'word.replacehelp': 'これらの表記を「%1」に変更します。常に修正したい表記だけを追加してください。',
 'word.more': 'その他の設定',
 'word.hint': 'この単語を認識しやすくする',
 'word.hinthelp': '音声認識サービスに単語を渡します。クラウド利用時は音声と一緒に送信される場合があります。',
 'word.case': 'この大文字・小文字表記を使う',
 'word.sound': '発音が似た表記も修正する',
 'word.soundhelp': '正しい単語も変わる場合があります。先に結果を確認してください。',
 'word.scope': '適用先',
 'word.allmodes': 'すべてのモード',
 'word.previewhelp': '文章を貼り付けて修正を確認できます。録音や AI サービスの呼び出しは行いません。',
 'word.sample': '試したい文章を貼り付け…',
 'word.preview': '修正結果を確認',
 'word.casewarning': '%1 も変更されます。その他の設定で無効にできます。',
 'word.save': '保存',
 'word.cancel': 'キャンセル',
 'word.discardhelp': '未保存の変更を破棄しますか？',
 'word.keepediting': '編集を続ける',
 'word.discard': '変更を破棄',
 'word.search': '単語や間違った表記を検索…',
 'word.from': '修正対象：',
 'word.paused': '一時停止中',
 'word.pause': '使用を一時停止',
 'word.resume': '使用を再開',
 'word.delete': '単語と修正設定を削除',
 'word.undo': '元に戻す',
 'word.empty': 'よく間違える名前や単語を追加してください。',
 'word.noresults': '該当する単語がありません。',
 'word.loading': '辞書を読み込み中…',
 'word.saved': '保存しました。',
 'word.pending': '保存済みですが未反映です。再試行するか音声サービスを起動してください。',
 'word.retry': '再試行',
 'word.refresh': '下書きを残して再読み込み',
 'word.failed': '保存できませんでした。入力内容は保持されています。',
 'word.readfailed': '辞書を読み込めません。再試行してください。',
 'word.stale': '別の場所で変更されました。下書きを残して再読み込みしてください。',
 'word.duplicate': 'この単語は登録済みです。既存の単語を編集してください。',
 'word.conflict': 'この表記は他の単語や修正と競合しています。',
 'word.invalid': '改行を含めず 1〜200 文字で入力してください。',
 'word.correct': 'この表記はすでに正しいため修正は不要です。',
 'word.invalidmode': '選択したモードがありません。選び直してください。',
 'word.missing': 'この単語は別の場所で削除されました。再読み込みしてください。',
 'word.capacity': '認識のヒントに使われなかった単語があります。設定済みの文字修正は有効です：',
 'word.legacy': '従来の辞書は下で使えます。新しい編集画面には音声サービスの更新、または表示された旧設定の確認が必要です。',
 'word.use': '自分の辞書を使う',
 'word.partial': '一部有効'})

PACK.update({'word.deleted': '単語と修正設定を削除しました。', 'word.restart': '新しい辞書を使うには音声サービスを再起動してください。既存の単語は変更されていません。'})

PACK.update({'modes.langsearch': '言語を検索…', 'modes.langempty': '一致する言語がありません', 'modes.langupgrade': '入力言語を選ぶには音声サービスを更新してください。'})
