# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Thiết lập Omavoi',
 "first.blurb": "Ba câu hỏi, rồi một nút. Không có gì chạy cho đến khi bạn bấm, và mọi câu lệnh đều được hiện ra trước.",
 "first.pick.language": 'Ngôn ngữ giao diện',
 "first.pick.model": 'Mô hình giọng nói',
 "first.reuse": "mô hình giọng nói đã có sẵn trên máy này — dùng ngay tại chỗ, không cần tải",
 "first.reuse.label": 'Dùng cái đang có',
 "first.m.large": "các bản turbo không phân biệt được im lặng với lời nói; bản này thì được",
 "first.m.turbo": "mặc định; tải về một nửa và nhanh hơn",
 "first.m.light": "cái nhẹ nhất mà vẫn đáng dùng",
 "first.willrun": 'NHỮNG GÌ SẼ CHẠY',
 "first.needspassword": 'sẽ hỏi mật khẩu của bạn',
 "first.install": 'Cài đặt',
 "first.retry": 'Thử lại',
 "first.working": '%1 …',
 "first.failed": '%1 thất bại — xem bên dưới',
 "first.cancelled": 'hộp nhập mật khẩu đã bị hủy, nên chưa có gì được cài',
 "first.done": 'Xong — giữ phím của bạn và nói',
 "first.dbstale": "Cài đặt lúc này có thể lỗi 404: các phiên bản nó ghi có thể không còn trên máy chủ gương. Cập nhật hệ thống trước là an toàn hơn.",
 "first.updatebtn": 'Cập nhật gói hệ thống',
 "first.pacman404": 'Cơ sở dữ liệu gói đã lạc hậu nên mirror không còn các phiên bản nó ghi. Hãy cập nhật hệ thống ở trên rồi thử lại.',
 "first.pick.hotkey": 'Phím giữ để nói',
 "first.hotkey.other": 'phím khác, ví dụ F9',
 "first.hotkey.note": "Được đọc bên dưới sơ đồ bàn phím và không bao giờ bị chiếm, nên phím vẫn làm việc của nó. Trên nhiều sơ đồ ngoài Mỹ, Alt phải là AltGr và dùng để gõ ký tự — hãy chọn Ctrl phải hoặc Scroll Lock nếu bàn phím của bạn như vậy.",
 "first.group.needed": "Bạn chưa ở trong nhóm input nên chưa đọc được phím nào. Bước bên dưới sẽ thêm bạn và khởi động dịch vụ nền để có quyền nhóm ngay — không cần đăng xuất.",
 "first.step.hotkey": 'phím tắt',
 "first.step.packages": 'gói hệ thống',
 "first.step.daemon": "dịch vụ nền",
 "first.step.language": 'ngôn ngữ',
 "first.step.weights": "mô hình giọng nói",
 "first.step.use": 'chọn mô hình',
 "first.step.mode": 'chế độ mặc định',
 "first.step.service": 'unit, phím tắt và mục trong menu',
 "up.title": 'CẬP NHẬT',
 "up.behind": 'có %1 commit mới trên nhánh của plugin',
 "up.current": 'Đã mới nhất',
 "up.daemon.blind": "Dịch vụ nền được cài riêng nên ở đây không biết nó có mới nhất không; cập nhật sẽ cài lại nó luôn.",
 "up.unknown": 'Không xác định được — plugin này không cài từ git',
 "up.nofetch": "Không kết nối được tới remote, nên đây có thể không phải bản mới nhất: %1",
 "up.noupstream": "Nhánh của plugin không có upstream, nên không có gì để so sánh",
 "up.dirty": 'Plugin đã cài có thay đổi cục bộ nên không fast-forward được. Hãy cài lại: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Cập nhật',
 "up.again": 'Kiểm tra lại',
 "up.done": 'Đã cập nhật',
 "up.step.plugin": 'plugin',
 "up.step.daemon": "dịch vụ nền",
 "up.step.shortcuts": 'unit, phím tắt và mục trong menu',
 "up.step.restart": 'khởi động lại',
 "nav.setup": "Thiết lập",
 "setup.rootblurb": "Các bước ở trên cần mật khẩu quản trị có thể làm luôn ở đây, chỉ hỏi mật khẩu một lần. Sau đó dịch vụ nền khởi động lại để nhận ra những gì vừa cài.",
 "setup.rootrun": 'Cài các mục này',
 "nav.history": "Lịch sử",
 "nav.modes": "Chế độ",
 "nav.models": "Mô hình",
 "nav.dictionary": 'Từ điển của tôi',
 "nav.settings": "Cài đặt",
 "state.idle": "rảnh",
 "state.recording": "đang ghi",
 "state.transcribing": "đang chuyển thành chữ",
 "state.stopped": "dịch vụ đã dừng",
 "hud.stage.decoding": 'đang chuyển thành chữ',
 "hud.stage.llm": 'đang viết lại',
 "hud.stage.injecting": 'đang gõ',
 "hud.nospeech": "không nghe thấy lời nói",

 "setup.prefix": "cài đặt ",
 "setup.title": "Còn %1 bước",
 "setup.titledone": 'Mọi thứ đã sẵn sàng',
 "setup.blurb": "Không có gì chạy cho đến khi bạn bấm, và mỗi bước đều hiện lệnh trước.",
 "setup.copy": "Sao chép",
 "setup.run": "Chạy",
 "setup.recheck": "Kiểm tra lại",
 "setup.hint": "hoặc chạy  omavoi setup  trong terminal — cùng các bước, cùng thứ tự",

 "hist.problems": "CÓ GÌ SAI",
 "hist.fellthrough": "không thành công — đã dùng văn bản trước đó",
 "hist.none": "chưa có bản ghi nào — giữ %1 và nói",
 "hist.yourkey": "phím của bạn",
 "hist.audio": "độ dài",
 "hist.level": "âm lượng",
 "hist.decode": "thời gian nhận dạng",
 "hist.model": "mô hình",
 "hist.language": "ngôn ngữ",
 "hist.injected": "nhập bằng",
 "hist.said": "ĐIỀU NÓ NGHE ĐƯỢC",
 "hist.post": "PHẦN LÀM SẠCH ĐÃ SỬA",
 "hist.segments": "ĐỘ TIN CẬY TỪNG ĐOẠN",
 "hist.copy": "Sao chép",
 "hist.play": "Phát",
 "hist.delete": "Xóa",

 "modes.wontfit": 'cần %1 trống',
 "modes.blocked": "chưa chuyển — mô hình của chế độ này hiện không vừa bộ nhớ đồ họa",
 "modes.speechmodel": "mô hình giọng nói",
 "modes.speechglobal": "dùng mặc định",
 "modes.speechglobalnamed": "dùng mặc định (%1)",
 "modes.speechonly1": "Mới tải một mô hình giọng nói. Thẻ Mô hình có mô hình nhỏ hơn, hợp với chế độ cần tốc độ hơn độ chính xác.",
 "modes.newname": "tên chế độ mới",
 "modes.here": "đang dùng",
 "modes.fallback": "dự phòng",
 "modes.followwin": "Chế độ đi theo cửa sổ đang được chọn",
 "modes.everytake": "Mọi bản ghi đều dùng ",
 "modes.longestwins": "Mẫu khớp dài nhất bên dưới thắng; không khớp gì thì quay về default.",
 "modes.matchoff": "Việc khớp theo cửa sổ đang tắt, nên các danh sách bên dưới đã được "
                   "cấu hình nhưng không có tác dụng. Nó cần được tinh chỉnh cho từng "
                   "ứng dụng trước khi đáng dùng.",
 "modes.hiddenauto": "Cửa sổ đang được chọn quyết định chế độ, nên bấm vào một chế độ bên dưới chỉ mở nó ra.",
 "modes.following": "theo cửa sổ",
 "modes.fixed": "chọn tại đây",
 "modes.delete": "Xóa chế độ",
 "modes.opens": "MỞ KHI",
 "modes.notinuse": "không dùng khi chế độ đang cố định",
 "modes.nothing": "không có — chế độ này chỉ gọi được bằng tên",
 "modes.classph": "class cửa sổ, ví dụ thunderbird",
 "modes.add": "Thêm",
 "modes.matchhint": "Đối chiếu với class và title của Hyprland. Mẫu khớp dài nhất thắng.",
 "modes.s1": "GIỌNG NÓI",
 "modes.language": "ngôn ngữ nói",
 "modes.decoderhint": "gợi ý nhận dạng",
 "modes.promptph": "vd: Cuộc họp về Hyprland, Quickshell và PipeWire.",
 "modes.s2": "LÀM SẠCH",
 "modes.rulessub": "Không dùng AI: tức thì, và lần nào cũng như nhau.",
 "modes.r.hallucinations": "gộp câu lặp lại",
 "modes.r.fillers": "bỏ từ đệm",
 "modes.r.dictionary": "từ điển",
 "modes.r.names": "tên riêng",
 "modes.r.cjk": "khoảng cách giữa CJK và Latin",
 "modes.s3": "AI VIẾT LẠI",
 "modes.llmsub": "Tùy chọn. Mỗi bước tốn thêm vài giây; bước nào lỗi sẽ chuyển tiếp văn bản nó nhận được.",
 "modes.step": "bước ",
 "modes.stepsuffix": "",
 "modes.remove": "Bỏ",
 "modes.stepph": "Hãy bảo nó sửa văn bản, đừng để nó trả lời.",
 "modes.addstep": "+ thêm bước viết lại",
 "modes.weights": "Mô hình",
 "modes.inherit": "dùng mặc định (%1)",
 "modes.nollm": "chưa thiết lập mô hình AI nào — xem thẻ Mô hình",
 "modes.inject.auto": "tự động",
 "modes.inject.type": "gõ từng chữ",
 "modes.inject.clipboard": "dán",
 "modes.langauto": "tự động",
 "modes.s4": "cách nhập",

 "models.speech": "NHẬN DẠNG GIỌNG NÓI",
 "models.speechsub": "Biến lời bạn nói thành văn bản. Mỗi lúc chỉ dùng một cách.",
 "models.e.vulkan": "Trên máy này",
 "models.e.vulkan.sub": "Chạy trên card đồ họa, hoặc trên CPU nếu không có. Không có gì rời khỏi máy.",
 "models.e.vulkan.note": "âm thanh ở lại máy",
 "models.e.api": "API từ xa",
 "models.e.api.sub": "Dịch vụ giọng nói bạn chỉ định — OpenAI, Groq, SiliconFlow hoặc máy chủ riêng.",
 "models.e.api.note": "âm thanh sẽ rời khỏi máy này",
 "models.now": "đang chạy",
 "models.running": "đang chạy",
 "models.notloaded": "chưa nạp",
 "models.llmnone": 'chưa nạp — mỗi cái khởi động khi dùng lần đầu',
 "models.coldshort": "chưa chạy",
 "models.ready": "sẵn sàng",
 "models.nodaemon": "dịch vụ nền không phản hồi, nên không biết đang tải gì",
 "models.f.edit": 'Sửa',
 "models.f.close": 'Đóng',
 "models.f.url": "địa chỉ",
 "models.f.model": 'Mô hình',
 "models.f.key": 'Khóa',
 "models.f.key.place": "dán khóa vào đây — chỉ lưu trong secrets.toml",
 "models.f.key.save": 'Lưu',
 "models.f.key.saved": "đã lưu vào secrets.toml, chỉ bạn đọc được",
 "models.f.key.failed": 'không lưu được',
 "models.f.test": 'Kiểm tra',
 "models.f.testing": "đang kết nối…",
 "models.f.testok": 'đã trả lời, %1 mô hình — chọn một bên dưới',
 "models.f.key.have": 'đã lưu một khoá',
 "models.f.key.fromenv": "đang dùng khóa từ %1 trong môi trường, được ưu tiên hơn khóa lưu ở đây",
 "models.f.key.fromfile": 'đã lưu trong secrets.toml',
 "models.f.testfail": 'không có phản hồi',
 "models.speechapi": "dịch vụ từ xa",
 "models.speechapi.sub": "Nơi âm thanh được gửi tới: địa chỉ, mô hình và khóa.",
 "models.speechapi.cat": "Đây là các mô hình của công cụ trên máy; khi dùng API từ xa thì chúng không được dùng.",
 "models.k.agent": 'Agent hệ thống',
 "models.k.agent.sub": "Agent lập trình mà Omarchy đang dùng. Đã đăng nhập, không cần khóa; mất vài giây mỗi lần. Lời bạn được gửi tới dịch vụ của agent đó.",
 "models.k.agent.argv": "(Dòng lệnh của nó chứa lời bạn nói, các chương trình khác trên máy này có thể thấy.)",
 "models.k.local": 'Mô hình cục bộ',
 "models.k.local.sub": "Chạy một mô hình trong danh sách bên dưới ngay trên máy này. Không có gì rời khỏi máy.",
 "models.k.api": 'API từ xa',
 "models.k.api.sub": "Một mô hình trực tuyến bạn chỉ định, cần địa chỉ và khóa. Lời bạn được gửi tới đó.",
 "models.k.unset": 'chưa cấu hình',
 "models.stale": "Dịch vụ nền vẫn đang dùng mô hình đã tải lúc khởi động",
 "models.loaded": "đã nạp ",
 "models.configured": "đã cấu hình ",
 "models.restart": "Khởi động lại dịch vụ nền",
 "models.ondisk": "đã có trên đĩa",
 "models.downloading": "đang tải…",
 "models.download": "Tải về",
 "models.use": "Dùng",
 "models.remove": "Xóa",
 "models.ourstore": "kho của chúng ta",
 "models.outside": "Mô hình tìm thấy ngoài %1 được dùng tại chỗ và không bao giờ bị xóa.",
 "models.llm": "AI VIẾT LẠI",
 "models.llmsub": "Những gì bước AI viết lại của một chế độ có thể dùng. Cả ba có thể sẵn sàng cùng lúc.",
 "models.nokey": "chưa có khóa",
 "models.endpointnote": "Khóa không bao giờ được ghi vào cấu hình: nó được giữ trong secrets.toml hoặc lấy từ biến môi trường.",
 "models.seg.speech": 'mô hình giọng nói',
 "models.seg.other": 'chương trình khác',
 "models.vramnote": "Cả hai mô hình luôn được nạp sẵn để đọc chính tả tức thì. Nếu thiếu bộ nhớ, mô hình giọng nói bị đẩy ra trước và việc đọc chính tả chậm đi nhiều.",

 "models.vram": "VRAM · ",
 "models.sharednote": "Chip đồ họa này dùng chung bộ nhớ của máy, nên thanh này là cả máy. Khi đầy, hệ thống bắt đầu dùng swap và mọi thứ chậm lại.",
 "models.shared": 'Bộ nhớ dùng chung · ',
 "models.needs": "cần",
 "dict.rules": "quy tắc",
 "dict.names": "tên riêng",
 "dict.blurb": "nghe thành → thật ra là. Prompt của bộ giải mã chỉ là gợi ý mà mô hình có "
               "thể bỏ qua; đây mới là thứ bảo đảm. Khóa dài nhất được thử trước, nên một "
               "khóa ngắn hơn nằm bên trong nó sẽ không bao giờ chạy.",
 "dict.shadowed": "không bao giờ chạy — bị che bởi ",
 "dict.remove": "Bỏ",
 "dict.heard": 'nghe thành',
 "dict.meant": 'đúng ra là',
 "dict.add": 'Thêm',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": 'Hyprland  Postgres  Wayland — thêm nhiều cái một lúc cũng được',
 "dict.namesblurb": "Chỉ viết dạng đúng. Tên riêng được đưa vào prompt của bộ giải mã để mô "
                    "hình tạo ra chúng, rồi sau đó khớp theo âm để các từ đồng âm quay về "
                    "đúng dạng. Việc khớp vẫn tắt cho đến khi bạn xem một lần chạy thử — "
                    "đây là thứ duy nhất ở đây có thể làm hỏng văn bản vốn đã đúng.",
 "dict.matching": "đang khớp",
 "dict.seedonly": "chỉ đưa vào prompt",
 "dict.dryrun": "Chạy thử",
 "dict.enable": "Bật việc khớp",
 "dict.prompt": "prompt: ",
 "dict.none": "(không có)",
 "dict.overbudget": "%1 tên nữa không vừa hạn mức prompt",
 "set.ptt": "giữ để nói",
 "set.toggle": "bấm để bắt đầu, bấm lại để dừng",
 "set.dwell.always": "luôn luôn",
 "set.dwell.changed": "khi có thay đổi",
 "set.dwell.never": "không bao giờ",
 "set.hotkey": "PHÍM NÓNG",
 "set.key.type": "hoặc gõ tên, vd F9",
 "set.key.rebind": 'Bấm một phím',
 "set.key.press": "đang chờ — bấm ngay, hoặc giữ một tổ hợp phím",
 "set.key": "phím",
 "set.behaviour": "cách bấm",
 "set.key.check": 'Kiểm tra lại',
 "set.key.ok": 'đang nghe trên %1',
 "set.key.testing": 'đang kiểm tra…',
 "set.key.badname": '%1 không phải là phím máy này có — hãy bấm một phím thay vì vậy',
 "set.key.nogroup": "Cần quyền của nhóm `input` để đọc phím, và bạn chưa ở trong nhóm này",
 "set.key.relogin": "Bạn vào nhóm `input` sau khi phiên này bắt đầu — dịch vụ nền có thể khởi động cùng nhóm ngay bây giờ, không cần đăng xuất",
 "set.key.nodevice": "Không bàn phím nào của bạn có phím %1 — hãy thử phím khác",
 "set.key.stopped": 'Dịch vụ nền không chạy, nên không có gì đang nghe',
 "set.key.stale": "Dịch vụ nền vẫn đang nghe phím %1 — hãy khởi động lại để dùng phím mới",
 "set.key.off": 'Phím tắt đang bị tắt',
 "set.key.fix.restart": 'Khởi động lại',
 "set.key.fix.regroup": 'Khởi động cùng nhóm',
 "set.key.fix.group": 'Thêm tôi vào `input`',
 "set.hotkeynote": "Phím được nhận theo vị trí thật trên bàn phím, nên đổi bố cục bàn phím không ảnh hưởng, và phím vẫn làm được việc cũ.",
 "set.preroll": "ghi sớm hơn",
 "set.prerollwhy": "Giữ một chút âm thanh trước khi nhấn phím, để từ đầu tiên không bị cắt.",
 "set.tail": "ghi thêm sau khi thả",
 "set.warnbelow": "cảnh báo âm lượng dưới",
 "set.maxtake": "ghi lâu nhất",
 "set.hud": "TRÊN MÀN HÌNH",
 "set.hud.show": "hiển thị",
 "set.hud.size": "kích thước",
 "set.size.xs": "nhỏ",
 "set.size.s": "vừa",
 "set.size.m": "lớn",
 "set.keepup": "hiện kết quả",
 "set.hudnote": "Thường kết quả chỉ hiện thoáng qua. “Khi có thay đổi” sẽ giữ lâu hơn khi quy tắc hoặc AI đã sửa lời bạn, hoặc có sự cố. Chọn “không bao giờ” thì lời bạn nói sẽ không hiện trên màn hình.",
 "set.notifications": "thông báo",
 "set.on": "bật",
 "set.off": "tắt",
 "set.history": "LỊCH SỬ VÀ QUYỀN RIÊNG TƯ",
 "set.keepaudio": "giữ bản ghi âm",
 "set.takes": " bản ghi",
 "set.historynote": "Chỉ giữ chừng này bản ghi âm mới nhất để nghe lại; văn bản của mỗi lần vẫn được giữ. Đặt 0 để không giữ bản nào.",
 "set.clearhistory": "Xóa toàn bộ lịch sử",
 "set.clearnote": "Mọi bản ghi, và mọi tệp âm thanh còn trên đĩa, cùng một lúc. Không hoàn tác được — muốn xóa từng cái thì nhấp chuột phải trong tab lịch sử.",
 "set.clear.confirm": "Xóa mọi bản ghi và mọi tệp âm thanh? Không thể hoàn tác.",
 "set.clear.cancel": "Hủy",
 "set.clear.go": "Xóa tất cả",
 "set.neverleaves": "Âm thanh không bao giờ rời khỏi máy này",
 "set.audioleaves": "Âm thanh được tải lên %1",
 "set.privacynote.api": "Công cụ nhận dạng là API từ xa, nên âm thanh mỗi lần ghi đều rời máy này. Chuyển lại công cụ cục bộ ở thẻ Mô hình để giữ âm thanh trên máy.",
 "set.privacynote": "Nhận dạng giọng nói chạy trên máy này. Văn bản chỉ rời máy khi AI viết lại của một chế độ dùng API từ xa hoặc agent hệ thống — thẻ Chế độ cho biết chế độ nào.",
 "set.editconfig": "Chỉnh sửa",
 "set.restart": "Khởi động lại dịch vụ nền",
 "set.configpath": "Mọi cài đặt nằm trong ~/.config/omavoi/config.toml.",
 "bar.stopped": "đã dừng",
 "bar.tip.notinstalled": "Omavoi — chưa được cài. Bấm để thiết lập.",
 "bar.tip.ready": "Omavoi — sẵn sàng",
 "bar.tip.recording": "Đang ghi",
 "bar.tip.rightclick": "Nhấp chuột phải để bắt đầu hoặc dừng một lần đọc",
 "bar.tip.stopped": "Omavoi — dịch vụ nền không chạy. Bấm để mở bảng điều khiển.",
 "bar.tip.transcribing": "Đang chuyển thành chữ…",
 "bar.tip.unfinished": "Omavoi — cài đặt chưa xong (%1)",
 "dict.dryrun.none": "Sẽ không có gì thay đổi.",
 "dict.dryrun.running": "Chạy thử · đang chạy…",
 "edit.revert": "Hoàn tác",
 "edit.save": "Lưu",
 "edit.unsaved": "chưa lưu",
 "first.dbstale.age": "Cơ sở dữ liệu gói của bạn đã cũ %1 ngày.",
 "first.dbstale.age1": "Cơ sở dữ liệu gói của bạn đã cũ một ngày.",
 "models.notready": "chưa sẵn sàng",
 "modes.speechnone": "Chưa tải mô hình giọng nói nào — thẻ Mô hình có sẵn.",
 "modes.pick.title": "chuyển chế độ",
 "modes.langfixed": "Chỉ nghe ngôn ngữ này: ổn định hơn nếu bạn chủ yếu nói nó, nhưng ngôn ngữ khác có thể ra sai.",
 "modes.script": "chữ Hán",
 "modes.script.none": "giữ như nhận dạng",
 "modes.script.hans": "giản thể",
 "modes.script.hant": "phồn thể",
 "modes.droppunct": "bỏ dấu câu cuối",
 "modes.addwhich": "viết lại bằng:",
 "modes.adv": "NÂNG CAO",
 "modes.adv.changed": "đã đổi: %1",
 "modes.adv.sep": ", ",
 "modes.adv.kv": "%1: %2",
 "modes.adv.cleanup": "làm sạch",
 "modes.speechreload": "Khi chuyển sang chế độ này, mô hình đó được tải trước, mất vài giây.",
 "modes.prompthint": "Bộ nhận dạng đọc đoạn này trước khi nghe — chỉ là gợi ý, không bảo đảm. Từ trong Từ điển của tôi được tự thêm vào.",
 "modes.promptinherited": "Chế độ này không có gợi ý riêng nên dùng của default. Lưu tại đây sẽ tạo gợi ý riêng cho nó.",
 "modes.inject.hint.auto": "Gõ văn bản, trừ trong ứng dụng Electron như VS Code, Slack và trình duyệt Chromium, nơi nó dán vào. Ứng dụng X11 được gõ bằng xdotool.",
 "modes.inject.hint.type": "Luôn gõ qua wtype — trừ ứng dụng X11, được gõ bằng xdotool.",
 "modes.inject.hint.paste": "Luôn dán, rồi trả lại bộ nhớ tạm của bạn — trừ ứng dụng X11, được gõ bằng xdotool.",
 "modes.sum.ai": "AI: %1",
 "modes.sum.plain": "không AI",
 "modes.sum.hans": "Trung giản thể",
 "modes.sum.hant": "Trung phồn thể",
 "modes.sum.nopunct": "không dấu câu cuối",
 "modes.sum.paste": "dán",
 "modes.sum.type": "gõ",
 "setup.optional": "tùy chọn",
 "set.hotkey.sub": "Phím dùng để nói. Lời bạn nói sẽ xuất hiện ở vị trí con trỏ.",
 "set.hud.sub": "Thanh nhỏ ở cuối màn hình khi bạn nói.",
 "set.notifynote": "Thông báo khi bản ghi có cảnh báo hoặc không nghe thấy gì.",
 "set.history.sub": "Lịch sử chỉ được lưu trên máy này.",
 "set.tailwhy": "Ghi thêm một chút sau khi thả phím, để từ cuối không bị cắt.",
 "set.warnwhy": "Bản ghi nhỏ hơn mức này sẽ được đánh dấu trong Lịch sử — âm quá nhỏ là nguyên nhân thường gặp khiến mất chữ.",
 "set.maxwhy": "Việc ghi tự dừng sau khoảng thời gian này.",
 "set.configfile": "tệp cấu hình",
 "hist.yesterday": "hôm qua %1",
 "hist.droppedas": "đã bỏ · %1",
 "hist.drop.short": "quá ngắn (%1 giây)",
 "hist.drop.nospeech": "không nghe thấy lời nói",
 "hist.drop.failed": "nhận dạng thất bại",
 "hist.w.quiet": "Bản ghi khá nhỏ (%1 dBFS), nguyên nhân thường gặp khiến mất chữ.",
 "hist.w.step": "Bước AI %1 (%2) không thành công: %3 — đã dùng văn bản trước đó.",
 "hist.w.wrapped": "Phần đầu của bản ghi này bị mất.",
 "hist.w.lowconf": "Bộ nhận dạng không chắc chắn — có thể có từ sai hoặc thiếu.",
 "hist.w.silence": "Một đoạn có thể là im lặng — hãy kiểm tra đoạn văn bản đó.",
 "hist.w.noxdotool": "Đây là cửa sổ X11 và chưa cài xdotool, nên văn bản không vào được.",
 "hist.w.script": "Chuyển đổi chữ Hán thất bại, nên giữ nguyên văn bản như đã nhận dạng.",
 "hist.w.fellback": "Lần này đã chuyển sang nhập bằng %1.",
 "hist.w.injectfailed": "Không thể gõ văn bản vào cửa sổ.",
 "hist.c.fillers": "đã bỏ từ đệm",
 "hist.c.deduped": "đã gộp câu lặp lại",
 "hist.c.spacing": "đã thêm khoảng cách giữa CJK và Latin",
 "hist.c.lines": "đã nối các dòng",
 "hist.c.punct": "đã bỏ dấu câu cuối",
 "hist.c.dictionary": "đã sửa theo Từ điển của tôi: %1",
 "hist.c.silence": "đã bỏ một đoạn im lặng",
 "hist.c.hans": "đã chuyển sang Trung giản thể",
 "hist.c.hant": "đã chuyển sang Trung phồn thể",
 "hist.took": "mất %1 giây",
 "hist.details": "CHI TIẾT",
 "hist.rtfnote": "RTF là thời gian nhận dạng so với thời gian bạn nói; dưới 1 là nhanh hơn thời gian thực.",
 "hist.raw": "nguyên văn từ dịch vụ nền",
 "models.list.speech": "mô hình giọng nói",
 "models.list.speech.sub": "Càng lớn càng chính xác, càng nhỏ càng nhanh. Cái có dấu ● đang được dùng.",
 "models.list.llm": "mô hình AI trên máy",
 "models.list.llm.sub": "Dùng cho cách viết lại “Mô hình cục bộ”. Nút Dùng đặt làm mặc định; bước trong chế độ vẫn chọn riêng được.",
 "models.usedby": "%1 đang dùng",
 "models.seg.llm": "mô hình AI",
 "setup.s.tools": "Công cụ ghi âm và nhập chữ",
 "setup.s.engine": "Công cụ nhận dạng",
 "setup.s.engineapi": "Công cụ nhận dạng (API từ xa)",
 "setup.s.model": "Mô hình giọng nói (%1)",
 "setup.s.llm": "Công cụ AI trên máy (llama.cpp)",
 "setup.s.hotkey": "Phím (%1)",
 "setup.s.service": "Khởi động khi đăng nhập",
 "setup.d.tools": "Các công cụ hệ thống để ghi giọng nói và gõ chữ vào cửa sổ.",
 "setup.d.engine": "Chương trình chuyển giọng nói thành văn bản trên máy này.",
 "setup.d.model": "Tệp mô hình dùng để nhận dạng. Chỉ cần tải một lần.",
 "setup.d.llm": "Chỉ cần khi AI viết lại của một chế độ dùng mô hình cục bộ.",
 "setup.d.hotkey": "Để đọc được phím, bạn cần ở trong nhóm input.",
 "setup.d.service": "Khởi động dịch vụ nền mỗi khi bạn đăng nhập.",
 "setup.x.missing": "Còn thiếu: %1",
 "setup.x.notinstalled": "Chưa cài %1",
 "setup.x.nocpu": "Đã cài whisper.cpp nhưng thiếu backend CPU mà nó cũng cần — sẽ dừng khi đang tải mô hình",
 "setup.x.notdownloaded": "Chưa tải xuống · %1",
 "setup.x.reading": "Dịch vụ nền đang nghe phím này",
 "setup.x.relogin": "Đã ở trong nhóm input, nhưng phiên này bắt đầu trước khi vào nhóm",
 "setup.x.ingroup": "Đã ở trong nhóm input",
 "setup.x.notingroup": "Chưa vào nhóm input",
 "setup.x.enabled": "Đã bật",
 "setup.x.notenabled": "Chưa bật",
 "setup.x.nounit": "Chưa thiết lập",
 "setup.x.provider": "Nhà cung cấp: %1",
 "setup.titleoptional": "Đã dùng được · còn %1 mục tùy chọn",
 "bar.tip.hold": "Giữ %1 và nói",
 "bar.tip.toggle": "Nhấn %1 để bắt đầu, nhấn lần nữa để kết thúc",
 "bar.tip.release": "Thả %1 để kết thúc",
 "bar.tip.again": "Nhấn %1 lần nữa để kết thúc",
 "word.corrects": "Sửa: %1",
 "word.sep": ", ",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': 'Thêm từ',
 'word.edit': 'Sửa từ',
 'word.intro': 'Thêm tên riêng và thuật ngữ để giúp Omavoi viết đúng.',
 'word.spelling': 'Cách viết mong muốn',
 'word.examples': 'Ví dụ: Nguyễn An, Acme, JavaScript',
 'word.spaces': 'Nhập đầy đủ tên hoặc cụm từ. Có thể dùng dấu cách.',
 'word.wrong': 'Vẫn thường viết sai?',
 'word.heard': 'Omavoi thường viết thành gì?',
 'word.another': 'Thêm cách viết khác',
 'word.removealias': 'Bỏ',
 'word.replacehelp': 'Các cách viết này sẽ đổi thành “%1”. Chỉ thêm nội dung bạn luôn muốn sửa.',
 'word.more': 'Tùy chọn khác',
 'word.hint': 'Hỗ trợ nhận dạng từ này',
 'word.hinthelp': 'Cung cấp từ cho dịch vụ nhận dạng. Dịch vụ đám mây có thể nhận từ cùng âm thanh.',
 'word.case': 'Dùng kiểu viết hoa này',
 'word.sound': 'Sửa cách viết có âm gần giống',
 'word.soundhelp': 'Có thể đổi cả từ đã đúng. Hãy xem trước kết quả.',
 'word.scope': 'Áp dụng trong',
 'word.allmodes': 'Tất cả chế độ',
 'word.previewhelp': 'Dán một câu để xem kết quả, không ghi âm hay gọi dịch vụ AI.',
 'word.sample': 'Dán câu để thử…',
 'word.preview': 'Xem trước sửa đổi',
 'word.casewarning': 'Tùy chọn này cũng đổi %1. Có thể tắt trong Tùy chọn khác.',
 'word.save': 'Lưu',
 'word.cancel': 'Hủy',
 'word.discardhelp': 'Bỏ các thay đổi chưa lưu?',
 'word.keepediting': 'Tiếp tục sửa',
 'word.discard': 'Bỏ thay đổi',
 'word.search': 'Tìm từ hoặc cách viết sai…',
 'word.paused': 'Đã tạm dừng',
 'word.pause': 'Tạm dừng từ',
 'word.resume': 'Dùng lại từ',
 'word.delete': 'Xóa từ và các cách sửa',
 'word.undo': 'Hoàn tác',
 'word.empty': 'Thêm tên hoặc từ Omavoi thường viết sai.',
 'word.noresults': 'Không tìm thấy từ phù hợp.',
 'word.loading': 'Đang tải từ điển…',
 'word.saved': 'Đã lưu.',
 'word.pending': 'Đã lưu nhưng chưa có hiệu lực. Thử lại hoặc khởi động dịch vụ giọng nói.',
 'word.retry': 'Thử lại',
 'word.refresh': 'Tải lại và giữ bản nháp',
 'word.failed': 'Không lưu được. Nội dung đã nhập vẫn còn.',
 'word.readfailed': 'Không đọc được từ điển. Hãy thử lại.',
 'word.stale': 'Từ điển đã thay đổi ở nơi khác. Tải lại; bản nháp vẫn được giữ.',
 'word.duplicate': 'Từ này đã có. Hãy sửa mục hiện có.',
 'word.conflict': 'Cách viết này xung đột với từ hoặc cách sửa khác.',
 'word.invalid': 'Nhập 1–200 ký tự, không xuống dòng.',
 'word.correct': 'Cách viết này đã đúng, không cần sửa.',
 'word.invalidmode': 'Chế độ đã chọn không còn. Hãy chọn lại.',
 'word.missing': 'Từ này đã bị xóa ở nơi khác. Hãy tải lại.',
 "word.capacity": "Một số từ chưa được dùng làm gợi ý. Các cách sửa vẫn có hiệu lực: %1",
 'word.legacy': 'Từ điển cũ vẫn dùng được bên dưới. Cần cập nhật dịch vụ giọng nói hoặc xem lại cài đặt '
                'được liệt kê.',
 'word.use': 'Dùng từ điển của tôi',
 'word.partial': 'Bật một phần'})

PACK.update({'word.deleted': 'Đã xóa từ và các cách sửa.',
 'word.restart': 'Khởi động lại dịch vụ giọng nói để dùng từ điển mới. Các từ hiện có chưa thay '
                 'đổi.'})

PACK.update({'modes.langsearch': 'Tìm ngôn ngữ…', 'modes.langempty': 'Không có ngôn ngữ phù hợp', 'modes.langupgrade': 'Cập nhật dịch vụ giọng nói để chọn ngôn ngữ nhập.'})
