# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Thiết lập Omavoi',
 "first.blurb": "Ba câu hỏi, rồi một nút. Không có gì chạy cho đến khi bạn bấm, và mọi câu lệnh đều được hiện ra trước.",
 "first.pick.language": 'Ngôn ngữ giao diện',
 "first.pick.model": 'Mô hình giọng nói',
 "first.reuse": "mô hình giọng nói đã có sẵn trên máy này — dùng ngay tại chỗ, không cần tải",
 "first.reuse.label": 'Dùng cái đang có',
 "first.m.large": "các bản turbo không phân biệt được im lặng với lời nói; bản này thì được",
 "first.m.turbo": "mặc định; tải về một nửa và nhanh hơn",
 "first.m.light": "cái nhẹ nhất mà vẫn đáng dùng",
 "first.willrun": 'NHỮNG GÌ SẼ CHẠY',
 "first.needspassword": 'sẽ hỏi mật khẩu của bạn',
 "first.install": 'Cài đặt',
 "first.retry": 'Thử lại',
 "first.working": '%1 …',
 "first.failed": '%1 thất bại — xem bên dưới',
 "first.cancelled": 'hộp nhập mật khẩu đã bị hủy, nên chưa có gì được cài',
 "first.done": 'Xong — giữ phím của bạn và nói',
 "first.dbstale": "Cài bất cứ gì lúc này sẽ lỗi 404: các phiên bản nó ghi không còn trên mirror. Dù sao Arch cũng cần cập nhật hệ thống trước khi thêm gói mới.",
 "first.updatebtn": 'Cập nhật gói hệ thống',
 "first.pacman404": 'Cơ sở dữ liệu gói đã lạc hậu nên mirror không còn các phiên bản nó ghi. Hãy cập nhật hệ thống ở trên rồi thử lại.',
 "first.pick.hotkey": 'Phím giữ để nói',
 "first.hotkey.other": 'phím khác, ví dụ F9',
 "first.hotkey.note": "Được đọc bên dưới sơ đồ bàn phím và không bao giờ bị chiếm, nên phím vẫn làm việc của nó. Trên nhiều sơ đồ ngoài Mỹ, Alt phải là AltGr và dùng để gõ ký tự — hãy chọn Ctrl phải hoặc Scroll Lock nếu bàn phím của bạn như vậy.",
 "first.group.needed": 'Bạn chưa thuộc nhóm input, nên không đọc được phím nào. Bước bên dưới sẽ thêm bạn vào, và daemon được khởi động theo cách nhận quyền nhóm ngay lập tức — không cần đăng xuất.',
 "first.step.hotkey": 'phím tắt',
 "first.step.packages": 'gói hệ thống',
 "first.step.daemon": 'dịch vụ',
 "first.step.language": 'ngôn ngữ',
 "first.step.weights": "mô hình giọng nói",
 "first.step.use": 'chọn mô hình',
 "first.step.mode": 'chế độ mặc định',
 "first.step.service": 'unit, phím tắt và mục trong menu',
 "up.title": 'CẬP NHẬT',
 "up.behind": 'có %1 commit mới trên nhánh của plugin',
 "up.current": 'Đã mới nhất',
 "up.daemon.blind": "Dịch vụ nền được cài riêng nên ở đây không biết nó có mới nhất không; cập nhật sẽ cài lại nó luôn.",
 "up.unknown": 'Không xác định được — plugin này không cài từ git',
 "up.nofetch": "Không kết nối được tới remote, nên đây có thể không phải bản mới nhất: %1",
 "up.noupstream": "Nhánh của plugin không có upstream, nên không có gì để so sánh",
 "up.dirty": 'Plugin đã cài có thay đổi cục bộ nên không fast-forward được. Hãy cài lại: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Cập nhật',
 "up.again": 'Kiểm tra lại',
 "up.done": 'Đã cập nhật',
 "up.step.plugin": 'plugin',
 "up.step.daemon": "dịch vụ nền",
 "up.step.shortcuts": 'unit, phím tắt và mục trong menu',
 "up.step.restart": 'khởi động lại',
 "nav.setup": "Thiết lập",
 "setup.rootblurb": 'Các bước ở trên cần root có thể làm ngay tại đây, chỉ hỏi mật khẩu một lần — polkit xem pacman là auth_admin, gọi hai lần thì bị hỏi hai lần. Sau đó daemon được khởi động lại: nó ghi nhớ việc thiếu engine trong suốt vòng đời tiến trình, nên chỉ cài binary thôi thì nó vẫn báo là thiếu.',
 "setup.rootrun": 'Cài các mục này',
 "nav.history": "Lịch sử",
 "nav.modes": "Chế độ",
 "nav.models": "Mô hình",
 "nav.dictionary": 'Từ điển của tôi',
 "nav.settings": "Cài đặt",
 "state.idle": "rảnh",
 "state.recording": "đang ghi",
 "state.transcribing": "đang chuyển thành chữ",
 "state.stopped": "dịch vụ đã dừng",
 "hud.stage.decoding": 'đang chuyển thành chữ',
 "hud.stage.llm": 'đang viết lại',
 "hud.stage.injecting": 'đang gõ',
 "hud.nospeech": 'không có giọng nói',

 "setup.prefix": "cài đặt ",
 "setup.title": 'Còn phải cài: %1',
 "setup.titledone": 'Mọi thứ đã sẵn sàng',
 "setup.blurb": "Ở đây không có gì chạy cho đến khi bạn bấm, và mỗi bước đều hiện "
                "đúng câu lệnh trước. Omarchy cố tình không chạy bất cứ thứ gì từ "
                "trong thư mục plugin, nên màn hình này phải hỏi bạn.",
 "setup.copy": "Sao chép",
 "setup.run": "Chạy",
 "setup.recheck": "Kiểm tra lại",
 "setup.hint": "hoặc chạy  omavoi setup  trong terminal — cùng các bước, cùng thứ tự",

 "hist.problems": 'ĐÃ SAI Ở ĐÂU',
 "hist.steps": 'CÁC BƯỚC LLM',
 "hist.fellthrough": 'thất bại, giữ lại văn bản trước đó',
 "hist.none": "chưa có bản ghi nào — giữ %1 và nói",
 "hist.yourkey": "phím của bạn",
 "hist.dropped": "đã bỏ — ",
 "hist.audio": "âm thanh",
 "hist.level": "mức",
 "hist.decode": "giải mã",
 "hist.model": "mô hình",
 "hist.language": "ngôn ngữ",
 "hist.mode": "chế độ",
 "hist.injected": "cách chèn",
 "hist.said": "mô hình nghe thành:  ",
 "hist.post": "HẬU XỬ LÝ",
 "hist.segments": "ĐỘ TIN CẬY TỪNG ĐOẠN",
 "hist.copy": "Sao chép",
 "hist.play": "Phát",
 "hist.delete": "Xóa",

 "modes.wontfit": 'cần %1 trống',
 "modes.blocked": 'chưa chuyển — mô hình của chế độ này hiện không vừa VRAM',
 "modes.speechmodel": "mô hình giọng nói",
 "modes.speechglobal": "dùng mặc định",
 "modes.speechglobalnamed": "dùng mặc định (%1)",
 "modes.speechonly1": "Mới tải một mô hình giọng nói. Thẻ Mô hình có mô hình nhỏ hơn, hợp với chế độ cần tốc độ hơn độ chính xác.",
 "modes.newname": "tên chế độ mới",
 "modes.here": "đang dùng",
 "modes.fallback": "dự phòng",
 "modes.followwin": "Chế độ đi theo cửa sổ đang được chọn",
 "modes.everytake": "Mọi bản ghi đều dùng ",
 "modes.longestwins": "Mẫu khớp dài nhất bên dưới thắng; không khớp gì thì quay về default.",
 "modes.matchoff": "Việc khớp theo cửa sổ đang tắt, nên các danh sách bên dưới đã được "
                   "cấu hình nhưng không có tác dụng. Nó cần được tinh chỉnh cho từng "
                   "ứng dụng trước khi đáng dùng.",
 "modes.hiddenauto": "Cửa sổ đang được chọn quyết định chế độ, nên bấm vào một chế độ bên dưới chỉ mở nó ra.",
 "modes.following": "theo cửa sổ",
 "modes.fixed": "chọn tại đây",
 "modes.delete": "Xóa chế độ",
 "modes.opens": "MỞ KHI",
 "modes.notinuse": "không dùng khi chế độ đang cố định",
 "modes.nothing": "không có — chế độ này chỉ gọi được bằng tên",
 "modes.classph": "class cửa sổ, ví dụ thunderbird",
 "modes.add": "Thêm",
 "modes.matchhint": "Đối chiếu với class và title của Hyprland. Mẫu khớp dài nhất thắng.",
 "modes.s1": "GIỌNG NÓI",
 "modes.language": "ngôn ngữ nói",
 "modes.decoderhint": "gợi ý nhận dạng",
 "modes.promptph": "vd: Cuộc họp về Hyprland, Quickshell và PipeWire.",
 "modes.s2": "LÀM SẠCH",
 "modes.rulessub": "Không dùng AI: tức thì, và lần nào cũng như nhau.",
 "modes.r.hallucinations": "gộp câu lặp lại",
 "modes.r.fillers": "bỏ từ đệm",
 "modes.r.dictionary": "từ điển",
 "modes.r.names": "tên riêng",
 "modes.r.cjk": "khoảng cách giữa CJK và Latin",
 "modes.s3": "AI VIẾT LẠI",
 "modes.llmsub": "Tùy chọn. Mỗi bước tốn thêm vài giây; bước nào lỗi sẽ chuyển tiếp văn bản nó nhận được.",
 "modes.step": "bước ",
 "modes.stepsuffix": "",
 "modes.remove": "Bỏ",
 "modes.stepph": "Hãy bảo nó sửa văn bản, đừng để nó trả lời.",
 "modes.addstep": "+ thêm bước viết lại",
 "modes.weights": "Mô hình",
 "modes.inherit": "dùng mặc định (%1)",
 "modes.nollm": "chưa cấu hình LLM nào — xem thẻ Mô hình",
 "modes.inject.auto": "tự động",
 "modes.inject.type": "gõ từng chữ",
 "modes.inject.clipboard": "dán",
 "modes.langauto": "tự động",
 "modes.s4": "cách nhập",

 "models.speech": "GIỌNG NÓI",
 "models.speechsub": "âm thanh → chữ · chỉ một cái chạy",
 "models.e.vulkan": "Cục bộ · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · trọng số ggml · NVIDIA, AMD và Intel đều được",
 "models.e.vulkan.note": "khoảng 10 MB gói",
 "models.e.api": "API từ xa",
 "models.e.api.sub": "tương thích OpenAI · OpenAI, Groq, SiliconFlow, một server cục bộ",
 "models.e.api.note": "âm thanh sẽ rời khỏi máy này",
 "models.llmcathint": 'được bước của một chế độ gọi theo tên, không phải chuyển toàn cục',
 "models.now": "ĐANG CHẠY",
 "models.running": "đang chạy",
 "models.notloaded": "chưa nạp",
 "models.llmnone": 'chưa nạp — mỗi cái khởi động khi dùng lần đầu',
 "models.coldshort": 'chưa chạy',
 "models.ready": "sẵn sàng",
 "models.nodaemon": "không liên lạc được dịch vụ — không rõ đang nạp những gì",
 "models.f.edit": 'Sửa',
 "models.f.close": 'Đóng',
 "models.f.url": 'URL',
 "models.f.model": 'Mô hình',
 "models.f.key": 'Khóa',
 "models.f.key.place": 'dán vào đây — sẽ vào secrets.toml, không bao giờ vào file cấu hình',
 "models.f.key.save": 'Lưu',
 "models.f.key.saved": 'đã lưu vào secrets.toml, 0600',
 "models.f.key.failed": 'không lưu được',
 "models.f.test": 'Kiểm tra',
 "models.f.testing": 'đang hỏi danh sách mô hình từ điểm cuối…',
 "models.f.testok": 'đã trả lời, %1 mô hình — chọn một bên dưới',
 "models.f.key.have": 'đã lưu một khoá',
 "models.f.key.fromenv": 'đang dùng từ %1 trong môi trường — nó thắng tệp, nên một '
                          'giá trị cũ sẽ đè khoá bạn vừa lưu',
 "models.f.key.fromfile": 'đã lưu trong secrets.toml',
 "models.f.testfail": 'không có phản hồi',
 "models.speechapi": 'ĐIỂM CUỐI GIỌNG NÓI TỪ XA',
 "models.speechapi.sub": 'Âm thanh sẽ ra khỏi máy này. Chọn nó ở trên trong "API từ xa".',
 "models.speechapi.cat": "Danh sách bên dưới là các mô hình giọng nói của engine cục bộ và không được dùng khi engine từ xa đang được chọn.",
 "models.k.agent": 'Agent hệ thống',
 "models.k.agent.sub": "tác nhân lập trình mà Omarchy đang đặt — đã đăng nhập, không cần khoá, mất vài giây khởi động mỗi lần. Lời của bạn đi tới nơi tác nhân đó đang đăng nhập.",
 "models.k.agent.argv": "· lệnh gọi agent này đặt bản chép lời vào dòng lệnh, mà /proc cho mọi tiến trình của người dùng này đọc được",
 "models.k.local": 'Mô hình cục bộ',
 "models.k.local.sub": "llama.cpp, do chương trình này khởi động và quản lý; mỗi bước có thể chọn mô hình riêng từ danh mục bên dưới",
 "models.k.api": 'API từ xa',
 "models.k.api.sub": "tương thích OpenAI — đặt base_url và một khoá. Lời của bạn đi tới địa chỉ đó.",
 "models.k.unset": 'chưa cấu hình',
 "models.stale": "Dịch vụ vẫn đang chạy thứ nó nạp lúc khởi động",
 "models.loaded": "đã nạp ",
 "models.configured": "đã cấu hình ",
 "models.restart": "Khởi động lại dịch vụ",
 "models.list": "MÔ HÌNH · ",
 "models.formathint": "định dạng mà engine này chạy",
 "models.ondisk": "đã có trên đĩa",
 "models.downloading": "đang tải…",
 "models.download": "Tải về",
 "models.use": "Dùng",
 "models.remove": "Xóa",
 "models.ourstore": "kho của chúng ta",
 "models.outside": "Mô hình tìm thấy ngoài %1 sẽ được dùng ngay tại chỗ và không bao giờ bị xóa.",
 "models.llm": "LLM",
 "models.llmsub": "chữ → chữ · bao nhiêu cũng được, các chế độ gọi theo tên",
 "models.nokey": "chưa có khóa",
 "models.endpointnote": "Các endpoint nằm dưới [llm.<name>] — omavoi config edit. Khóa "
                        "không bao giờ nằm trong file cấu hình: hãy đặt biến môi trường "
                        "của nó, hoặc để trong secrets.toml.",
 "models.seg.speech": 'mô hình giọng nói',
 "models.seg.other": 'chương trình khác',
 "models.vramsub": "đang dùng trên toàn máy",
 "models.vramnote": "Giữ cả hai thường trú mới là điểm chính: một chuỗi phải nạp trọng số "
                    "mỗi lần ghi sẽ tốn hàng giây, không phải hàng mili giây. Nếu vượt quá "
                    "dung lượng, thứ bị đẩy ra là mô hình giọng nói — việc nhập bằng giọng "
                    "chậm đi mười lần mà không có gì nói cho bạn biết vì sao.",

 "models.vram": "VRAM · ",
 "models.sharednote": 'GPU này không có bộ nhớ riêng — trọng số nằm trong bộ nhớ hệ thống thông thường, và thanh phía trên là toàn bộ máy. Giữ cả hai thường trú vẫn là điểm chính, nhưng vượt quá ở đây phải trả bằng swap chứ không phải bị đẩy ra: việc nhập bằng giọng sẽ treo hẳn thay vì chỉ chậm đi, và mọi thứ khác trên máy treo theo.',
 "models.shared": 'Bộ nhớ dùng chung · ',
 "models.needs": "cần",
 "dict.rules": "quy tắc",
 "dict.names": "tên riêng",
 "dict.blurb": "nghe thành → thật ra là. Prompt của bộ giải mã chỉ là gợi ý mà mô hình có "
               "thể bỏ qua; đây mới là thứ bảo đảm. Khóa dài nhất được thử trước, nên một "
               "khóa ngắn hơn nằm bên trong nó sẽ không bao giờ chạy.",
 "dict.shadowed": "không bao giờ chạy — bị che bởi ",
 "dict.remove": "Bỏ",
 "dict.heard": 'nghe thành',
 "dict.meant": 'đúng ra là',
 "dict.add": 'Thêm',
 "dict.heardph": 'hyper land',
 "dict.meantph": 'Hyprland',
 "dict.nameph": 'Hyprland  Postgres  Wayland — thêm nhiều cái một lúc cũng được',
 "dict.namesblurb": "Chỉ viết dạng đúng. Tên riêng được đưa vào prompt của bộ giải mã để mô "
                    "hình tạo ra chúng, rồi sau đó khớp theo âm để các từ đồng âm quay về "
                    "đúng dạng. Việc khớp vẫn tắt cho đến khi bạn xem một lần chạy thử — "
                    "đây là thứ duy nhất ở đây có thể làm hỏng văn bản vốn đã đúng.",
 "dict.matching": "đang khớp",
 "dict.seedonly": "chỉ đưa vào prompt",
 "dict.dryrun": "Chạy thử",
 "dict.enable": "Bật việc khớp",
 "dict.prompt": "prompt: ",
 "dict.none": "(không có)",
 "dict.overbudget": "%1 tên nữa không vừa hạn mức prompt",
 "set.ptt": "giữ để nói",
 "set.toggle": "bấm để bắt đầu, bấm lại để dừng",
 "set.dwell.always": "luôn luôn",
 "set.dwell.changed": "khi có thay đổi",
 "set.dwell.never": "không bao giờ",
 "set.hotkey": "PHÍM NÓNG",
 "set.key.type": "hoặc gõ tên, vd F9",
 "set.key.rebind": 'Bấm một phím',
 "set.key.press": "đang chờ — bấm ngay, hoặc giữ một tổ hợp phím",
 "set.key": "phím",
 "set.behaviour": "cách bấm",
 "set.key.check": 'Kiểm tra lại',
 "set.key.ok": 'đang nghe trên %1',
 "set.key.testing": 'đang kiểm tra…',
 "set.key.badname": '%1 không phải là phím máy này có — hãy bấm một phím thay vì vậy',
 "set.key.nogroup": 'Bạn không ở trong nhóm `input`, nên không mở được bàn phím nào — '
                    'phím được đọc trực tiếp từ thiết bị, bên dưới màn hình nền',
 "set.key.relogin": 'Bạn đã ở trong nhóm `input`, nhưng phiên này bắt đầu trước đó — daemon có thể khởi động cùng nhóm ngay bây giờ, không cần đăng xuất',
 "set.key.nodevice": 'Không bàn phím nào ở đây báo %1 — hãy bấm một phím khác',
 "set.key.stopped": 'Dịch vụ nền không chạy, nên không có gì đang nghe',
 "set.key.stale": 'Dịch vụ vẫn đang nghe trên %1 — nó chưa nhận thay đổi này',
 "set.key.off": 'Phím tắt đang bị tắt',
 "set.key.fix.restart": 'Khởi động lại',
 "set.key.fix.regroup": 'Khởi động cùng nhóm',
 "set.key.fix.group": 'Thêm tôi vào `input`',
 "set.hotkeynote": "Phím được nhận theo vị trí thật trên bàn phím, nên đổi bố cục bàn phím không ảnh hưởng, và phím vẫn làm được việc cũ.",
 "set.preroll": "ghi sớm hơn",
 "set.prerollwhy": "Giữ một chút âm thanh trước khi nhấn phím, để từ đầu tiên không bị cắt.",
 "set.tail": "ghi thêm sau khi thả",
 "set.warnbelow": "cảnh báo âm lượng dưới",
 "set.maxtake": "ghi lâu nhất",
 "set.hud": "TRÊN MÀN HÌNH",
 "set.hud.show": "hiển thị",
 "set.hud.size": "kích thước",
 "set.size.xs": "nhỏ",
 "set.size.s": "vừa",
 "set.size.m": "lớn",
 "set.keepup": "hiện kết quả",
 "set.hudnote": "Thường kết quả chỉ hiện thoáng qua. “Khi có thay đổi” sẽ giữ lâu hơn khi quy tắc hoặc AI đã sửa lời bạn, hoặc có sự cố. Chọn “không bao giờ” thì lời bạn nói sẽ không hiện trên màn hình.",
 "set.notifications": "thông báo",
 "set.on": "bật",
 "set.off": "tắt",
 "set.history": "LỊCH SỬ VÀ QUYỀN RIÊNG TƯ",
 "set.keepaudio": "giữ bản ghi âm",
 "set.takes": " bản ghi",
 "set.historynote": "Chỉ giữ chừng này bản ghi âm mới nhất để nghe lại; văn bản của mỗi lần vẫn được giữ. Đặt 0 để không giữ bản nào.",
 "set.clearhistory": "Xóa toàn bộ lịch sử",
 "set.clearnote": "Mọi bản ghi, và mọi tệp âm thanh còn trên đĩa, cùng một lúc. Không hoàn tác được — muốn xóa từng cái thì nhấp chuột phải trong tab lịch sử.",
 "set.clear.confirm": "Xóa mọi bản ghi và mọi tệp âm thanh? Không thể hoàn tác.",
 "set.clear.cancel": "Hủy",
 "set.clear.go": "Xóa tất cả",
 "set.neverleaves": "Âm thanh không bao giờ rời khỏi máy này",
 "set.audioleaves": "Âm thanh được tải lên %1",
 "set.privacynote.api": "Công cụ nhận dạng là API từ xa, nên âm thanh mỗi lần ghi đều rời máy này. Chuyển lại công cụ cục bộ ở thẻ Mô hình để giữ âm thanh trên máy.",
 "set.privacynote": "Nhận dạng giọng nói chạy trên máy này. Văn bản chỉ rời máy khi AI viết lại của một chế độ dùng API từ xa hoặc agent hệ thống — thẻ Chế độ cho biết chế độ nào.",
 "set.editconfig": "Chỉnh sửa",
 "set.restart": "Khởi động lại dịch vụ nền",
 "set.configpath": "Mọi cài đặt nằm trong ~/.config/omavoi/config.toml.",
 "bar.stopped": "đã dừng",
 "bar.tip.notinstalled": "Omavoi — chưa được cài. Bấm để thiết lập.",
 "bar.tip.ready": "Omavoi — sẵn sàng",
 "bar.tip.recording": "Đang ghi · thả phím để chuyển thành chữ",
 "bar.tip.rightclick": "Nhấp chuột phải để bắt đầu hoặc dừng một lần đọc",
 "bar.tip.stopped": "Omavoi — dịch vụ nền không chạy. Bấm để mở bảng điều khiển.",
 "bar.tip.transcribing": "Đang chuyển thành chữ…",
 "bar.tip.unfinished": "Omavoi — cài đặt chưa xong (%1)",
 "dict.dryrun.none": "Sẽ không có gì thay đổi.",
 "dict.dryrun.running": "Chạy thử · đang chạy…",
 "edit.revert": "Hoàn tác",
 "edit.save": "Lưu",
 "edit.unsaved": "chưa lưu",
 "first.dbstale.age": "Cơ sở dữ liệu gói của bạn đã cũ %1 ngày.",
 "first.dbstale.age1": "Cơ sở dữ liệu gói của bạn đã cũ một ngày.",
 "models.notready": "chưa sẵn sàng",
 "modes.speechnone": "Chưa tải mô hình giọng nói nào — thẻ Mô hình có sẵn.",
 "modes.pick.title": "chuyển chế độ",
 "modes.langfixed": "Chỉ nghe ngôn ngữ này: ổn định hơn nếu bạn chủ yếu nói nó, nhưng ngôn ngữ khác có thể ra sai.",
 "modes.script": "chữ Hán",
 "modes.script.none": "giữ như nhận dạng",
 "modes.script.hans": "giản thể",
 "modes.script.hant": "phồn thể",
 "modes.droppunct": "bỏ dấu câu cuối",
 "modes.addwhich": "viết lại bằng:",
 "modes.adv": "NÂNG CAO",
 "modes.adv.changed": "đã đổi: %1",
 "modes.adv.sep": ", ",
 "modes.adv.kv": "%1: %2",
 "modes.adv.cleanup": "làm sạch",
 "modes.speechreload": "Khi chuyển sang chế độ này, mô hình đó được tải trước, mất vài giây.",
 "modes.prompthint": "Bộ nhận dạng đọc đoạn này trước khi nghe — chỉ là gợi ý, không bảo đảm. Từ trong Từ điển của tôi được tự thêm vào.",
 "modes.promptinherited": "Chế độ này không có gợi ý riêng nên dùng của default. Lưu tại đây sẽ tạo gợi ý riêng cho nó.",
 "modes.inject.hint.auto": "Gõ văn bản, trừ trong ứng dụng Electron như VS Code, Slack và trình duyệt Chromium, nơi nó dán vào. Ứng dụng X11 được gõ bằng xdotool.",
 "modes.inject.hint.type": "Luôn gõ qua wtype — trừ ứng dụng X11, được gõ bằng xdotool.",
 "modes.inject.hint.paste": "Luôn dán, rồi trả lại bộ nhớ tạm của bạn — trừ ứng dụng X11, được gõ bằng xdotool.",
 "modes.sum.ai": "AI: %1",
 "modes.sum.plain": "không AI",
 "modes.sum.hans": "Trung giản thể",
 "modes.sum.hant": "Trung phồn thể",
 "modes.sum.nopunct": "không dấu câu cuối",
 "modes.sum.paste": "dán",
 "modes.sum.type": "gõ",
 "setup.optional": "tùy chọn",
 "set.hotkey.sub": "Phím dùng để nói. Lời bạn nói sẽ xuất hiện ở vị trí con trỏ.",
 "set.hud.sub": "Thanh nhỏ ở cuối màn hình khi bạn nói.",
 "set.notifynote": "Thông báo khi bản ghi có cảnh báo hoặc không nghe thấy gì.",
 "set.history.sub": "Lịch sử chỉ được lưu trên máy này.",
 "set.tailwhy": "Ghi thêm một chút sau khi thả phím, để từ cuối không bị cắt.",
 "set.warnwhy": "Bản ghi nhỏ hơn mức này sẽ được đánh dấu trong Lịch sử — âm quá nhỏ là nguyên nhân thường gặp khiến mất chữ.",
 "set.maxwhy": "Việc ghi tự dừng sau khoảng thời gian này.",
 "set.configfile": "tệp cấu hình",
}

# My dictionary: one word and its optional corrections.
PACK.update({'word.add': 'Thêm từ',
 'word.edit': 'Sửa từ',
 'word.intro': 'Thêm tên riêng và thuật ngữ để giúp Omavoi viết đúng.',
 'word.spelling': 'Cách viết mong muốn',
 'word.examples': 'Ví dụ: Nguyễn An, Acme, JavaScript',
 'word.spaces': 'Nhập đầy đủ tên hoặc cụm từ. Có thể dùng dấu cách.',
 'word.wrong': 'Vẫn thường viết sai?',
 'word.heard': 'Omavoi thường viết thành gì?',
 'word.another': 'Thêm cách viết khác',
 'word.removealias': 'Bỏ',
 'word.replacehelp': 'Các cách viết này sẽ đổi thành “%1”. Chỉ thêm nội dung bạn luôn muốn sửa.',
 'word.more': 'Tùy chọn khác',
 'word.hint': 'Hỗ trợ nhận dạng từ này',
 'word.hinthelp': 'Cung cấp từ cho dịch vụ nhận dạng. Dịch vụ đám mây có thể nhận từ cùng âm thanh.',
 'word.case': 'Dùng kiểu viết hoa này',
 'word.sound': 'Sửa cách viết có âm gần giống',
 'word.soundhelp': 'Có thể đổi cả từ đã đúng. Hãy xem trước kết quả.',
 'word.scope': 'Áp dụng trong',
 'word.allmodes': 'Tất cả chế độ',
 'word.previewhelp': 'Dán một câu để xem kết quả, không ghi âm hay gọi dịch vụ AI.',
 'word.sample': 'Dán câu để thử…',
 'word.preview': 'Xem trước sửa đổi',
 'word.casewarning': 'Tùy chọn này cũng đổi %1. Có thể tắt trong Tùy chọn khác.',
 'word.save': 'Lưu',
 'word.cancel': 'Hủy',
 'word.discardhelp': 'Bỏ các thay đổi chưa lưu?',
 'word.keepediting': 'Tiếp tục sửa',
 'word.discard': 'Bỏ thay đổi',
 'word.search': 'Tìm từ hoặc cách viết sai…',
 'word.from': 'Sửa:',
 'word.paused': 'Đã tạm dừng',
 'word.pause': 'Tạm dừng từ',
 'word.resume': 'Dùng lại từ',
 'word.delete': 'Xóa từ và các cách sửa',
 'word.undo': 'Hoàn tác',
 'word.empty': 'Thêm tên hoặc từ Omavoi thường viết sai.',
 'word.noresults': 'Không tìm thấy từ phù hợp.',
 'word.loading': 'Đang tải từ điển…',
 'word.saved': 'Đã lưu.',
 'word.pending': 'Đã lưu nhưng chưa có hiệu lực. Thử lại hoặc khởi động dịch vụ giọng nói.',
 'word.retry': 'Thử lại',
 'word.refresh': 'Tải lại và giữ bản nháp',
 'word.failed': 'Không lưu được. Nội dung đã nhập vẫn còn.',
 'word.readfailed': 'Không đọc được từ điển. Hãy thử lại.',
 'word.stale': 'Từ điển đã thay đổi ở nơi khác. Tải lại; bản nháp vẫn được giữ.',
 'word.duplicate': 'Từ này đã có. Hãy sửa mục hiện có.',
 'word.conflict': 'Cách viết này xung đột với từ hoặc cách sửa khác.',
 'word.invalid': 'Nhập 1–200 ký tự, không xuống dòng.',
 'word.correct': 'Cách viết này đã đúng, không cần sửa.',
 'word.invalidmode': 'Chế độ đã chọn không còn. Hãy chọn lại.',
 'word.missing': 'Từ này đã bị xóa ở nơi khác. Hãy tải lại.',
 'word.capacity': 'Một số từ chưa được dùng làm gợi ý. Các cách sửa vẫn có hiệu lực:',
 'word.legacy': 'Từ điển cũ vẫn dùng được bên dưới. Cần cập nhật dịch vụ giọng nói hoặc xem lại cài đặt '
                'được liệt kê.',
 'word.use': 'Dùng từ điển của tôi',
 'word.partial': 'Bật một phần'})

PACK.update({'word.deleted': 'Đã xóa từ và các cách sửa.',
 'word.restart': 'Khởi động lại dịch vụ giọng nói để dùng từ điển mới. Các từ hiện có chưa thay '
                 'đổi.'})

PACK.update({'modes.langsearch': 'Tìm ngôn ngữ…', 'modes.langempty': 'Không có ngôn ngữ phù hợp', 'modes.langupgrade': 'Cập nhật dịch vụ giọng nói để chọn ngôn ngữ nhập.'})
