import QtQuick

// The UI's text, in one place.
//
// Not Qt's own translation machinery: that wants .ts files compiled to .qm at
// build time, and this plugin is loaded from a directory of QML with nothing
// to build it. A plain table is also inspectable — a missing key shows up as
// the key itself rather than as blank space.
//
// Instantiated per root component (console, HUD, bar module) and handed down
// to child views as a property, because a plugin folder has no import path of
// its own to hang a singleton on.
//
// Product nouns stay untranslated on purpose: wtype, XWayland, PipeWire, ggml,
// VRAM, evdev. Translating a thing you have to type into a terminal or search
// for makes it unfindable.
Item {
  id: root

  // "" follows the environment; anything else wins.
  property string lang: ""

  readonly property var languages: [
    { code: "en", name: "English" },
    { code: "zh", name: "简体中文" },
    { code: "th", name: "ไทย" }
  ]

  readonly property string active: {
    if (lang && _table[lang] !== undefined) return lang
    var env = (Qt.locale().name || "en").toLowerCase()
    if (env.indexOf("zh") === 0) return "zh"
    if (env.indexOf("th") === 0) return "th"
    return "en"
  }

  function t(key) {
    var pack = _table[root.active] || {}
    if (pack[key] !== undefined) return pack[key]
    var base = _table.en || {}
    // The key itself, so an untranslated string is visible rather than blank.
    return base[key] !== undefined ? base[key] : key
  }

  // Same, with one substitution. Kept separate so the common case stays a
  // plain lookup.
  function tf(key, a) {
    return String(t(key)).replace("%1", a === undefined ? "" : String(a))
  }

  function nameOf(code) {
    for (var i = 0; i < languages.length; i++)
      if (languages[i].code === code) return languages[i].name
    return code
  }

  readonly property var _table: ({
    en: {
      // ---- nav
      "nav.history": "History",
      "nav.modes": "Modes",
      "nav.models": "Models",
      "nav.dictionary": "Dictionary",
      "nav.settings": "Settings",
      "lang.label": "Language",

      // ---- state
      "state.ready": "Ready",
      "state.idle": "idle",
      "state.recording": "recording",
      "state.transcribing": "transcribing",
      "state.stopped": "daemon stopped",

      // ---- setup
      "setup.prefix": "setup ",
      "setup.title": "Two more pieces to install",
      "setup.blurb": "Nothing here runs until you press it, and every step shows the exact command first. Omarchy deliberately runs nothing from inside a plugin folder, so this screen asks instead.",
      "setup.optional": "optional",
      "setup.copy": "Copy",
      "setup.run": "Run",
      "setup.recheck": "Re-check",
      "setup.hint": "or run  omavoi setup  in a terminal — same steps, same order",

      // ---- history
      "hist.none": "no takes yet — hold %1 and talk",
      "hist.yourkey": "your key",
      "hist.dropped": "dropped — ",
      "hist.audio": "audio",
      "hist.level": "level",
      "hist.decode": "decode",
      "hist.model": "model",
      "hist.language": "language",
      "hist.mode": "mode",
      "hist.injected": "injected",
      "hist.said": "model said:  ",
      "hist.post": "POST-PROCESSING",
      "hist.segments": "SEGMENT CONFIDENCE",
      "hist.copy": "Copy",
      "hist.play": "Play",

      // ---- modes
      "modes.newname": "new mode name",
      "modes.here": "here",
      "modes.fallback": "fallback",
      "modes.followwin": "The mode follows the focused window",
      "modes.everytake": "Every take uses ",
      "modes.longestwins": "The longest match below wins; nothing matching falls back to default.",
      "modes.matchoff": "Window matching is off, so the lists below are configured but inert. It needs tuning per application before it earns its keep.",
      "modes.following": "following the window",
      "modes.fixed": "fixed",
      "modes.activehere": "active in this window",
      "modes.delete": "Delete mode",
      "modes.opens": "OPENS ON",
      "modes.notinuse": "not in use while the mode is fixed",
      "modes.nothing": "nothing — this mode is only reached by name",
      "modes.classph": "window class, e.g. thunderbird",
      "modes.add": "Add",
      "modes.matchhint": "Matched against the Hyprland class and title. The longest match wins.",
      "modes.s1": "1  SPEECH",
      "modes.speechsub": "what the model is told before it decodes",
      "modes.language": "language",
      "modes.langhint": "empty detects it per take; a code like en or zh is faster and steadier",
      "modes.decoderhint": "decoder hint",
      "modes.promptph": "Seeded into the model. Good for jargon it keeps mangling — a hint, not a guarantee; the dictionary is the guarantee.",
      "modes.s2": "2  RULES",
      "modes.rulessub": "deterministic · no latency",
      "modes.r.hallucinations": "hallucinations",
      "modes.r.fillers": "fillers",
      "modes.r.dictionary": "dictionary",
      "modes.r.names": "names",
      "modes.r.cjk": "CJK spacing",
      "modes.keeppunct": "keep end punctuation",
      "modes.s3": "3  LLM",
      "modes.llmsub": "optional · runs in order · a failure keeps the text it was given",
      "modes.step": "step ",
      "modes.stepsuffix": "",
      "modes.remove": "Remove",
      "modes.stepph": "Tell it to edit, not to reply.",
      "modes.nostep": "This mode has no LLM pass, so there is no prompt to write yet. Add one below and its prompt appears here, editable, with a usable default already in it.",
      "modes.addstep": "+ add a step",
      "modes.nollm": "no LLM is configured — see the Models tab",
      "modes.inject.auto": "auto",
      "modes.inject.clipboard": "clipboard",
      "modes.langauto": "auto",
      "modes.s4": "4  INJECT",
      "modes.injecthint": "auto types with wtype, except in XWayland clients and known Electron apps, where it pastes instead — wtype's synthetic keycodes reach those as digits.",

      // ---- models
      "models.speech": "SPEECH",
      "models.speechsub": "audio → text · one runs",
      "models.e.vulkan": "Local · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml weights · NVIDIA, AMD and Intel alike",
      "models.e.vulkan.note": "~10 MB of packages",
      "models.e.cuda": "Local · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2 weights · NVIDIA only",
      "models.e.cuda.note": "~2.2 GB of wheels",
      "models.e.api": "Remote API",
      "models.e.api.sub": "OpenAI-compatible · OpenAI, Groq, SiliconFlow, a local server",
      "models.e.api.note": "audio leaves this machine",
      "models.stale": "The daemon is still running what it started with",
      "models.loaded": "loaded ",
      "models.configured": "configured ",
      "models.restart": "Restart daemon",
      "models.list": "MODELS · ",
      "models.formathint": "the format this engine runs",
      "models.ondisk": "already on disk",
      "models.downloading": "downloading…",
      "models.download": "Download",
      "models.use": "Use",
      "models.remove": "Remove",
      "models.ourstore": "our store",
      "models.outside": "Weights found outside %1 are used where they lie and never deleted.",
      "models.llm": "LLM",
      "models.llmsub": "text → text · any number, named by modes",
      "models.remote": "remote",
      "models.local": "local",
      "models.nokey": "no key",
      "models.usedby": "used by ",
      "models.unused": "not named by any mode — costs nothing until one does",
      "models.endpointnote": "Endpoints live under [llm.<name>] — omavoi config edit. A key never goes in the config: set its environment variable, or put it in secrets.toml.",
      "models.vram": "VRAM · ",
      "models.vramsub": "in use across the whole machine",
      "models.needs": "needs",
      "models.vramnote": "Keeping both resident is the point: a chain that loads weights per take costs seconds, not milliseconds. Overcommit and the speech model is what gets evicted — dictation goes ten times slower with nothing to say why.",

      // ---- dictionary
      "dict.rules": "rules",
      "dict.names": "names",
      "dict.blurb": "heard → meant. A decoder prompt is a hint the model may ignore; this is the guarantee. The longest key is tried first, so a shorter one it contains can never fire.",
      "dict.shadowed": "never fires — shadowed by ",
      "dict.remove": "Remove",
      "dict.namesblurb": "Write only the correct form. Names are seeded into the decoder prompt so the model produces them, and matched by sound afterwards so homophones collapse back. Matching stays off until a dry run has been looked at — it is the one thing here that can damage text that was already right.",
      "dict.matching": "matching",
      "dict.seedonly": "seed only",
      "dict.dryrun": "Dry run",
      "dict.enable": "Enable matching",
      "dict.prompt": "prompt: ",
      "dict.none": "(none)",
      "dict.addrule": "Add one with  omavoi dict add <heard> <meant>",
      "dict.addnames": "Add several at once with  omavoi names add <name> <name> …",

      // ---- settings
      "set.ptt": "push to talk",
      "set.toggle": "toggle",
      "set.dwell.always": "always",
      "set.dwell.changed": "changed",
      "set.dwell.never": "never",
      "set.hotkey": "HOTKEY",
      "set.key": "key",
      "set.behaviour": "behaviour",
      "set.hotkeynote": "Read from evdev, below xkb, so the key stays where it physically is even if your layout remaps it. A modifier cannot be bound in Hyprland instead: pressing one changes the modmask, which fires the release binding at once and records a 0.0s take.",
      "set.audio": "AUDIO",
      "set.preroll": "pre-roll",
      "set.prerollwhy": "Audio kept from before the key went down. Lower it and the first syllable starts going missing while PipeWire opens the stream.",
      "set.tail": "tail",
      "set.warnbelow": "warn below",
      "set.maxtake": "max take",
      "set.hud": "HUD",
      "set.keepup": "keep the result up",
      "set.hudnote": "\"changed\" is the default: a dwell you always pay for turns into noise the moment you dictate two sentences in a row, but a silent correction you never saw is worse.",
      "set.notifications": "notifications",
      "set.on": "on",
      "set.off": "off",
      "set.history": "HISTORY",
      "set.keepaudio": "keep audio for",
      "set.takes": " takes",
      "set.historynote": "Stored audio is what makes re-running a take on another model, and the names dry run, possible. Set it to 0 and those go away with it.",
      "set.privacy": "WHERE YOUR VOICE GOES",
      "set.neverleaves": "Audio never leaves this machine",
      "set.privacynote": "Speech runs on the local GPU in every mode. A mode whose LLM step is a remote model does send the transcribed text out — the Modes tab shows which ones have a step at all.",
      "set.editconfig": "Edit config",
      "set.restart": "Restart daemon",
      "set.configpath": "everything here is  ~/.config/omavoi/config.toml"
    },
    zh: {
      // ---- nav
      "nav.history": "历史",
      "nav.modes": "模式",
      "nav.models": "模型",
      "nav.dictionary": "词典",
      "nav.settings": "设置",
      "lang.label": "语言",

      // ---- state
      "state.ready": "就绪",
      "state.idle": "空闲",
      "state.recording": "录音中",
      "state.transcribing": "转写中",
      "state.stopped": "守护进程已停止",

      // ---- setup
      "setup.prefix": "安装 ",
      "setup.title": "还有两个组件要装",
      "setup.blurb": "这里的每一步都要你按下才会执行，并且会先把完整命令显示出来。Omarchy 有意不执行插件目录里的任何东西，所以这个页面只能来问你。",
      "setup.optional": "可选",
      "setup.copy": "复制",
      "setup.run": "运行",
      "setup.recheck": "重新检查",
      "setup.hint": "或者在终端里运行  omavoi setup  —— 步骤和顺序完全一样",

      // ---- history
      "hist.none": "还没有记录 —— 按住 %1 说话",
      "hist.yourkey": "你的按键",
      "hist.dropped": "已丢弃 —— ",
      "hist.audio": "音频",
      "hist.level": "电平",
      "hist.decode": "解码",
      "hist.model": "模型",
      "hist.language": "语言",
      "hist.mode": "模式",
      "hist.injected": "注入方式",
      "hist.said": "模型原文：  ",
      "hist.post": "后处理",
      "hist.segments": "分段置信度",
      "hist.copy": "复制",
      "hist.play": "播放",

      // ---- modes
      "modes.newname": "新模式名称",
      "modes.here": "当前",
      "modes.fallback": "兜底",
      "modes.followwin": "模式跟随当前焦点窗口",
      "modes.everytake": "每次录音都使用 ",
      "modes.longestwins": "下面匹配最长的规则胜出；都不匹配时回落到 default。",
      "modes.matchoff": "窗口匹配已关闭，下面的列表虽已配置但不会生效。它需要为每个应用逐个调过才值得开启。",
      "modes.following": "跟随窗口",
      "modes.fixed": "固定",
      "modes.activehere": "在当前窗口生效",
      "modes.delete": "删除模式",
      "modes.opens": "触发窗口",
      "modes.notinuse": "模式固定时这里不生效",
      "modes.nothing": "无 —— 这个模式只能按名字调用",
      "modes.classph": "窗口 class，例如 thunderbird",
      "modes.add": "添加",
      "modes.matchhint": "与 Hyprland 的 class 和 title 做匹配，最长的匹配胜出。",
      "modes.s1": "1  语音",
      "modes.speechsub": "解码之前告诉模型的内容",
      "modes.language": "语言",
      "modes.langhint": "留空则每次自动检测；填 en、zh 这样的代码更快也更稳",
      "modes.decoderhint": "解码提示词",
      "modes.promptph": "会喂给模型。适合它总认错的专有名词 —— 这只是提示，不是保证；保证靠词典。",
      "modes.s2": "2  规则",
      "modes.rulessub": "确定性 · 零延迟",
      "modes.r.hallucinations": "幻觉过滤",
      "modes.r.fillers": "语气词",
      "modes.r.dictionary": "词典",
      "modes.r.names": "名称",
      "modes.r.cjk": "中英间距",
      "modes.keeppunct": "保留句末标点",
      "modes.s3": "3  LLM",
      "modes.llmsub": "可选 · 按顺序执行 · 某步失败则保留上一步的文本",
      "modes.step": "第 ",
      "modes.stepsuffix": " 步",
      "modes.remove": "移除",
      "modes.stepph": "让它改写，不要让它回答。",
      "modes.nostep": "这个模式没有 LLM 步骤，所以还没有提示词可写。在下面加一个，它的提示词就会出现在这里，可编辑，并且已经带了一份能直接用的默认内容。",
      "modes.addstep": "+ 添加一步",
      "modes.nollm": "还没有配置 LLM —— 去「模型」页",
      "modes.inject.auto": "自动",
      "modes.inject.clipboard": "剪贴板",
      "modes.langauto": "自动",
      "modes.s4": "4  注入",
      "modes.injecthint": "auto 默认用 wtype 逐字输入；遇到 XWayland 客户端和已知的 Electron 应用则改为粘贴 —— wtype 合成的键码传到那些程序里会变成数字。",

      // ---- models
      "models.speech": "语音",
      "models.speechsub": "音频 → 文本 · 只跑一个",
      "models.e.vulkan": "本地 · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml 权重 · NVIDIA、AMD、Intel 都能跑",
      "models.e.vulkan.note": "约 10 MB 的软件包",
      "models.e.cuda": "本地 · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2 权重 · 仅 NVIDIA",
      "models.e.cuda.note": "约 2.2 GB 的 wheel 包",
      "models.e.api": "远程 API",
      "models.e.api.sub": "兼容 OpenAI 协议 · OpenAI、Groq、SiliconFlow，或自建服务",
      "models.e.api.note": "音频会离开本机",
      "models.stale": "守护进程仍在跑启动时加载的那一个",
      "models.loaded": "已加载 ",
      "models.configured": "已配置 ",
      "models.restart": "重启守护进程",
      "models.list": "模型 · ",
      "models.formathint": "这个引擎使用的权重格式",
      "models.ondisk": "已在磁盘上",
      "models.downloading": "下载中…",
      "models.download": "下载",
      "models.use": "使用",
      "models.remove": "删除",
      "models.ourstore": "我们的模型目录",
      "models.outside": "在 %1 之外找到的权重会就地使用，永不删除。",
      "models.llm": "LLM",
      "models.llmsub": "文本 → 文本 · 可配多个，由模式按名字引用",
      "models.remote": "远程",
      "models.local": "本地",
      "models.nokey": "缺密钥",
      "models.usedby": "被使用于 ",
      "models.unused": "没有任何模式引用它 —— 在被引用前不占任何资源",
      "models.endpointnote": "接入点写在 [llm.<name>] 下 —— omavoi config edit。密钥绝不写进配置文件：设成环境变量，或者放进 secrets.toml。",
      "models.vram": "显存 · ",
      "models.vramsub": "全机范围的占用",
      "models.needs": "需要",
      "models.vramnote": "让两个模型都常驻是关键：每次录音都重新加载权重要花几秒，而不是几毫秒。一旦超配，被换出去的就是语音模型 —— 听写会慢十倍，而且不会有任何提示告诉你为什么。",

      // ---- dictionary
      "dict.rules": "规则",
      "dict.names": "名称",
      "dict.blurb": "听到的 → 想要的。解码提示词只是模型可以无视的建议，这里才是保证。匹配时先试最长的键，所以被它包含的更短的键永远不会触发。",
      "dict.shadowed": "永不触发 —— 被遮蔽于 ",
      "dict.remove": "移除",
      "dict.namesblurb": "只写正确的写法。名称会被喂进解码提示词，让模型倾向于产出它们，之后再按读音匹配，把同音的写法收回来。匹配默认关闭，直到你看过一次试运行 —— 这是这里唯一可能把原本正确的文字改坏的功能。",
      "dict.matching": "匹配中",
      "dict.seedonly": "仅提示",
      "dict.dryrun": "试运行",
      "dict.enable": "开启匹配",
      "dict.prompt": "提示词： ",
      "dict.none": "（无）",
      "dict.addrule": "用  omavoi dict add <听到> <想要>  添加一条",
      "dict.addnames": "用  omavoi names add <名字> <名字> …  一次加多个",

      // ---- settings
      "set.ptt": "按住说话",
      "set.toggle": "按一下切换",
      "set.dwell.always": "总是",
      "set.dwell.changed": "有改动时",
      "set.dwell.never": "从不",
      "set.hotkey": "快捷键",
      "set.key": "按键",
      "set.behaviour": "行为",
      "set.hotkeynote": "直接从 evdev 读取，位于 xkb 之下，所以即使你的键盘布局把它重映射了，这个键的物理位置也不变。换成在 Hyprland 里绑一个修饰键是不行的：按下修饰键会改变 modmask，松开绑定会立刻触发，录出一条 0.0 秒的记录。",
      "set.audio": "音频",
      "set.preroll": "前置缓冲",
      "set.prerollwhy": "保留按键按下之前的一段音频。调小了，PipeWire 打开音频流的这段时间里第一个音节就会开始丢。",
      "set.tail": "尾部延时",
      "set.warnbelow": "低于则警告",
      "set.maxtake": "单次上限",
      "set.hud": "HUD",
      "set.keepup": "结果保持显示",
      "set.hudnote": "默认是 \"changed\"：每次都停留一下，等你连着说两句话就变成了干扰；但一次你根本没看见的静默改写更糟。",
      "set.notifications": "通知",
      "set.on": "开",
      "set.off": "关",
      "set.history": "历史",
      "set.keepaudio": "保留音频",
      "set.takes": " 条",
      "set.historynote": "存下的音频是「换个模型重跑一次」和名称试运行的前提。设成 0，这两个功能也一起没了。",
      "set.privacy": "你的声音去了哪里",
      "set.neverleaves": "音频永不离开本机",
      "set.privacynote": "所有模式的语音识别都跑在本地 GPU 上。但如果某个模式的 LLM 步骤用的是远程模型，转写出来的文本确实会发出去 —— 「模式」页里可以看到哪些模式有 LLM 步骤。",
      "set.editconfig": "编辑配置",
      "set.restart": "重启守护进程",
      "set.configpath": "这里的一切都在  ~/.config/omavoi/config.toml"
    },
    th: {
      // ---- nav
      "nav.history": "ประวัติ",
      "nav.modes": "โหมด",
      "nav.models": "โมเดล",
      "nav.dictionary": "พจนานุกรม",
      "nav.settings": "ตั้งค่า",
      "lang.label": "ภาษา",

      // ---- state
      "state.ready": "พร้อม",
      "state.idle": "ว่าง",
      "state.recording": "กำลังอัดเสียง",
      "state.transcribing": "กำลังถอดเสียง",
      "state.stopped": "เดมอนหยุดทำงาน",

      // ---- setup
      "setup.prefix": "ติดตั้ง ",
      "setup.title": "เหลืออีกสองส่วนที่ต้องติดตั้ง",
      "setup.blurb": "ไม่มีอะไรทำงานจนกว่าคุณจะกด และทุกขั้นจะแสดงคำสั่งจริงให้ดูก่อน Omarchy ตั้งใจไม่รันสิ่งใด จากในโฟลเดอร์ปลั๊กอิน หน้านี้จึงต้องถามคุณแทน",
      "setup.optional": "ไม่บังคับ",
      "setup.copy": "คัดลอก",
      "setup.run": "รัน",
      "setup.recheck": "ตรวจอีกครั้ง",
      "setup.hint": "หรือรัน  omavoi setup  ในเทอร์มินัล — ขั้นตอนและลำดับเดียวกัน",

      // ---- history
      "hist.none": "ยังไม่มีรายการ — กด %1 ค้างไว้แล้วพูด",
      "hist.yourkey": "ปุ่มของคุณ",
      "hist.dropped": "ถูกทิ้ง — ",
      "hist.audio": "เสียง",
      "hist.level": "ระดับ",
      "hist.decode": "ถอดรหัส",
      "hist.model": "โมเดล",
      "hist.language": "ภาษา",
      "hist.mode": "โหมด",
      "hist.injected": "วิธีป้อน",
      "hist.said": "โมเดลได้ยินว่า:  ",
      "hist.post": "การประมวลผลภายหลัง",
      "hist.segments": "ความมั่นใจต่อช่วง",
      "hist.copy": "คัดลอก",
      "hist.play": "เล่น",

      // ---- modes
      "modes.newname": "ชื่อโหมดใหม่",
      "modes.here": "ที่นี่",
      "modes.fallback": "สำรอง",
      "modes.followwin": "โหมดจะตามหน้าต่างที่โฟกัส",
      "modes.everytake": "ทุกครั้งจะใช้ ",
      "modes.longestwins": "กฎที่ตรงยาวที่สุดด้านล่างชนะ ถ้าไม่ตรงเลยจะกลับไปใช้ default",
      "modes.matchoff": "การจับคู่หน้าต่างปิดอยู่ รายการด้านล่างจึงถูกตั้งไว้แต่ไม่ทำงาน ต้องปรับทีละแอปก่อนจะคุ้มค่าที่จะเปิด",
      "modes.following": "ตามหน้าต่าง",
      "modes.fixed": "คงที่",
      "modes.activehere": "ทำงานในหน้าต่างนี้",
      "modes.delete": "ลบโหมด",
      "modes.opens": "เปิดเมื่อ",
      "modes.notinuse": "ไม่ถูกใช้ขณะโหมดถูกตั้งคงที่",
      "modes.nothing": "ไม่มี — โหมดนี้เรียกได้ด้วยชื่อเท่านั้น",
      "modes.classph": "คลาสหน้าต่าง เช่น thunderbird",
      "modes.add": "เพิ่ม",
      "modes.matchhint": "เทียบกับ class และ title ของ Hyprland กฎที่ตรงยาวที่สุดชนะ",
      "modes.s1": "1  เสียงพูด",
      "modes.speechsub": "สิ่งที่บอกโมเดลก่อนเริ่มถอดเสียง",
      "modes.language": "ภาษา",
      "modes.langhint": "ปล่อยว่างจะตรวจทุกครั้ง ใส่รหัสอย่าง en หรือ zh จะเร็วและนิ่งกว่า",
      "modes.decoderhint": "คำใบ้ให้ตัวถอดเสียง",
      "modes.promptph": "ถูกป้อนเข้าโมเดล เหมาะกับศัพท์เฉพาะที่มันเพี้ยนบ่อย — เป็นคำใบ้ ไม่ใช่การรับประกัน ตัวที่รับประกันคือพจนานุกรม",
      "modes.s2": "2  กฎ",
      "modes.rulessub": "แน่นอน · ไม่มีดีเลย์",
      "modes.r.hallucinations": "การหลอน",
      "modes.r.fillers": "คำเติม",
      "modes.r.dictionary": "พจนานุกรม",
      "modes.r.names": "ชื่อเฉพาะ",
      "modes.r.cjk": "ระยะห่าง CJK",
      "modes.keeppunct": "คงเครื่องหมายท้ายประโยค",
      "modes.s3": "3  LLM",
      "modes.llmsub": "ไม่บังคับ · ทำตามลำดับ · ถ้าล้มเหลวจะคงข้อความเดิมไว้",
      "modes.step": "ขั้น ",
      "modes.stepsuffix": "",
      "modes.remove": "เอาออก",
      "modes.stepph": "สั่งให้แก้ข้อความ ไม่ใช่ให้ตอบ",
      "modes.nostep": "โหมดนี้ไม่มีขั้น LLM จึงยังไม่มีพรอมป์ตให้เขียน เพิ่มด้านล่างแล้วพรอมป์ตจะปรากฏที่นี่ แก้ไขได้ และมีค่าเริ่มต้นที่ใช้งานได้อยู่แล้ว",
      "modes.addstep": "+ เพิ่มขั้น",
      "modes.nollm": "ยังไม่ได้ตั้งค่า LLM — ดูที่แท็บโมเดล",
      "modes.inject.auto": "อัตโนมัติ",
      "modes.inject.clipboard": "คลิปบอร์ด",
      "modes.langauto": "อัตโนมัติ",
      "modes.s4": "4  การป้อนข้อความ",
      "modes.injecthint": "auto จะพิมพ์ด้วย wtype ยกเว้นไคลเอนต์ XWayland และแอป Electron ที่รู้จัก ซึ่งจะใช้การวางแทน — คีย์โค้ดสังเคราะห์ของ wtype ไปถึงแอปพวกนั้นเป็นตัวเลข",

      // ---- models
      "models.speech": "เสียงพูด",
      "models.speechsub": "เสียง → ข้อความ · ทำงานตัวเดียว",
      "models.e.vulkan": "ในเครื่อง · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · น้ำหนัก ggml · ใช้ได้ทั้ง NVIDIA, AMD และ Intel",
      "models.e.vulkan.note": "แพ็กเกจราว 10 MB",
      "models.e.cuda": "ในเครื่อง · CUDA",
      "models.e.cuda.sub": "faster-whisper · น้ำหนัก ct2 · NVIDIA เท่านั้น",
      "models.e.cuda.note": "wheel ราว 2.2 GB",
      "models.e.api": "API ระยะไกล",
      "models.e.api.sub": "รองรับรูปแบบ OpenAI · OpenAI, Groq, SiliconFlow หรือเซิร์ฟเวอร์ในเครื่อง",
      "models.e.api.note": "เสียงจะออกจากเครื่องนี้",
      "models.stale": "เดมอนยังรันตัวที่โหลดไว้ตอนเริ่มอยู่",
      "models.loaded": "โหลดแล้ว ",
      "models.configured": "ตั้งค่าไว้ ",
      "models.restart": "รีสตาร์ตเดมอน",
      "models.list": "โมเดล · ",
      "models.formathint": "รูปแบบน้ำหนักที่เอนจินนี้ใช้",
      "models.ondisk": "มีอยู่ในดิสก์แล้ว",
      "models.downloading": "กำลังดาวน์โหลด…",
      "models.download": "ดาวน์โหลด",
      "models.use": "ใช้",
      "models.remove": "ลบ",
      "models.ourstore": "คลังของเรา",
      "models.outside": "น้ำหนักที่พบนอก %1 จะถูกใช้ตามที่อยู่เดิมและไม่ถูกลบ",
      "models.llm": "LLM",
      "models.llmsub": "ข้อความ → ข้อความ · มีได้หลายตัว โหมดเรียกตามชื่อ",
      "models.remote": "ระยะไกล",
      "models.local": "ในเครื่อง",
      "models.nokey": "ไม่มีคีย์",
      "models.usedby": "ใช้โดย ",
      "models.unused": "ยังไม่มีโหมดใดเรียกใช้ — ไม่กินทรัพยากรจนกว่าจะมี",
      "models.endpointnote": "ปลายทางอยู่ใต้ [llm.<name>] — omavoi config edit คีย์ไม่เคยอยู่ในไฟล์ตั้งค่า: ตั้งเป็นตัวแปรสภาพแวดล้อม หรือใส่ใน secrets.toml",
      "models.vram": "VRAM · ",
      "models.vramsub": "ที่ใช้อยู่ทั้งเครื่อง",
      "models.needs": "ต้องใช้",
      "models.vramnote": "การให้ทั้งสองตัวค้างในหน่วยความจำคือหัวใจ: สายที่โหลดน้ำหนักใหม่ทุกครั้งเสียเวลาเป็นวินาที ไม่ใช่มิลลิวินาที ถ้าจัดเกินโควตา ตัวที่ถูกไล่ออกคือโมเดลเสียงพูด — การพิมพ์ด้วยเสียงจะช้าลงสิบเท่าโดยไม่มีอะไรบอกสาเหตุ",

      // ---- dictionary
      "dict.rules": "กฎ",
      "dict.names": "ชื่อเฉพาะ",
      "dict.blurb": "ที่ได้ยิน → ที่ต้องการ พรอมป์ตของตัวถอดเสียงเป็นเพียงคำใบ้ที่โมเดลอาจเมิน ส่วนนี้คือตัวรับประกัน คีย์ที่ยาวที่สุดถูกลองก่อน คีย์สั้นที่อยู่ข้างในจึงไม่มีวันทำงาน",
      "dict.shadowed": "ไม่เคยทำงาน — ถูกกลบโดย ",
      "dict.remove": "เอาออก",
      "dict.namesblurb": "เขียนเฉพาะรูปที่ถูกต้อง ชื่อจะถูกป้อนเข้าพรอมป์ตของตัวถอดเสียงเพื่อให้โมเดลสร้างมันออกมา แล้วจับคู่ด้วยเสียงภายหลังเพื่อรวมคำพ้องเสียงกลับ การจับคู่จะปิดไว้จนคุณได้ดูผลทดลองก่อน — นี่เป็นสิ่งเดียวในหน้านี้ที่ทำให้ข้อความที่ถูกอยู่แล้วเสียได้",
      "dict.matching": "จับคู่อยู่",
      "dict.seedonly": "ป้อนพรอมป์ตเท่านั้น",
      "dict.dryrun": "ทดลองรัน",
      "dict.enable": "เปิดการจับคู่",
      "dict.prompt": "พรอมป์ต: ",
      "dict.none": "(ไม่มี)",
      "dict.addrule": "เพิ่มด้วย  omavoi dict add <ที่ได้ยิน> <ที่ต้องการ>",
      "dict.addnames": "เพิ่มหลายรายการพร้อมกันด้วย  omavoi names add <ชื่อ> <ชื่อ> …",

      // ---- settings
      "set.ptt": "กดค้างเพื่อพูด",
      "set.toggle": "สลับเปิด/ปิด",
      "set.dwell.always": "เสมอ",
      "set.dwell.changed": "เมื่อมีการแก้",
      "set.dwell.never": "ไม่เลย",
      "set.hotkey": "ปุ่มลัด",
      "set.key": "ปุ่ม",
      "set.behaviour": "พฤติกรรม",
      "set.hotkeynote": "อ่านจาก evdev ซึ่งอยู่ต่ำกว่า xkb ปุ่มจึงอยู่ตำแหน่งจริงเสมอแม้เลย์เอาต์จะรีแมป จะผูกปุ่มมอดิฟายเออร์ใน Hyprland แทนไม่ได้: การกดมันเปลี่ยน modmask ทำให้ทริกเกอร์ปล่อยปุ่มทำงานทันทีและได้รายการยาว 0.0 วินาที",
      "set.audio": "เสียง",
      "set.preroll": "บัฟเฟอร์นำหน้า",
      "set.prerollwhy": "เสียงที่เก็บไว้ก่อนกดปุ่ม ถ้าลดลง พยางค์แรกจะเริ่มหายไปช่วงที่ PipeWire เปิดสตรีม",
      "set.tail": "ส่วนท้าย",
      "set.warnbelow": "เตือนเมื่อต่ำกว่า",
      "set.maxtake": "ความยาวสูงสุด",
      "set.hud": "HUD",
      "set.keepup": "คงผลลัพธ์ไว้บนจอ",
      "set.hudnote": "ค่าเริ่มต้นคือ \"changed\": การค้างจอทุกครั้งจะกลายเป็นสิ่งรบกวนทันทีที่คุณพูดสองประโยคติดกัน แต่การแก้ไขเงียบ ๆ ที่คุณไม่เคยเห็นแย่กว่า",
      "set.notifications": "การแจ้งเตือน",
      "set.on": "เปิด",
      "set.off": "ปิด",
      "set.history": "ประวัติ",
      "set.keepaudio": "เก็บเสียงไว้",
      "set.takes": " รายการ",
      "set.historynote": "เสียงที่เก็บไว้คือสิ่งที่ทำให้รันรายการเดิมด้วยโมเดลอื่น และการทดลองรันชื่อ เป็นไปได้ ตั้งเป็น 0 แล้วสองอย่างนั้นก็หายไปด้วย",
      "set.privacy": "เสียงของคุณไปที่ไหน",
      "set.neverleaves": "เสียงไม่เคยออกจากเครื่องนี้",
      "set.privacynote": "การถอดเสียงทำงานบน GPU ในเครื่องทุกโหมด แต่โหมดที่ขั้น LLM ใช้โมเดลระยะไกล จะส่งข้อความที่ถอดได้ออกไปจริง — แท็บโหมดแสดงว่าโหมดใดมีขั้นนั้นบ้าง",
      "set.editconfig": "แก้ไฟล์ตั้งค่า",
      "set.restart": "รีสตาร์ตเดมอน",
      "set.configpath": "ทุกอย่างในหน้านี้อยู่ที่  ~/.config/omavoi/config.toml"
    }
  })
}
